import json
from pathlib import Path

ROOT = Path(__file__).parent
raw = [
    ("Which statement describes a tuple's defining property?", "Its elements cannot be reassigned after creation", ["Its elements must all have the same type", "It stores values under named keys", "It can contain only numbers"], "A tuple is an ordered collection that cannot have its elements added, removed, or replaced.", "Tuples", 3, "identify tuple immutability", "rates = (2.1, 1.8, 2.5)\n# rates[0] = 3.0  # raises TypeError"),
    ("Given `x = ([1, 2], [3, 4])`, what does `x[0][1] = 7` do?", "Changes the nested list; x becomes ([1, 7], [3, 4])", ["Raises TypeError because x is a tuple", "Replaces the first tuple element with 7", "Creates a new tuple and leaves x unchanged"], "The tuple's references cannot be replaced, but the list referenced by x[0] remains mutable.", "One sneaky exception", 4, "distinguish tuple immutability from nested mutability", "x = ([1, 2], [3, 4])\nx[0][1] = 7\nprint(x)"),
    ("What does `x + y` do when both x and y are tuples?", "Creates a new tuple containing the elements of both", ["Changes x by appending y to it", "Changes y by inserting x at the start", "Creates a list containing both tuples"], "Tuple concatenation returns a new tuple; it does not mutate either original tuple.", "Access and Slice Tuples", 4, "trace tuple concatenation", "x = (1, 2)\ny = (3, 4)\nz = x + y\nprint(z, x, y)"),
    ("For `values = (10, 20, 30, 40, 50)`, what is `values[1:4]`?", "(20, 30, 40)", ["(10, 20, 30, 40)", "(20, 30, 40, 50)", "[20, 30, 40]"], "Tuple slices follow the same start-included, stop-excluded rule as list slices and return a tuple.", "Access and Slice Tuples", 4, "trace tuple slicing", "values = (10, 20, 30, 40, 50)\nprint(values[1:4])"),
    ("What does `rates.count(2.5)` return for `rates = (2.1, 1.8, 2.5, 3.0, 2.8, 1.9, 2.5, 3.2, 2.8, 2.5)`?", "3", ["1", "2", "10"], "count returns the number of occurrences of the specified value; 2.5 appears three times.", "Tuple Methods", 7, "count tuple values", "rates = (2.1, 1.8, 2.5, 3.0, 2.8, 1.9, 2.5, 3.2, 2.8, 2.5)\nprint(rates.count(2.5))"),
    ("What does `rates.index(3.0)` return for this inflation tuple?", "3", ["2", "4", "The value 3.0"], "index returns the first position of a matching value, using zero-based indexing; 3.0 is at index 3.", "Tuple Methods", 7, "find a tuple element index", "rates = (2.1, 1.8, 2.5, 3.0, 2.8, 1.9, 2.5, 3.2, 2.8, 2.5)\nprint(rates.index(3.0))"),
    ("Which loop visits the characters of the string `\"Python\"` one at a time?", "`for letter in \"Python\":`", ["`for letter in range(\"Python\"):`", "`for letter in len(\"Python\"):`", "`for letter in \"Python\"[0]:`"], "A string is iterable, so the loop variable takes each character in sequence.", "Looping Over a Tuple", 5, "recognize iteration over a string", None),
    ("In `for name, age, position in team`, what must each element of team provide for unpacking to work?", "Three values, in the corresponding order", ["A dictionary with three keys", "A single string containing three words", "Three nested lists of equal length"], "Each team record is a three-element tuple, unpacked into the three loop variables.", "Looping Over a List of Tuples", 6, "explain tuple unpacking", "team = [('Ahmed', 20, 'center'), ('Anas', 22, 'point guard')]\nfor name, age, position in team:\n    print(name, age, position)"),
    ('What is the average age of the five players in the team records?', "20.8", ["20.0", "21.0", "104"], "The ages total 104, and 104 divided by 5 is 20.8.", "Looping Over a List of Tuples", 6, "calculate an aggregate over unpacked records", "ages = [20, 22, 22, 21, 19]\nprint(sum(ages) / len(ages))"),
    ('For the team list, what does `team[1][2]` select?', "The second player's position, `point guard`", ["The second player's age, 22", "The third player's position, `shooting guard`", "The second player's name, `Anas`"], "team[1] selects the second tuple; index 2 selects its third field.", "Looping Over a List of Tuples", 6, "index a tuple within a record list", "team = [('Ahmed', 20, 'center'), ('Anas', 22, 'point guard')]\nprint(team[1][2])"),
    ("In `country_capitals`, what is the role of `\"Canada\"` in the expression `country_capitals[\"Canada\"]`?", "It is a key used to look up its associated value", ["It is a positional index into the dictionary", "It is a value searched for among the capitals", "It is a method that returns all dictionary entries"], "Dictionaries are accessed by key; here the key maps to the value Ottawa.", "Dictionary", 8, "interpret dictionary key lookup", "country_capitals = {'Germany': 'Berlin', 'Canada': 'Ottawa', 'England': 'London'}\nprint(country_capitals['Canada'])"),
    ("Which statement about dictionary keys and values is correct?", "Keys are unique; values may be repeated", ["Keys may repeat; values must be unique", "Both keys and values must be unique", "Keys must be strings; values must be numbers"], "A dictionary has at most one value associated with each key, while different keys may map to equal values.", "Dictionary", 8, "distinguish key and value constraints", None),
    ("How does a dictionary lookup differ from list access?", "A dictionary is accessed by key rather than by positional index", ["A dictionary is accessed only by a numeric position", "A dictionary uses slices but not keys", "A dictionary can be accessed only inside a loop"], "Dictionary lookups use keys such as country names; list lookups use positions.", "Why it's called a dictionary", 9, "compare keyed and positional access", None),
    ('Which value cannot be used as a dictionary key because it is mutable?', "A list such as `[1, 2]`", ["A string such as `\"country\"`", "An integer such as `7`", "A tuple such as `(1, 2)`"], "The lesson identifies immutable values such as strings, numbers, and tuples as key candidates; a list can change and is not hashable.", "Creating a Dictionary", 11, "identify an invalid mutable key", None),
    ("Which expression constructs the mapping `{'first_name': 'Rob', 'surname': 'Jone'}` using keyword arguments?", "`dict(first_name='Rob', surname='Jone')`", ["`dict(('first_name', 'Rob'), ('surname', 'Jone'))`", "`dict(first_name: 'Rob', surname: 'Jone')`", "`dict(['first_name', 'Rob'], ['surname', 'Jone'])`"], "dict accepts keyword arguments, with each argument name used as a key.", "Creating a Dictionary", 10, "construct a dictionary with keyword arguments", None),
    ("Which argument shape can be passed to `dict()` to create several key-value pairs?", "An iterable of two-element pairs", ["A flat iterable of alternating keys and values", "A set containing all keys and values", "A tuple containing only the keys"], "The lesson constructs a dictionary from a list of two-element tuples.", "Creating a Dictionary", 10, "recognize dict pair input", "pairs = [('first_name', 'Rob'), ('surname', 'Jone')]\nprint(dict(pairs))"),
    ("How can one dictionary key map to three numbers?", "Store the numbers together in one list as the value", ["Write three comma-separated values after the key", "Repeat the key three times in the dictionary", "Use three colons after the key"], "Each key maps to a single value; a list can package several values into that one value.", "One key, one value", 11, "represent multiple values under one key", None),
    ("For `person = {'name': 'Mona', 'age': 25}`, what does `'age' in person` test?", "Whether `age` is a key in person", ["Whether the value 25 is in person", "Whether person has exactly 25 items", "Whether the key and value are both strings"], "Membership testing directly on a dictionary checks its keys.", "Adding, changing, checking, removing", 14, "interpret dictionary membership", "person = {'name': 'Mona', 'age': 25}\nprint('age' in person)"),
    ("By default, what does `for key in person:` iterate over?", "The dictionary's keys", ["The dictionary's values", "The dictionary's key-value tuples", "The integer positions of its entries"], "The lesson's nested-data example notes that looping over a dictionary directly yields keys.", "Reaching into nested data", 16, "interpret dictionary iteration", "person = {'first_name': 'Mona', 'age': 25}\nfor key in person:\n    print(key)"),
    ("What does `for key, value in pd.items():` allow the loop to access on each iteration?", "Both the key and its associated value", ["Only the key, then the next numeric index", "Only the values and their positions", "A copy of the entire dictionary each time"], "items() supplies key-value pairs, which can be unpacked into two loop variables.", "keys, values, items", 13, "unpack dictionary items", "pd = {'first_name': 'Rob', 'surname': 'Jone'}\nfor key, value in pd.items():\n    print(key, value)"),
    ("Which expression returns the values from `pd`?", "`pd.values()`", ["`pd.keys()`", "`pd.items()`", "`pd.value()`"], "values() supplies the dictionary's values; keys() and items() serve different purposes.", "Dictionary Methods", 12, "select a dictionary view method", None),
    ("In `pd['hobby'] = 'tennis'`, what happens if `hobby` was not already a key?", "A new key-value item is added", ["A KeyError is raised because the key is missing", "The dictionary is replaced with a string", "The value is added to every existing key"], "Subscript assignment adds an item for a new key or updates the value for an existing key.", "Adding, changing, checking, removing", 14, "add a dictionary item", "pd = {}\npd['hobby'] = 'tennis'\nprint(pd)"),
    ("If `pd` contains `{'name': 'Rob'}`, what does `pd['name'] = 'James'` do?", "Replaces the value for the existing key `name`", ["Adds a second `name` key beside the first", "Raises an error because dictionary values cannot change", "Renames the key to `James`"], "Assigning to an existing key updates its associated value; keys remain unique.", "Adding, changing, checking, removing", 14, "update a dictionary value", "pd = {'name': 'Rob'}\npd['name'] = 'James'\nprint(pd)"),
    ("What does `pd.pop('favourite_food')` do when that key exists?", "Removes that key-value item and returns its value", ["Removes the last inserted item regardless of its key", "Returns the value but leaves the item in pd", "Removes every item whose value is a food"], "pop(key) removes the item identified by that key and returns its value.", "Dictionary Methods", 12, "interpret pop by key", "pd = {'favourite_food': 'Pizza', 'hobby': 'tennis'}\nvalue = pd.pop('favourite_food')\nprint(value, pd)"),
    ("What does `del pd['hobby']` remove?", "The item stored under the key `hobby`", ["The last item inserted into pd", "Every dictionary item with a string value", "The variable pd itself"], "The del statement with a key removes that dictionary entry.", "Adding, changing, checking, removing", 14, "interpret deletion by key", None),
    ("After `pd['new'] = 3`, which entry does `pd.popitem()` remove?", "The last inserted key-value pair", ["The first key alphabetically", "The item with the smallest value", "A randomly selected key-value pair"], "The Part 2 methods table describes popitem() as removing the last inserted pair.", "Dictionary Methods", 12, "trace popitem", "pd = {'old': 1}\npd['new'] = 3\nprint(pd.popitem())"),
    ("What does `pd.update({'age': 25, 'city': 'Cairo'})` do?", "Adds or replaces the specified key-value pairs in pd", ["Deletes keys not present in the supplied dictionary", "Returns a new dictionary and leaves pd unchanged", "Converts pd into a list of pairs"], "update merges the supplied pairs into the existing dictionary, replacing values where keys already exist.", "Dictionary Methods", 12, "interpret dictionary update", "pd = {'name': 'Mona', 'age': 24}\npd.update({'age': 25, 'city': 'Cairo'})\nprint(pd)"),
    ("What remains true after `pd2 = pd.copy()` followed by `pd.clear()`?", "pd becomes empty while pd2 retains the original top-level items", ["Both dictionaries become empty because they are aliases", "pd is unchanged and pd2 is empty", "pd2 contains only the last item removed from pd"], "copy() creates a separate top-level dictionary, so clearing pd does not clear pd2.", "Adding, changing, checking, removing", 14, "trace dictionary copy and clear", "pd = {'name': 'Rob', 'age': 25}\npd2 = pd.copy()\npd.clear()\nprint(pd, pd2)"),
    ("What is the main limitation of `pd.copy()` when pd contains a nested list?", "The copy is shallow, so the nested list is still shared", ["The copy always converts nested lists to tuples", "The copy omits all nested values", "The copy changes every dictionary key"], "copy() duplicates the outer dictionary but does not recursively copy nested objects.", "Adding, changing, checking, removing", 14, "identify a shallow-copy limitation", "pd = {'scores': [4, 5]}\npd2 = pd.copy()\npd2['scores'].append(6)\nprint(pd['scores'])"),
    ("What does `pd.clear()` do?", "Removes all items from the dictionary", ["Deletes only the final inserted item", "Deletes the dictionary variable", "Returns a copy and empties that copy"], "clear empties the existing dictionary while the variable still refers to it.", "Dictionary Methods", 12, "interpret clear", None),
    ("Given the person dictionary, what does `person['address']['street']` access?", "The street value inside the nested address dictionary", ["The first character of the address key", "The address dictionary's first positional item", "The list of skills at index street"], "The first lookup retrieves the nested address dictionary; the second lookup retrieves its street value.", "Reaching into nested data", 16, "chain nested dictionary lookups", "person = {'address': {'street': 'Main Road', 'zipcode': '02210'}}\nprint(person['address']['street'])"),
    ("For the person record, what does `person['skills'][2]` return?", "`Node`", ["`React`", "`MongoDB`", "`Python`"], "The skills list is zero-indexed: index 2 selects its third element, Node.", "Reaching into nested data", 16, "index a list stored in a dictionary", "person = {'skills': ['JavaScript', 'React', 'Node', 'MongoDB', 'Python']}\nprint(person['skills'][2])"),
    ('Which data shape is a table-like collection of records?', "A list of dictionaries with the same keys", ["A tuple containing one dictionary key", "A dictionary whose keys are all list positions", "A string containing comma-separated labels"], "Each dictionary can represent a row and its common keys can represent columns.", "A list of dictionaries — the shape of real data", 18, "recognize a table-like data shape", None),
    ('In `avg_hours(entries)`, which values are added before dividing by the number of records?', "The `hours` value from each dictionary in entries", ["The age values from each dictionary", "The number of keys in each dictionary", "The hours key repeated once per record"], "The generator expression selects e['hours'] from every record, then sum adds those values.", "A list of dictionaries — the shape of real data", 18, "trace aggregation over dictionaries", "data = [{'hours': 3}, {'hours': 1}, {'hours': 4}, {'hours': 2}]\nprint(sum(e['hours'] for e in data) / len(data))"),
    ('For the four survey records, what does `avg_hours(data)` return?', "2.5", ["2", "3", "10"], "The hours are 3, 1, 4, and 2; their sum 10 divided by four is 2.5.", "A list of dictionaries — the shape of real data", 18, "calculate a dictionary-record average", "hours = [3, 1, 4, 2]\nprint(sum(hours) / len(hours))"),
    ('With `limit=2`, which names does `heavy_users(data)` return for the four survey records?', "Alice and Charlie", ["Alice, Charlie, and David", "Charlie and David", "Bob and David"], "The condition is strictly greater than 2; Alice has 3 hours and Charlie 4, while David has exactly 2.", "A list of dictionaries — the shape of real data", 18, "apply a strict threshold to records", "data = [{'name': 'Alice', 'hours': 3}, {'name': 'Bob', 'hours': 1}, {'name': 'Charlie', 'hours': 4}, {'name': 'David', 'hours': 2}]\nprint([e['name'] for e in data if e['hours'] > 2])"),
    ('The code iterates over `set(txt.upper())` but counts with `txt.count(i)`. Why can the count be zero for a character in that set?', "The loop uses uppercase characters but count searches the original mixed-case string", ["count works only on tuples, not on strings", "set removes every character that occurs once", "upper changes txt itself before count is called"], "upper() returns uppercase characters for the set, but txt remains unchanged; string count is case-sensitive.", "Character frequency", 15, "diagnose inconsistent case normalization", "txt = 'Hello, I love feps'\nfor char in set(txt.upper()):\n    print(char, txt.count(char))"),
    ('Which correction makes this character-frequency approach case-insensitive: iterate over `set(txt.upper())` and count each character in the unchanged `txt`?', "`text = txt.lower()`; iterate over `set(text)` and count in `text`", ["`text = txt.lower()`; iterate over `set(txt.upper())` and count in `text`", "`text = txt.lower()`; iterate over `set(text)` and count in `txt`", "`text = txt.upper()`; iterate over `set(text)` and count in `txt`"], "Normalize the source once, then iterate over and count in that same normalized string: `text = txt.lower(); for char in set(text): freq[char] = text.count(char)`. This ensures case-insensitive matching.", "Character frequency", 15, "repair character-frequency case handling", None),
    ("For the case-insensitive text `\"Hello, I love feps\"`, how many times does `l` occur?", "3", ["1", "2", "4"], "There are two l characters in Hello and one in love.", "Character frequency", 15, "count a normalized character", "text = 'Hello, I love feps'.lower()\nprint(text.count('l'))"),
    ('For `ad_ctr`, what does `max(ad_ctr.values())` return?', "5.4", ["4.2", "3.8", "1.9"], "The largest click-through rate among the four platforms is Google's 5.4%.", "Looping Over a Dictionary: Marketing", 17, "find the maximum dictionary value", "ad_ctr = {'Google Ads': 5.4, 'Facebook Ads': 3.8, 'Instagram Ads': 4.2, 'LinkedIn Ads': 1.9}\nprint(max(ad_ctr.values()))"),
    ("With `min_ctr=4.0`, which platforms does `suggest_improvement(ad_ctr)` select?", "Facebook Ads and LinkedIn Ads", ["Facebook Ads and Instagram Ads", "Instagram Ads and LinkedIn Ads", "Google Ads and Facebook Ads"], "The function selects rates strictly below 4.0; those are 3.8 and 1.9.", "Looping Over a Dictionary: Marketing", 17, "filter dictionary entries below a threshold", "ad_ctr = {'Google Ads': 5.4, 'Facebook Ads': 3.8, 'Instagram Ads': 4.2, 'LinkedIn Ads': 1.9}\nprint([p for p, c in ad_ctr.items() if c < 4.0])"),
    ('What list is produced by `[k for k, v in ad_ctr.items() if v == top]` for the campaign data?', "`['Google Ads']`", ["`['Facebook Ads']`", "`['Instagram Ads']`", "`['LinkedIn Ads']`"], "top is 5.4, and Google Ads is the only key associated with that value.", "Looping Over a Dictionary: Marketing", 17, "select the key for a maximum value", None),
    ('If `price_change` is zero in the elasticity calculation, what does the guard do?', "Avoids dividing by zero and assigns infinity", ["Sets elasticity to zero", "Skips the product without assigning elasticity", "Changes the price change to one"], "The code checks the denominator before division and assigns float('inf') for zero price change.", "Sheet 4: price elasticity answer", 22, "explain a division-by-zero guard", "price_change = 0\nif price_change != 0:\n    elasticity = 0.2 / price_change\nelse:\n    elasticity = float('inf')\nprint(elasticity)"),
]

essays = [
    {"prompt": "Compare tuples, lists, and dictionaries for storing (a) fixed annual inflation observations, (b) a collection of student records that will be edited, and (c) country-to-capital mappings. For each, choose a suitable type and explain the access and mutability trade-off.", "expectedAnswer": "Use a tuple for fixed inflation observations because it is ordered and immutable. Use a list for editable records when sequence position and iteration are useful. Use a dictionary for country-to-capital mappings because countries act as keys and values are looked up by name; dictionaries are mutable and keys are unique.", "justification": "The recommendation follows the source's distinctions: tuple for fixed ordered data, list for changeable ordered data, and dictionary for mutable key-value mappings accessed by key.", "rubric": ["Selects tuple for fixed observations", "Selects list for editable sequence records", "Selects dictionary for named country-capital lookup", "Explains relevant mutability differences", "Explains positional versus key-based access"], "source": "6_tuples_and_dictionaries.md, Tuples; Dictionaries; PDF pp. 3, 8, 19", "operation": "compare collection types and justify data-structure choices", "stimulusCode": "inflation = (2.1, 1.8, 2.5)\nstudents = ['Mona', 'Ali']\ncapitals = {'Canada': 'Ottawa'}"},
    {"prompt": "Using `team = [('Ahmed', 20, 'center'), ('Anas', 22, 'point guard'), ('Wael', 22, 'shooting guard'), ('Ameer', 21, 'power forward'), ('Ali', 19, 'small forward')]`, write or outline a loop that prints each name and position, calculates average age, then state the result of `team[1][2]` and `team[2:4][1]`.", "expectedAnswer": "Initialize total=0; for name, age, position in team, print name and position and add age to total; then print total/len(team), which is 20.8. team[1][2] is 'point guard'; team[2:4][1] is ('Ameer', 21, 'power forward').", "justification": "Each three-field tuple unpacks into the loop variables; the ages sum to 104, so the average is 104/5=20.8. The requested indices select the second record's third field and the second tuple of the slice.", "rubric": ["Correctly unpacks the three fields and prints name/position", "Accumulates the age for each record", "Calculates average age as 20.8", "Identifies team[1][2] as point guard", "Identifies team[2:4][1] as Ameer’s tuple"], "source": "6_tuples_and_dictionaries.md, List of tuples; PDF p. 6", "operation": "write and trace a loop over unpacked tuple records", "stimulusCode": "team = [('Ahmed', 20, 'center'),\n        ('Anas', 22, 'point guard'),\n        ('Wael', 22, 'shooting guard'),\n        ('Ameer', 21, 'power forward'),\n        ('Ali', 19, 'small forward')]"},
    {"prompt": "Build a dictionary for two survey respondents using a list of `(key, value)` pairs, with each respondent's name and hours. Explain why a list of dictionaries with the same keys represents a table, and show how to retrieve the second respondent's hours. State one valid way to store several scores under one key.", "expectedAnswer": "For example: `rows = [dict([('name','Alice'),('hours',3)]), dict([('name','Bob'),('hours',1)])]`. `rows[1]['hours']` returns 1. The dictionaries are rows and common keys are columns. A list such as `{'scores':[8,9,10]}` stores multiple scores as one value.", "justification": "dict() accepts an iterable of key-value pairs; a list of dictionaries with common keys is row-oriented tabular data; indexing the second row and then its hours key retrieves the requested value.", "rubric": ["Creates a respondent dictionary from key-value pairs", "Uses a list containing two dictionaries with consistent keys", "Retrieves second respondent's hours by key", "Explains rows and columns in the table-like structure", "Shows multiple scores grouped in one list value"], "source": "6_tuples_and_dictionaries.md, Creating dictionaries; One key, one value; list of dictionaries; PDF pp. 10–11, 18", "operation": "construct and query a list of dictionaries", "stimulusCode": "rows = [\n    dict([('name', 'Alice'), ('hours', 3)]),\n    dict([('name', 'Bob'), ('hours', 1)])\n]"},
    {"prompt": "Trace this code. Give `selected`, `removed`, `copied`, and `data` after execution. Explain what `update`, `pop`, `copy`, and `clear` each do.\n\n```python\ndata = {'name': 'Rob', 'age': 24}\ndata.update({'age': 25, 'city': 'Cairo'})\nremoved = data.pop('name')\ncopied = data.copy()\ndata.clear()\nselected = copied['city']\n```", "expectedAnswer": "selected is 'Cairo'; removed is 'Rob'; copied is {'age': 25, 'city': 'Cairo'}; data is {}. update adds city and changes age, pop removes and returns name's value, copy makes a separate outer dictionary, and clear removes every item from data.", "justification": "The operations run in sequence: update changes the mapping, pop returns and removes name, copy snapshots the remaining top-level pairs, and clear empties only data; selected then looks up city in copied.", "rubric": ["Gives selected as Cairo", "Gives removed as Rob", "Gives copied with age 25 and city Cairo", "Gives data as an empty dictionary", "Explains the four methods' effects"], "source": "6_tuples_and_dictionaries.md, Dictionary methods and mutations; PDF pp. 12–14", "operation": "trace dictionary mutations and explain methods", "stimulusCode": "data = {'name': 'Rob', 'age': 24}\ndata.update({'age': 25, 'city': 'Cairo'})\nremoved = data.pop('name')\ncopied = data.copy()\ndata.clear()\nselected = copied['city']"},
    {"prompt": 'Given the survey records, state (a) the average hours, (b) the names returned by `heavy_users(data)` with its default limit, and (c) the names returned by `heavy_users(data, avg)`. Explain how the strict comparison affects David, who has exactly 2 hours.', "expectedAnswer": "The average is (3+1+4+2)/4=2.5. With limit 2, the result is ['Alice','Charlie']; with limit 2.5, it is ['Charlie']. The function tests hours > limit, so David's value of exactly 2 does not pass the default threshold.", "justification": "The given data sum to 10 hours over four respondents. Applying the function's strict greater-than condition selects 3 and 4 above 2, then only 4 above 2.5.", "rubric": ["Calculates mean hours as 2.5", "Returns Alice and Charlie above the default threshold", "Returns Charlie above the average threshold", "Explains that the comparison is strictly greater than", "Explains why David at exactly 2 is excluded"], "source": "6_tuples_and_dictionaries.md, A list of dictionaries; PDF p. 18", "operation": "calculate and apply thresholds to dictionary records", "stimulusCode": "data = [\n    {'name': 'Alice', 'hours': 3},\n    {'name': 'Bob', 'hours': 1},\n    {'name': 'Charlie', 'hours': 4},\n    {'name': 'David', 'hours': 2}\n]"},
    {"prompt": "For campaign rates `{'Google Ads': 5.4, 'Facebook Ads': 3.8, 'Instagram Ads': 4.2, 'LinkedIn Ads': 1.9}`, identify the best platform and the improvement lists for thresholds 4.0 and 2.0. Describe the role of `values()`, `items()`, and the list comprehension in finding these results.", "expectedAnswer": "Google Ads is best at 5.4. Below 4.0 gives ['Facebook Ads','LinkedIn Ads']; below 2.0 gives ['LinkedIn Ads']. values() supplies rates for max; items() supplies key-rate pairs; the comprehension retains keys whose rate is below the threshold.", "justification": "The maximum rate is 5.4, while strict less-than filtering selects 3.8 and 1.9 at threshold 4 and only 1.9 at threshold 2.", "rubric": ["Identifies Google Ads as the maximum", "Gives Facebook Ads and LinkedIn Ads below 4.0", "Gives LinkedIn Ads below 2.0", "Explains values() use for maximum", "Explains items/comprehension key selection"], "source": "6_tuples_and_dictionaries.md, Marketing campaign analysis; PDF p. 17", "operation": "analyze dictionary data using maximum and filtering", "stimulusCode": "ad_ctr = {'Google Ads': 5.4, 'Facebook Ads': 3.8,\n          'Instagram Ads': 4.2, 'LinkedIn Ads': 1.9}\ntop = max(ad_ctr.values())\nbest = [k for k, v in ad_ctr.items() if v == top]"},
    {"prompt": "Repair this character-frequency approach for `txt = 'Hello, I love feps'` so counts are case-insensitive. Show a correct loop and state the counts for `h`, `e`, `l`, and the space character. Explain why iterating over `set(txt.upper())` while counting in `txt` fails for lowercase characters.", "expectedAnswer": "Normalize once with `text = txt.lower()`, initialize `freq = {}`, then loop `for ch in set(text): freq[ch] = text.count(ch)`. Counts are h:1, e:3, l:3, and space:3. `upper()` creates uppercase characters for iteration, but `txt` remains mixed-case and `count` is case-sensitive.", "justification": "Case normalization must be applied to both the iterated characters and the string being counted. In the normalized text, h occurs once, e three times, l three times, and there are three spaces.", "rubric": ["Normalizes the text consistently", "Initializes and builds counts for unique normalized characters", "Gives h=1 and e=3", "Gives l=3 and spaces=3", "Explains that uppercased iteration characters do not match case-sensitive counts in the original mixed-case text"], "source": "6_tuples_and_dictionaries.md, Character frequency; PDF p. 15", "operation": "debug and repair a dictionary frequency program", "stimulusCode": "txt = 'Hello, I love feps'\n# Original approach: for char in set(txt.upper()):\n#                 freq[char] = txt.count(char)"},
    {"prompt": "Using the nested product data below, calculate the signed price elasticity for Laptop and Smartphone from the formula `(percentage change in quantity)/(percentage change in price)`. Then compare direct `elasticity > 1` / `< 1` classification with classification by absolute magnitude, and explain the issue for Laptop.\n\n```python\nproducts = {\n    'Laptop': {'p0': 1000, 'p1': 1500, 'q0': 50, 'q1': 20},\n    'Smartphone': {'p0': 800, 'p1': 1000, 'q0': 200, 'q1': 400}\n}\n```", "expectedAnswer": "Laptop: price change=(1500-1000)/1000=0.5; quantity change=(20-50)/50=-0.6; signed elasticity=-1.2. Smartphone: price change=0.25; quantity change=1.0; elasticity=4.0. Comparing signed values directly with 1 calls -1.2 inelastic, but magnitude-based classification uses |-1.2|>1 and calls it elastic. Compare `abs(elasticity)` with 1.", "justification": "The formula yields -0.6/0.5=-1.2 for Laptop and 1.0/0.25=4.0 for Smartphone. Since demand elasticities can be negative, magnitude must be used for the standard elastic/inelastic distinction; direct signed comparison makes all negative values fall below 1.", "rubric": ["Calculates Laptop percentage changes and signed elasticity -1.2", "Calculates Smartphone percentage changes and elasticity 4.0", "Identifies that comparing signed -1.2 directly with 1 labels Laptop inelastic", "Explains magnitude-based classification makes Laptop elastic", "States a corrected absolute-value comparison"], "source": "6_tuples_and_dictionaries.md, price elasticity example; PDF Sheet 4 Ex 4 pp. 20–22", "operation": "calculate elasticity and critically evaluate a classification rule", "stimulusCode": "products = {\n    'Laptop': {'p0': 1000, 'p1': 1500, 'q0': 50, 'q1': 20},\n    'Smartphone': {'p0': 800, 'p1': 1000, 'q0': 200, 'q1': 400}\n}"},
]

for i, row in enumerate(essays, 1):
    row.update({"id": f"M2L6-E{i:02d}", "responseType": "structured response", "marks": 5, "rubric": [{"criterion": c, "points": 1} for c in row["rubric"]]})

items = []
excluded = {
    "What does `rates.index(3.0)` return for this inflation tuple?",
    "How does a dictionary lookup differ from list access?",
    "What does `pd.clear()` do?",
}
for question, key, distractors, explanation, section, page, operation, code in raw:
    if question in excluded:
        continue
    i = len(items) + 1
    options = [key] + distractors
    target = (i - 1) % 4
    shift = (-target) % 4
    options = options[shift:] + options[:shift]
    item = {
        "id": f"M2L6-{i:03d}", "question": question, "options": options,
        "correctIndex": options.index(key), "expectedAnswer": key,
        "explanation": explanation,
        "source": f"6_tuples_and_dictionaries.md — {section}; Collection Data Types Part 2 PDF p. {page}",
        "objective": "tuples and dictionaries", "operation": operation,
    }
    if code:
        item["stimulusCode"] = code
    items.append(item)

# Balance visible option lengths and keep each correct answer in its assigned position.
balanced_options = {
    "M2L6-001": ["Its elements can be changed, removed, or replaced after creation", "Its elements can contain only one data type", "It stores values under named keys"],
    "M2L6-002": ["Creates a new tuple and leaves x unchanged", "Raises TypeError because x is a tuple", "Changes the nested list and replaces the tuple's first reference with a new list"],
    "M2L6-003": ["Changes x by appending y to it in place", "Creates a list containing both tuples as nested values", "Creates a new tuple holding x and y as two nested values"],
    "M2L6-006": ["`for letter in 'Py':`", "`for letter in range(\"Python\"):`", "`for letter in len(\"Python\"):`"],
    "M2L6-007": ["Three values, but in the wrong order for the named variables", "A dictionary containing the three named fields", "Only one tuple"],
    "M2L6-013": ["`dict(first_name='Rob')`", "`dict(('first_name', 'Rob'), ('surname', 'Jone'))`", "`dict(first_name: 'Rob', surname: 'Jone')`"],
    "M2L6-015": ["Repeat the key three times in the dictionary", "Write each number after the key with commas between them", "Use three colons after the key"],
    "M2L6-016": ["Whether 25 is present", "Whether person has exactly 25 dictionary items", "Whether the key and its value are both strings"],
    "M2L6-017": ["The dictionary values", "The dictionary's key-value pairs", "The integer positions of its entries"],
    "M2L6-019": ["`pd.value()`", "`pd.keys()`", "`dict(pd.items())`"],
    "M2L6-020": ["A KeyError is raised because the key is missing", "It changes pd's type", "The value is added to every existing key"],
    "M2L6-025": ["Adds only new keys without replacing existing values", "Deletes keys missing from the supplied dictionary", "Returns a new dictionary and leaves pd unchanged"],
    "M2L6-026": ["pd2 contains only the last item removed from pd", "pd remains unchanged while pd2 becomes empty", "pd2 is cleared too, because clear empties all dictionaries sharing their values"],
    "M2L6-027": ["The copy omits all nested values", "The copy changes every dictionary key", "The shallow copy recursively duplicates each nested list into a separate object"],
    "M2L6-028": ["The address key's first character in the dictionary's displayed text", "The address dictionary's first positional item", "The zipcode inside the nested address dictionary"],
    "M2L6-029": ["`React`, the second item in the skills list", "`MongoDB`, the fourth item in the skills list", "`Python`, the fifth and final skill in the list"],
    "M2L6-031": ["The number of keys stored in every dictionary record", "The number of hours in the first respondent's record", "The hours key repeated once for each record"],
    "M2L6-032": ["2", "3", "2.75"],
    "M2L6-034": ["Counting runs on the set object, not txt", "`i` is uppercase but `txt` remains mixed case", "The loop's uppercase characters do not match the original text used by count"],
    "M2L6-035": ["`text = txt.lower()`; iterate over `set(txt.upper())` and count in `text`", "`text = txt.lower()`; iterate over `set(text)` and count in `txt`", "`text = txt.upper()`; iterate over `set(text)` and count in `txt`"],
    "M2L6-039": ["[]", "['Facebook Ads']", "['Instagram Ads']"],
}
for item in items:
    if item["id"] in balanced_options:
        choices = [item["expectedAnswer"]] + balanced_options[item["id"]]
        target = (int(item["id"].rsplit("-", 1)[1]) - 1) % 4
        shift = (-target) % 4
        item["options"] = choices[shift:] + choices[:shift]
        item["correctIndex"] = item["options"].index(item["expectedAnswer"])
if next(x for x in items if x["id"] == "M2L6-034")["expectedAnswer"].startswith("The loop uses uppercase"):
    item = next(x for x in items if x["id"] == "M2L6-034")
    item["expectedAnswer"] = "`i` is uppercase, while `txt` remains mixed-case"
    choices = [item["expectedAnswer"], "The set removes characters that occur more than once in the string", "The set counts characters by itself", "upper() changes txt, but count searches a separate lower-case copy"]
    target = (int(item["id"].rsplit("-", 1)[1]) - 1) % 4
    shift = (-target) % 4
    item["options"] = choices[shift:] + choices[:shift]
    item["correctIndex"] = item["options"].index(item["expectedAnswer"])
item = next(x for x in items if x["id"] == "M2L6-029")
item["expectedAnswer"] = "`Node`, the third item"
choices = [item["expectedAnswer"], "`Java`", "`React`, the second skill in the list", "`Python`, the final skill"]
target = (int(item["id"].rsplit("-", 1)[1]) - 1) % 4
shift = (-target) % 4
item["options"] = choices[shift:] + choices[:shift]
item["correctIndex"] = item["options"].index(item["expectedAnswer"])

import sys
sys.path.insert(0, str(ROOT.parent))
from explanation_overrides import apply_overrides
apply_overrides(ROOT.name, items)
(ROOT / "final_items.jsonl").write_text("\n".join(json.dumps(x, ensure_ascii=False) for x in items) + "\n")
(ROOT / "essay_items.jsonl").write_text("\n".join(json.dumps(x, ensure_ascii=False) for x in essays) + "\n")
print(f"created {len(items)} MCQs and {len(essays)} structured responses")
