import json
from pathlib import Path

ROOT = Path(__file__).parent

# question, key, distractors, rationale, Markdown locator, PDF page, operation, code
raw = [
 ("Which statement best distinguishes a built-in function from a user-defined function?", "A built-in is supplied by Python; a user-defined function is written for a program's needs", ["A built-in always returns a value; a user-defined function always prints", "A built-in must be imported from a module; a user-defined function cannot be imported", "A built-in accepts no arguments; a user-defined function must accept arguments"], "Built-ins are already available in Python, while user-defined functions are created for a task.", "Two kinds of function", 3, "distinguish function categories", None),
 ("What happens when Python executes a function definition that has not been called?", "Python binds the function name, but the function body does not run", ["Python runs the body once and then stores its return value", "Python prints the docstring and waits for input", "Python runs the body only if it contains a return statement"], "Defining a function makes it available to call; its body runs when called.", "Writing your own", 6, "interpret a function definition", "def greet():\n    print('Hello')\n"),
 ("What is the role of `def` in a Python function definition?", "It introduces a function definition", ["It calls a function", "It returns a value from a function", "It imports a function from a module"], "The `def` keyword begins a function definition.", "Writing your own", 6, "identify function syntax", None),
 ("In `def add(a, b):`, what are `a` and `b`?", "Parameters named in the function definition", ["The returned values", "The function calls", "The module aliases"], "Parameters are the names that receive input values when the function is called.", "Writing your own", 6, "identify formal parameters", "def add(a, b):\n    return a + b"),
 ('What does `print_hello()` do when called three times?', "It displays the greeting three times", ["It defines three separate functions", "It returns the greeting once and stores it", "It prints the function's docstring three times"], "The function is called three times, and each call prints the greeting.", "Your first function", 8, "trace repeated function calls", "def print_hello():\n    print('Good Morning FEPS')\n\nprint_hello()\nprint_hello()\nprint_hello()"),
 ('What does `add(5, 7)` return?', "12", ["5", "7", "35"], "The function adds its two arguments and returns their sum.", "Parameters and a return value", 8, "evaluate a function call", "def add(a, b):\n    s = a + b\n    return s\n\nprint(add(5, 7))"),
 ("What is the key difference between `print` and `return` inside a function?", "`print` displays output; `return` hands a value back to the caller", ["`print` hands a value back; `return` displays it", "Both always display and return the same value", "`return` defines the function, while `print` calls it"], "Printed output is not automatically a value available to the caller.", "print is not return", 6, "distinguish output from a return value", "def shows(x):\n    print(x * 2)\n\ndef gives(x):\n    return x * 2\n\na = shows(5)\nb = gives(5)"),
 ("After `a = shows(5)` where `shows` only prints `x * 2`, what value is assigned to `a`?", "`None`", ["10", "5", "The string `'10'`"], "A function without an explicit returned value returns None, even if it prints.", "print is not return", 6, "trace implicit return value", "def shows(x):\n    print(x * 2)\n\na = shows(5)\nprint(a)"),
 ("Why can the result of `gives(5)` be used in `b + 1`?", "`gives` returns the number 10 to its caller", ["`gives` prints 10, and printed text is numeric", "The variable `b` refers to the function body", "Python converts every printed number into an integer"], "`return x * 2` provides a numeric value that can participate in another expression.", "print is not return", 6, "apply a returned value", "def gives(x):\n    return x * 2\n\nb = gives(5)\nprint(b + 1)"),
 ("For `my_avg(10, 20)` defined as `(x + y) / 2`, what is returned?", "15.0", ["30", "10", "20.0"], "The arithmetic mean is (10+20)/2; Python's `/` produces a float.", "Average of two numbers", 9, "calculate a function result", "def my_avg(x, y):\n    return (x + y) / 2\n\nprint(my_avg(10, 20))"),
 ("In `my_avg_list(L)`, why does the function initialize `s = 0` before its loop?", "It gives the accumulator a starting value before adding list items", ["It sets the list length to zero", "It makes the function return zero after the loop", "It prevents the loop from visiting the first item"], "The accumulator starts at zero and is increased once for each item.", "Average of a whole list", 9, "explain accumulator initialization", "def my_avg_list(L):\n    s = 0\n    for i in L:\n        s += i\n    return s / len(L)"),
 ("What does the guard clause in `loan_payment` do when `annual_rate == 0`?", "It returns an equal monthly repayment before the formula divides by zero", ["It changes the annual rate to 100 percent", "It skips the payment calculation and returns the principal", "It raises an error to prevent an interest-free loan"], "With zero interest, the standard formula's denominator becomes zero, so the function handles that case separately.", "Monthly loan payment", 11, "interpret a guard clause", "def loan_payment(principal, annual_rate, years):\n    months = years * 12\n    if annual_rate == 0:\n        return principal / months\n    monthly_rate = annual_rate / (100 * 12)\n    R = (1 + monthly_rate) ** months\n    return round((principal * monthly_rate * R) / (R - 1), 2)"),
 ("In the loan function, how is an annual rate given as a percentage converted to a monthly decimal rate?", "Divide by `100 * 12`", ["Multiply by `100 * 12`", "Divide by 12 and then add 100", "Subtract 12 and divide by 100"], "The annual percentage is converted to a decimal and divided across 12 months.", "Monthly loan payment", 11, "interpret a rate conversion", "monthly_rate = annual_rate / (100 * 12)"),
 ("A function receives three scores, calculates their mean, and divides the sum of squared deviations by 3. Which variance convention is it using?", "Population variance for the three provided scores", ["Sample variance, dividing by 2", "Standard deviation, taking a square root", "Range, subtracting the minimum from the maximum"], "The example divides by the number of values (3), not n-1, and does not take a square root.", "Descriptive statistics example", 12, "classify a variance calculation", "v = ((x-m)**2 + (y-m)**2 + (z-m)**2) / 3"),
 ('If both default parameters are omitted from `generate_full_name`, what name is returned?', "Arwa Mohammed", ["Mona Saber", "Arwa Saber", "Mona Mohammed"], "Both parameters default to Arwa and Mohammed.", "Default parameters and named arguments", 13, "evaluate default arguments", "def generate_full_name(first_name='Arwa', last_name='Mohammed'):\n    return first_name + ' ' + last_name\n\nprint(generate_full_name())"),
 ("What does `generate_full_name(last_name='Saber')` return when the defaults are Arwa and Mohammed?", "Arwa Saber", ["Saber Arwa", "Arwa Mohammed", "Saber Mohammed"], "The named argument overrides only `last_name`; the first name keeps its default.", "Default parameters and named arguments", 13, "trace a named argument with defaults", "def generate_full_name(first_name='Arwa', last_name='Mohammed'):\n    return first_name + ' ' + last_name\n\nprint(generate_full_name(last_name='Saber'))"),
 ("What does the `*nums` parameter collect in `sum_all_nums(*nums)`?", "The extra positional arguments as a tuple", ["All keyword arguments as a dictionary", "The function's return values as a list", "A single required list argument"], "A parameter prefixed with `*` collects any number of positional arguments into a tuple.", "Dynamic parameters with *", 14, "interpret a variable-length parameter", "def sum_all_nums(*nums):\n    return nums\n\nprint(sum_all_nums(2, 3, 5))"),
 ("What value does `sum_all_nums(2, 3, 5, 10, 20)` return?", "40", ["20", "25", "10"], "The function accumulates all five supplied values: 2+3+5+10+20=40.", "Dynamic parameters with *", 14, "calculate a variadic function result", "def sum_all_nums(*nums):\n    total = 0\n    for i in nums:\n        total += i\n    return total\n\nprint(sum_all_nums(2, 3, 5, 10, 20))"),
 ("In `def generate_groups(team, *args):`, what does `team` receive when called as `generate_groups('Team-1', 'Ana', 'Mona')`?", "The first positional argument, `'Team-1'`", ["All three arguments as one tuple", "The final positional argument, `'Mona'`", "No value, because `*args` must come first"], "The fixed parameter consumes the first positional argument; remaining positional arguments go into `args`.", "One fixed parameter and several dynamic parameters", 14, "trace mixed fixed and variable arguments", "def generate_groups(team, *args):\n    return team, args\n\nprint(generate_groups('Team-1', 'Ana', 'Mona'))"),
 ('In `get_power(f, x)`, what value is passed as `f` by `get_power(square_number(5), 3)?', "25, because `square_number(5)` is called before `get_power`", ["The function object `square_number`", "5, because the argument is the input to `square_number`", "125, because both functions run as one expression"], "Python evaluates the argument expression `square_number(5)` first; this example passes its returned value, not the function itself.", "Function as a parameter example", 15, "analyze argument evaluation", "def square_number(n):\n    return n * n\n\ndef get_power(f, x):\n    return pow(f, x)\n\nprint(get_power(square_number(5), 3))"),
 ("What does `get_power(square_number(5), 3)` calculate?", "`25 ** 3`, which is 15,625", ["`5 ** 3`, which is 125", "`(5 ** 2) * 3`, which is 75", "`3 ** 25`, which is a different power"], "The first argument evaluates to 25, then `pow(25, 3)` returns 15,625.", "Function as a parameter example", 15, "trace nested function calls", "def square_number(n):\n    return n * n\n\ndef get_power(f, x):\n    return pow(f, x)\n\nresult = get_power(square_number(5), 3)"),
 ("A function-local variable `y` is assigned inside `print_var`. What happens if the main program tries to use that local `y` after the call?", "It is not available there; the reference raises a `NameError`", ["It reads the value from the most recent call", "It automatically becomes a global variable", "It is available only until the next function definition"], "A local variable is scoped to the function in which it is created.", "Variable scope", 16, "apply local scope rules", "def f():\n    y = 10\n\nf()\nprint(y)"),
 ("In the scope example, why can `print_var()` read global `x` without declaring it `global`?", "Reading a global name does not require assigning to it", ["Every function automatically copies all globals into locals", "The call passes `x` as an implicit parameter", "Python treats all single-letter names as global"], "The `global` declaration is needed to rebind a global name inside a function, not merely read it.", "Variable scope", 16, "distinguish reading and rebinding a global", "x = 5\ndef show():\n    print(x)\n\nshow()"),
 ("What effect does `global x` have before the function assigns `x = -60`?", "It makes that assignment rebind the module-level `x`", ["It creates a new local variable named `x`", "It makes every variable in the function global", "It passes the old value of `x` as a parameter"], "The declaration tells Python that assignment to `x` refers to the global name.", "Changing a global from inside", 17, "trace global rebinding", "x = 5\ndef change():\n    global x\n    x = -60\n\nchange()\nprint(x)"),
 ("What is recursion?", "A function calling itself", ["A function importing its own module", "A loop calling a function repeatedly", "A function returning without a value"], "Recursion is a function's ability to call itself.", "Recursion", 18, "define recursion", None),
 ("What stops the countdown recursion when it reaches zero?", "The condition `n > 0` becomes false, so no further call is made", ["The `print` statement returns zero", "Python resets `n` to its original value", "The function reaches a `break` statement"], "At n=0 the recursive condition fails, so that call returns without another call.", "Countdown", 18, "trace a recursive stopping condition", "def countdown(n):\n    print(n)\n    if n > 0:\n        countdown(n - 1)\n\ncountdown(2)"),
 ("What is the base-case result of `fact(n)` when `n <= 1`?", "1", ["0", "n", "The function calls `fact(n-1)` again"], "The base case returns 1 and ends the recursive chain.", "Factorial, recursively", 19, "identify a recursive base case", "def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)"),
 ('What does `fact(4)` return for this recursive definition?', "24", ["10", "16", "4"], "The calls reduce to 4*3*2*1, which is 24.", "Factorial, recursively", 19, "trace recursive factorial", "def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(4))"),
 ("What is a likely result of a recursive function whose calls never reach a base case?", "It continues calling until Python raises `RecursionError`", ["It automatically converts itself into a loop", "It returns `None` after one call", "It exits normally at the end of the module"], "Without a stopping case, recursive calls keep accumulating until the recursion limit is reached.", "Every recursion needs a base case", 19, "infer the role of a base case", None),
 ("Which benefit of functions means a caller can use a function without knowing its internal steps?", "Abstraction", ["Recursion", "Variable scope", "Package installation"], "Abstraction hides implementation details behind a usable interface.", "Why functions matter", 20, "identify abstraction", None),
 ('Which practice follows clean-code principles?', "Use focused functions with meaningful names that describe their purpose", ["Use short names such as `x` and `y` everywhere", "Add a comment that repeats every line of code", "Put unrelated tasks into one large function"], "The lesson recommends meaningful names, small focused functions, and useful comments.", "Clean code", 22, "apply clean-code principles", None),
 ("When is a code comment most useful?", "When it explains why a decision was made rather than restating the code", ["When it repeats an obvious assignment", "When it substitutes for meaningful function names", "When it describes every punctuation mark"], "Comments should add context; comments that merely restate code are noise.", "Clean code", 23, "evaluate a commenting choice", None),
 ('What is a Python module?', "A single `.py` file that can group definitions and statements for reuse", ["A folder containing only installed third-party packages", "A function that calls another function", "A variable that stores imported package versions"], "The lecture defines a module as a Python file containing reusable code definitions and statements.", "Modules", 24, "define a module", None),
 ("After `import Module_test`, how does the example call `generate_full_name` from that module?", "`Module_test.generate_full_name(...)`", ["`generate_full_name.Module_test(...)`", "`import.generate_full_name(...)`", "`Module_test::generate_full_name(...)`"], "A normal module import makes its names accessible through the module name and dot notation.", "Import functions from a user-defined module", 24, "apply module-qualified access", "import Module_test\nprint(Module_test.generate_full_name('Mona', 'Ahmed'))"),
 ("What does `from Module_test import generate_full_name as fullname` do?", "Imports that name and binds it locally as `fullname`", ["Renames the module file on disk", "Creates a new function with different behavior", "Imports every name from the module under `fullname`"], "The `as` clause gives the imported name a local alias.", "Importing and renaming", 26, "interpret an import alias", None),
 ("Which import pattern lets code call `sqrt` as `math.sqrt(2)`?", "`import math`", ["`from math import sqrt as math`", "`import math.sqrt as 2`", "`from math import * as sqrt`"], "Importing the module name allows access to its member through dot notation.", "Import built-in modules", 28, "select a module import form", "import math\nprint(math.sqrt(2))"),
 ('A program imports `random` and `randint` directly, then calls `random.choice(items)`. Which edit gives a valid random-choice call?', "Import `choice` and call `choice(items)`", ["Import `randint` and call `randint(items)`", "Import `random` and call `random(items)`", "Import `choice` and call `random.choice(items)`"], "The shown import binds `random` to the function, not the module; importing `choice` and calling it directly is valid.", "Random numbers", 29, "repair an import and member call", None),
 ("What range of values can `randint(5, 20)` return?", "An integer from 5 through 20, including both endpoints", ["An integer from 5 through 19", "A decimal from 5 up to but not including 20", "Only 5 or 20"], "The lesson describes randint endpoints as inclusive.", "Random numbers", 29, "interpret randint bounds", "from random import randint\nprint(randint(5, 20))"),
 ('Which statement best describes a Python package?', "A folder that groups related modules", ["A single function stored in a variable", "A built-in function that installs modules", "A list of all functions in the standard library"], "The lesson describes a package as a folder of related modules.", "Packages", 31, "define a package", None),
 ('Which alias is conventionally used for `matplotlib.pyplot`?', "`plt`", ["`mp`", "`sns`", "`pd`"], "The conventional import shown is `import matplotlib.pyplot as plt`.", "Packages", 32, "recognize a package alias", "import matplotlib.pyplot as plt"),
 ('Which package family includes pandas, NumPy, and SymPy for data preparation and numerical analysis?', "Operational packages for loading, structuring, and preparing data", ["Data-visualization packages for plotting", "Machine-learning packages for predictive models", "Operating-system packages for file management"], "The table places pandas, NumPy, and SymPy under operational packages.", "Package categories", 34, "classify packages by purpose", None),
 ('What does software deprecation mean?', "A feature is outdated or scheduled to be removed, so code may need updating", ["A function has completed its return statement", "A package has been installed successfully", "A module has been renamed with an alias"], "Deprecation refers to features becoming outdated and potentially removed in future versions.", "Code deprecation", 35, "interpret deprecation", None),
 ("In the reusable `growth_model`, why can the same function handle population growth, inflation, interest, and depreciation?", "The function's logic is reused with different labels, starting values, rates, and period counts", ["Each call changes the function definition itself", "All four examples use the same numerical rate", "The function ignores its arguments and reads global values"], "One proportional-update loop serves different cases by changing its arguments.", "Putting it together: growth_model", 40, "explain parameterized reuse", "def growth_model(label, start_value=10000, growth_rate=0.05, n=5):\n    year = 1\n    value = start_value\n    while year <= n:\n        value += value * growth_rate\n        year += 1\n    return value"),
 ("In `analyze_list(data_list, word1, word2)`, what happens when the two counts are equal?", "The function reports that the counts are equal", ["It reports `word1` as the majority", "It reports `word2` as the majority", "It divides by zero"], "The example has an explicit tie branch after comparing the two counts.", "Sheet 3, Exercise 9", 37, "trace a tie condition", "if count1 > count2:\n    print('word1 wins')\nelif count2 > count1:\n    print('word2 wins')\nelse:\n    print('The counts are equal')"),
 ("For 1,000 invested at a 5% annual rate for 2 years, what amount does the simple-interest formula `P + P*r*t` give?", "1,100", ["1,102.50", "1,050", "1,025"], "Simple interest is 1000 + 1000*0.05*2 = 1100.", "Sheet 3, Exercise 10", 41, "calculate simple interest", None),
 ("For the same 1,000 principal, 5% annual rate, and 2 years, what is the compound amount using `P*(1+r)^t`, rounded to two decimals?", "1,102.50", ["1,100.00", "1,105.00", "1,050.00"], "Compound growth gives 1000*(1.05)^2 = 1102.50.", "Sheet 3, Exercise 10", 41, "calculate compound interest", None),
 ('The code assigns the principal input to `P` but later calls `Deposite_simple_interest(p, r, t)`. Why does that name reference fail?', "Python is case-sensitive, so lowercase `p` is not the assigned uppercase `P`", ["Imported module names must be lowercase", "Function parameters cannot be passed from variables", "Python converts lowercase variable names to strings"], "Python distinguishes uppercase and lowercase identifiers; the shown local name is P.", "Sheet 3, Exercise 10 answer", 43, "spot a case-sensitive name mismatch", "P = int(input('Principal investment: '))\nr = float(input('Annual interest rate (0-1): '))\nt = int(input('Time in years: '))\ninterest_growth.Deposite_simple_interest(p, r, t)"),
 ("Which is the best reason to put related functions in a module and import them into a main program?", "It organizes reusable definitions so other files can use them", ["It makes every function run automatically on import without any call", "It converts functions into built-in functions", "It prevents the module from using parameters"], "Modules group code for reuse across programs; importing does not mean every function call in the module is automatically executed as an API operation.", "Modules", 24, "explain modular organization", None),
]

essays = [
 {"prompt":"Trace the two calls and explain the distinction between displayed output and returned values. State what is printed by `shows(5)` and `gives(5)`, and what values are assigned to `a` and `b`.\n\n```python\ndef shows(x):\n    print(x * 2)\n\ndef gives(x):\n    return x * 2\n\na = shows(5)\nb = gives(5)\n```", "expectedAnswer":"Calling shows(5) prints 10 and assigns None to a because it has no return. Calling gives(5) displays nothing and assigns 10 to b because it returns the value.", "rubric":["States shows prints 10","States a is None","States gives prints nothing during the call","States b is 10","Explains print displays while return passes a value to the caller"], "source":"Markdown: print is not return; PDF p. 6", "operation":"trace and explain output versus returned values", "code":"def shows(x):\n    print(x * 2)\n\ndef gives(x):\n    return x * 2\n\na = shows(5)\nb = gives(5)"},
 {"prompt":"Write a function `mean_of(values)` that returns the arithmetic mean of a non-empty list. Trace its result for `[10, 20, 30, 40, 50]`, and explain the role of the accumulator and `len(values)`. State one issue the function should consider for an empty list.", "expectedAnswer":"Initialize a total to zero, add each item in a loop, then return total/len(values). For the five values, the sum is 150 and the mean is 30. An empty list has length zero, so division by zero must be handled or excluded by a precondition.", "rubric":["Initializes an accumulator","Loops through and adds every value","Returns total divided by the list length","Calculates 30 for the supplied list","Identifies empty-list division by zero and a suitable guard or precondition"], "source":"Markdown: Average of a whole list; PDF p. 9", "operation":"design and analyze a list-processing function"},
 {"prompt":"Explain how the loan-payment function handles zero annual interest. Then calculate the interest-free monthly payment for a principal of 12,000 repaid over 4 years, and explain why the guard must occur before the general formula.", "expectedAnswer":"There are 48 months, so the zero-interest payment is 12000/48=250 per month. The guard returns this equal repayment before evaluating the interest formula, whose denominator R-1 becomes zero when the rate is zero.", "rubric":["Converts 4 years to 48 months","Calculates 250 per month","Explains the zero-rate case is handled separately","Explains R becomes 1 and R-1 becomes zero","States the guard prevents division by zero"], "source":"Markdown: Monthly loan payment; PDF p. 11", "operation":"explain and calculate a guarded formula"},
 {"prompt":"Compare positional arguments, default parameters, keyword arguments, and `*args`. Use `generate_full_name(first_name='Arwa', last_name='Mohammed')` to show what `generate_full_name(last_name='Saber')` returns, then explain what `*nums` receives in `sum_all_nums(2, 3, 5)`.", "expectedAnswer":"Positional values are matched by order; defaults are used when values are omitted; keyword arguments name a parameter and can override one default. The call returns Arwa Saber. A `*nums` parameter gathers the extra positional values into a tuple (2,3,5).", "rubric":["Explains positional matching by order","Explains omitted parameters use defaults","Explains a keyword argument selects/overrides the named parameter","Gives Arwa Saber","Explains *nums collects variable positional arguments"], "source":"Markdown: Different ways to pass parameters; PDF pp. 13–14", "operation":"compare parameter-passing techniques"},
 {"prompt":'Trace `get_power(square_number(5), 3)`. Show the value produced by each call and clarify whether `get_power` receives the function object `square_number` or the result of calling it.', "expectedAnswer":"square_number(5) returns 25. That expression is evaluated before get_power is called, so get_power receives 25 and 3. It returns pow(25,3)=15625; it does not receive the function object itself.", "rubric":["Calculates square_number(5) as 25","Explains argument expression is evaluated before get_power runs","States get_power receives values 25 and 3, not a function object","Calculates 25 cubed","Gives 15625"], "source":"PDF p. 15; function argument evaluation", "operation":"trace nested calls and argument evaluation", "code":"def square_number(n):\n    return n * n\n\ndef get_power(f, x):\n    return pow(f, x)\n\nresult = get_power(square_number(5), 3)"},
 {"prompt":"For the scope example, identify which variables are local and global. Explain why a function can read a global `x` without `global`, why `y` is unavailable outside the function, and what changes when the function declares `global x` and assigns `x = -60`.", "expectedAnswer":"A name created in the main program is global; y assigned inside the function is local and cannot be read outside. Reading global x is allowed without a declaration. The global statement is needed to rebind x; assigning -60 then changes the module-level x.", "rubric":["Identifies main-program x and y as global in the examples","Identifies function-local y as unavailable outside","Explains reading a global does not require global declaration","Explains global x enables rebinding the global name","States the later global x value is -60"], "source":"Markdown: Variable scope; PDF pp. 16–17", "operation":"analyze local and global scope"},
 {"prompt":"Trace the recursive factorial function for `fact(4)`. Show the sequence of calls down to the base case and the values returned while the calls unwind. Explain what role the base case plays.", "expectedAnswer":"fact(4)=4*fact(3); fact(3)=3*fact(2); fact(2)=2*fact(1); fact(1) returns 1. Unwinding gives 2, then 6, then 24. The base case stops further recursive calls.", "rubric":["Shows calls descend from fact(4) through fact(1)","Identifies fact(1) returns 1","Correctly traces an intermediate return such as 2 or 6","Gives final result 24","Explains the base case terminates recursion"], "source":"Markdown: Factorial, recursively; PDF p. 19", "operation":"trace recursive calls and returns", "code":"def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(4))"},
 {"prompt":'Write a Python module with simple- and compound-interest functions, then import it into a main program. Describe how a module supports reuse, distinguish `import interest_growth` from importing a function directly, and correct the variable-name case error in the call (`P` is assigned from input but `p` is passed).', "expectedAnswer":"A module is a .py file that groups reusable definitions. With `import interest_growth`, call a member as `interest_growth.function_name(...)`; a direct import such as `from interest_growth import growth_model` lets code call `growth_model(...)`. Python is case-sensitive, so the call should pass uppercase P, or the assignment should consistently use lowercase p.", "rubric":["Defines a module as a reusable Python file of related definitions","Gives module-qualified call form for normal import","Distinguishes direct import and unqualified call","Identifies P/p case mismatch","Provides a consistent correction"], "source":"PDF pp. 24–26 and 41–43; module exercise", "operation":"explain module reuse and diagnose an import example"},
]

for i, row in enumerate(essays, 1):
    row.update({"id":f"M2L4-E{i:02d}", "responseType":"structured response", "marks":5,
                "rubric":[{"criterion":c,"points":1} for c in row["rubric"]]})
essay_code={
 "M2L4-E01":"def shows(x):\n    print(x * 2)\n\ndef gives(x):\n    return x * 2\n\na = shows(5)\nb = gives(5)",
 "M2L4-E05":"def square_number(n):\n    return n * n\n\ndef get_power(f, x):\n    return pow(f, x)\n\nresult = get_power(square_number(5), 3)",
 "M2L4-E07":"def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(4))",
}
essay_justifications=[
 "A print-only function displays its result but implicitly returns None; a return-based function supplies a value to the caller, so the two assignments differ.",
 "A list mean is the accumulated sum divided by the number of values; for a non-empty list of five scores this is 150/5=30, while an empty list would divide by zero.",
 "At zero interest, the loan is divided evenly across 48 months, giving 250 per month; the guard avoids evaluating the general formula's zero denominator.",
 "Positional values match parameters by order, defaults fill omitted values, keyword arguments identify parameters directly, and *args gathers extra positional inputs into a tuple.",
 "Python evaluates function-call arguments before entering the outer call: square_number(5) yields 25, so get_power computes 25 cubed, or 15,625.",
 "A function-local assignment stays within that function; reading a global is allowed, while rebinding the global requires a global declaration.",
 "Each recursive call reduces n until fact(1) reaches the base case and returns 1; the pending multiplications then unwind to 4*3*2*1=24.",
 "A module groups reusable definitions; qualified and direct imports provide different access forms, and Python's case-sensitive names make P and p distinct identifiers.",
]
for row in essays:
    row["justification"]=essay_justifications[int(row["id"][-2:])-1]
    if row["id"] in essay_code:
        row["stimulusCode"]=essay_code[row["id"]]

items=[]
excluded_questions={
    "What is the role of `def` in a Python function definition?",
    "Why can the result of `gives(5)` be used in `b + 1`?",
    'In `get_power(f, x)`, what value is passed as `f` by `get_power(square_number(5), 3)?',
    "What is the base-case result of `fact(n)` when `n <= 1`?",
    "Which benefit of functions means a caller can use a function without knowing its internal steps?",
    "When is a code comment most useful?",
    "What does `get_power(square_number(5), 3)` calculate?",
    "What range of values can `randint(5, 20)` return?",
}
option_rewrites={
"Which statement best distinguishes a built-in function from a user-defined function?":("Python supplies built-ins; programmers define user functions for a particular task",["A built-in always returns a value; a user-defined function always prints","A built-in must be imported from a module; a user-defined function cannot be imported","A built-in accepts no arguments; a user-defined function must accept arguments"]),
"What happens when Python executes a function definition that has not been called?":("The name is bound; the function body waits for a call",["Python runs the body once and then stores its return value","Python prints the docstring and waits for input","Python runs the body only if it contains a return statement"]),
"In `def add(a, b):`, what are `a` and `b`?":("Formal parameter names",["The returned values produced by a call","The function calls","The module aliases"]),
"What is the key difference between `print` and `return` inside a function?":("`print` displays; `return` sends a value to its caller",["`print` hands a value back; `return` displays it","Both show output, but only `return` can pass a value back","`return` defines the function, while `print` calls it"]),
"In `my_avg_list(L)`, why does the function initialize `s = 0` before its loop?":("Give the running sum a zero starting value",["It sets the list length to zero","It makes the function return zero after the loop","It prevents the loop from visiting the first item"]),
"What does the guard clause in `loan_payment` do when `annual_rate == 0`?":("It handles zero interest before the general payment formula runs",["It raises an error to prevent an interest-free loan","It skips all payment calculations and returns the principal amount only","It changes the annual rate to 100 percent"]),
"In the loan function, how is an annual rate given as a percentage converted to a monthly decimal rate?":("Divide the annual percentage by `100 * 12`",["Multiply the annual percentage rate by `100 * 12`","Divide by 12 and then add 100","Subtract 12 and divide by 100"]),
"A function receives three scores, calculates their mean, and divides the sum of squared deviations by 3. Which variance convention is it using?":("Population variance, dividing squared deviations by n",["Sample variance using n minus one after squaring deviations","Standard deviation, taking a square root","Range, subtracting the minimum from the maximum"]),
"What does the `*nums` parameter collect in `sum_all_nums(*nums)`?":("Extra positional values, collected as a tuple",["All keyword arguments as a dictionary","The function's return values as a list","A required list object passed as the only argument"]),
"A function-local variable `y` is assigned inside `print_var`. What happens if the main program tries to use that local `y` after the call?":("`NameError`; the local name is outside its scope",["It reads the value from the most recent call","It automatically becomes a global variable","It is available only until the next function definition"]),
"What effect does `global x` have before the function assigns `x = -60`?":("It makes that assignment rebind the module-level `x`",["It creates a new local variable named `x`","It makes every variable in the function global","It passes the old value of `x` as an extra function parameter"]),
"What is recursion?":("A function calling itself during execution",["A function importing its own module","A loop repeatedly calling a function until a condition is met","A function returning without a value"]),
"What stops the countdown recursion when it reaches zero?":("At zero, the condition fails and recursion stops",["Python uses `break` to exit the recursive function","The `print` statement returns zero","Python resets `n` to its original value"]),
"What is a likely result of a recursive function whose calls never reach a base case?":("Python eventually raises `RecursionError`",["It automatically converts itself into a loop","It returns `None` after one call","It exits normally at the end of the module"]),
'Which practice follows clean-code principles?':("Use focused functions with meaningful, descriptive names",["Use short names such as `x` and `y` everywhere","Add a comment that repeats every line of code","Group the whole program in one function with short generic names"]),
'What is a Python module?':("A `.py` file grouping related definitions",["A folder containing only installed third-party packages","A function that calls another function","A variable that stores imported package versions"]),
"What does `from Module_test import generate_full_name as fullname` do?":("Imports the name locally as `fullname`",["Renames the module file on disk","Creates a new function with different behavior","Imports every module name locally under the alias `fullname`"]),
"Which import pattern lets code call `sqrt` as `math.sqrt(2)`?":("Import the `math` module",["`from math import sqrt as math`","`import math.sqrt as 2`","`from math import * as sqrt`"]),
'Which statement best describes a Python package?':("A folder grouping related modules together",["A single function stored in a variable","A built-in function that installs modules","A list of all functions in the standard library"]),
'Which package family includes pandas, NumPy, and SymPy for data preparation and numerical analysis?':("Operational packages prepare data for analysis",["Data-visualization packages for plotting","Machine-learning packages for predictive models","Operating-system packages for file management"]),
'What does software deprecation mean?':("A feature becomes outdated and may be removed later",["A function has completed its return statement","A package has been installed successfully","An imported module member is renamed to fit a new alias"]),
"In the reusable `growth_model`, why can the same function handle population growth, inflation, interest, and depreciation?":("One growth function is reused with changed arguments",["Each call changes the function definition itself","All four examples use the same numerical rate","The function ignores its arguments and reads global values"]),
"In `analyze_list(data_list, word1, word2)`, what happens when the two counts are equal?":("It reports a tie",["It reports `word1` as the majority","It reports `word2` as the majority","It errors"]),
'The code assigns the principal input to `P` but later calls `Deposite_simple_interest(p, r, t)`. Why does that name reference fail?':("Uppercase `P` differs from lowercase `p`",["Imported module names must be lowercase","Function parameters cannot be passed from variables","Python converts lowercase variable names to strings"]),
}
for q,key,distr,why,md,pdf,op,code in raw:
    if q in excluded_questions:
        continue
    if q in option_rewrites:
        key,distr=option_rewrites[q]
    i=len(items)+1
    opts=[key]+distr
    target=(i-1)%4
    shift=(-target)%4
    opts=opts[shift:]+opts[:shift]
    row={"id":f"M2L4-{i:03d}","question":q,"options":opts,"correctIndex":opts.index(key),
         "expectedAnswer":key,"explanation":why,"source":f"4_funcitons_and_modules.md — {md}; Lecture 2_3 PDF p. {pdf}",
         "objective":"functions and modules","operation":op}
    if code: row["stimulusCode"]=code
    items.append(row)

import sys
sys.path.insert(0, str(ROOT.parent))
from explanation_overrides import apply_overrides
apply_overrides(ROOT.name, items)
(ROOT/"final_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in items)+"\n")
(ROOT/"essay_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in essays)+"\n")
print(f"created {len(items)} MCQs and {len(essays)} structured responses")
