import json
from pathlib import Path

ROOT=Path(__file__).parent

# question, key, distractors, explanation, Markdown locator, PDF page, operation, code
raw=[
 ("Which property makes a Python list useful when a program needs to update its collection after creating it?","A list is ordered and mutable",["A list is unordered and immutable","A list stores only values of one type","A list can be accessed only by keys"],"Lists preserve order and allow items to be changed, added, or removed.","Creating and indexing a list",4,"identify list properties",None),
 ("What is the value of `len([1, 1.0, 'one', False])`?","4",["3","2","1"],"A mixed-type list still has four items.","Creating lists",4,"count list elements","x = [1, 1.0, 'one', False]\nprint(len(x))"),
 ("For `x = [0, 10, 20, 30, 40, 50]`, what does `x[-1]` return?","50",["0","40","An IndexError"],"Negative index -1 refers to the final list element.","Accessing items by index",7,"trace negative indexing","x = [0, 10, 20, 30, 40, 50]\nprint(x[-1])"),
 ("In a list with n items, what is the index of its final item?","n - 1",["n","n + 1","1"],"With zero-based indexing, n items occupy indices 0 through n-1.","Creating and indexing a list",4,"infer final list index",None),
 ("What does `y[1][2]` access when `y = [[10, 20, 30], [40, 50, 60]]`?","60",["30","50","The second inner list"],"The first index selects the second inner list, and the second selects its third item.","Slicing a list of lists",7,"index a nested list","y = [[10, 20, 30], [40, 50, 60]]\nprint(y[1][2])"),
 ("What is the result of `nums[1:4]` for `nums = [10, 20, 30, 40, 50, 60]`?","[20, 30, 40]",["[10, 20, 30, 40]","[20, 30, 40, 50]","[10, 20, 30]"],"The slice includes index 1 and stops before index 4.","Slicing",5,"trace a slice","nums = [10, 20, 30, 40, 50, 60]\nprint(nums[1:4])"),
 ("What does `nums[:3]` select?","The first three items",["Items at indices 1, 2, and 3","The final three items","Every third item"],"An omitted start defaults to the beginning, and stop 3 is excluded.","Slicing",5,"interpret omitted slice start",None),
 ("Which slice returns the final three items of a list?","`nums[-3:]`",["`nums[:-3]`","`nums[3:]`","`nums[-3:-1]`"],"The start at -3 counts from the end; an omitted stop includes the rest.","Slicing with negative indices",6,"select a suffix slice",None),
 ("What does `nums[::-1]` produce?","A reversed copy of the list",["The original list sorted descending","A list containing every second item","An empty list"],"A negative step traverses from the end toward the beginning.","Slicing with negative indices",6,"interpret a negative slice step",None),
 ("After `x = y` for a list, what happens if the program appends an item to `x`?","The same item also appears when `y` is viewed",["`y` stays unchanged because assignment copied it","Python raises an aliasing error","Only the first element of `y` changes"],"Assignment binds a second name to the same list object; it does not copy the list.","The copy trap",11,"reason about list aliasing","y = [0, 10, 20]\nx = y\nx.append(30)\nprint(y)"),
 ("Which operation makes a separate shallow copy of a list `y`?","`x = y.copy()`",["`x = y`","`x = y.append([])`","`x = len(y)`"],"The copy method returns another list, so appending to x does not add to y.","The fix — .copy()",11,"choose a list copy operation",None),
 ("What is the main difference between `append(w)` and `extend(w)` when `w` has three items?","append adds w as one item; extend adds its three items individually",["append adds three items; extend adds w as one nested item","Both add w as one item","append sorts w; extend reverses it"],"append adds exactly one object, while extend iterates through the supplied sequence.","append vs extend vs +",13,"compare list growth methods","x = [1, 2]\nw = ['a', 'b', 'c']\na = x.copy(); a.append(w)\nb = x.copy(); b.extend(w)\nprint(len(a), len(b))"),
 ("For `x = [1, 2]`, what is `len(x)` after `x.append([3, 4, 5])`?","3",["5","4","2"],"The appended list is one new element, even though that element contains three values.","append vs extend vs +",12,"count after appending a list","x = [1, 2]\nx.append([3, 4, 5])\nprint(len(x))"),
 ("Which list operation removes and returns the item at a specified index?","`pop(i)`",["`remove(x)`","`clear()`","`sort()`"],"pop removes an item by index and returns that removed value.","Removing items",14,"identify a removing method",None),
 ("What does `x.remove(20)` remove from a list?","The first item whose value equals 20",["The item at index 20","Every item equal to 20","The final item in the list"],"remove takes a value and deletes its first matching occurrence.","Removing items",14,"distinguish removal by value",None),
 ("What does `x.clear()` do?","Removes all items from x",["Removes only the first item","Returns a sorted copy of x","Deletes the variable name x"],"clear empties the list while leaving the variable bound to that empty list.","Removing items",14,"interpret clear()",None),
 ("What is the result of `y.count(4)` for `y = [1, 4, 4, 5, 4]`?","3",["2","4","1"],"count returns the number of equal occurrences of the specified value.","count, reverse, sort, and in",15,"count repeated values","y = [1, 4, 4, 5, 4]\nprint(y.count(4))"),
 ("How does `y.reverse()` differ from `y.sort(reverse=True)`?","reverse changes the current order; sort orders values from largest to smallest",["reverse sorts alphabetically; sort changes the current order","Both sort values from largest to smallest","reverse returns a new list; sort leaves y unchanged"],"reverse flips the existing sequence order; descending sort compares the values.","count, reverse, sort, and in",15,"distinguish reversing from descending sort",None),
 ("What does `sorted(x)` do to the original list `x`?","Returns a sorted copy of x without changing the original",["Sorts x in place and returns None","Deletes duplicate items from x","Returns x in reverse insertion order"],"sorted is a built-in that produces a new list, leaving the original order intact.","Methods versus built-in functions",16,"compare sorted() with sort()","x = [35, 20, 30, 15]\ny = sorted(x)\nprint(y, x)"),
 ("What is the result of calling `x.sort()` on a list?","It sorts x in place and returns no sorted-list value",["It returns a new sorted list and leaves x unchanged","It sorts x and returns the first item","It converts x into a tuple"],"sort is a list method that modifies the list itself; use sorted when a new list is wanted.","Methods versus built-in functions",16,"interpret in-place sorting",None),
 ("In `max(words, key=len)`, what does `key=len` tell Python?","Compare words using their lengths",["Return the length of every word","Sort alphabetically and then choose the final word","Ignore words whose length is repeated"],"The key function supplies the value used for comparison, here each word's length.","Six ways to find the longest word",26,"interpret a key function","words = ['oak', 'pear', 'watermelon']\nprint(max(words, key=len))"),
 ("Why does the GDP-growth loop start at index 1?","Each growth rate compares a value with the previous one, which index 0 does not have",["Index 0 is reserved for a list's length","The first GDP value is always zero","Starting at 1 reverses the list"],"The first observation has no prior observation; N values therefore yield N-1 changes.","GDP growth rates",19,"explain a loop start index",None),
 ("For GDP values `[2.1, 2.3, 2.6, 2.9]`, approximately what is the first growth rate?","9.52%",["0.20%","8.70%","13.04%"],"(2.3-2.1)/2.1×100 is approximately 9.52%.","GDP growth rates",19,"calculate a percentage change",None),
 ("What is the median of `[2500, 3200, 4000, 2800, 5000]`?","3200",["3500","4000","2800"],"After sorting, the middle of five values is 3200.","Median income",17,"calculate an odd-length median","incomes = [2500, 3200, 4000, 2800, 5000]\nprint(sorted(incomes))"),
 ("A median function receives four values. After sorting, how should it calculate the median?","Compute the average of the two central values",["Return the smaller of the two middle values instead","Average the first and last values","Divide the sum of all four values by four"],"For an even-length list there is no single middle element, so average the two central values.","Median income",17,"explain an even-length median",None),
 ("What does the list comprehension `[i for i in range(21) if i % 2 == 0]` contain?","The even integers from 0 through 20",["The odd integers from 0 through 19","The integers from 0 through 21","Only the value 2"],"The range includes 0 to 20; the filter keeps values with remainder zero when divided by 2.","List comprehension",21,"interpret a filtered comprehension","print([i for i in range(21) if i % 2 == 0])"),
 ("Which part of `[i for i in numbers if i % 2 == 0 and i > 0]` filters out negative even numbers?","The condition `i > 0`",["The expression `i`","The condition `i % 2 == 0`","The sequence `numbers`"],"The parity test keeps even values; the additional positive test excludes zero and negatives.","List comprehension",21,"interpret a compound comprehension filter",None),
 ("What does `txt_news.upper()` return?","A new string with lowercase letters converted to uppercase",["The original string with punctuation removed","A list of uppercase words","The number of uppercase letters"],"upper returns a case-converted string; strings are not modified in place.","String methods",22,"interpret upper()",None),
 ("What does `txt_news.split()` do when no separator is supplied?","Splits the string at whitespace into a list of words",["Splits at every character into separate strings","Splits only at commas","Returns the number of words"],"The no-argument split separates on runs of whitespace and returns a list.","String methods on a news headline",23,"interpret split()",None),
 ("What does `txt_news.find('Palestine')` return when the text does not contain that substring?","-1",["0","None","An empty list"],"find returns -1 when the target is not found.","Searching inside a string",24,"interpret a failed find()",None),
 ("In the headline example, if 'Gaza' appears once among 11 split words, what is its word density rounded to two decimals?","9.09%",["0.09%","11.00%","1.10%"],"The calculation is 1/11×100≈9.09%.","Searching inside a string",24,"calculate word density",None),
 ("What does `' '.join(['Dina', 'Khaled'])` produce?","`Dina Khaled`",["`DinaKhaled`","`['Dina', 'Khaled']`","`Dina, Khaled`"],"join places the separator string between each item and returns one string.","String methods",22,"interpret join()",None),
 ("What does `strip()` remove from a string by default?","Whitespace at the beginning and end",["Every space between words","All punctuation marks","The first and last character regardless of type"],"strip removes surrounding whitespace; it does not remove internal spaces.","String methods",22,"interpret strip()",None),
 ("What does `isdigit()` test?","Whether all characters in the string are digits",["Whether the string contains at least one digit","Whether the string can be converted to a list","Whether the string contains a decimal point"],"The method returns True when the string's characters are all digits.","String methods",22,"interpret isdigit()",None),
 ("What does `find('@')` return for an email string with no at sign?","-1",["0","The string length","None"],"The email-provider example uses -1 to identify addresses without an @ sign.","Extract email providers",29,"trace a string search",None),
 ("Why does `email_provider` check whether a domain is already in `domains` before appending it?","To avoid duplicate provider domains in the result",["To alphabetize all domains before returning them","To remove email addresses from repeat providers","To check whether each domain contains an `@`"],"The membership check prevents a provider repeated in several addresses from appearing more than once.","Extract email providers",29,"explain de-duplication",None),
 ("What does the `sorted(domains)` return in the email-provider function?","A new list of unique domains in sorted order",["The original email list in reverse order","A set of domain names","The number of domains"],"Duplicates are prevented during collection, and sorted returns those domains in order.","Extract email providers",29,"trace a domain-processing function",None),
 ("For sorted incomes `[500, 1000, 1500, 2000, 3000]`, the lesson's Gini calculation returns approximately what value?","0.30",["0.03","0.50","0.70"],"The rank-weighted numerator is 12000 and n×total is 40000, giving 0.30.","Gini coefficient",33,"calculate the example Gini index",None),
 ("Under the PDF's interpretation bands, how is a Gini index of exactly 0.30 classified?","Low inequality",["Moderate inequality","High inequality","Invalid Gini Index"],"The low band includes 0.30; the moderate band begins above 0.30.","Gini coefficient",32,"interpret a boundary value",None),
 ("Why does the Gini function sort its data before applying the rank-weighted sum?","The formula's weights depend on each income's position in ascending order",["Sorting removes duplicate incomes","The function can calculate the sum only after sorting","The rank formula requires descending order"],"The simplified formula assigns a rank coefficient to each income in sorted order.","Gini coefficient",33,"explain sorting before rank weighting",None),
 ("Which comprehension builds the same full-name list as looping through `[ ['Ahmed','Ali'], ['Dina','Khaled'] ]` and appending first plus last name?","`[s[0] + ' ' + s[1] for s in students]`",["`[students[0] + students[1]]`","`[s[1] + ' ' + s[0] for s in students]`","`[s for s in students if s[0]]`"],"The expression combines each inner pair in order and produces one full-name string per student.","Lists of strings",31,"translate a loop into a comprehension",None),
 ("What does `len(growth_rates)` equal when `gdp_values` contains four yearly observations and the function starts at index 1?","3",["4","5","1"],"There is no growth rate for the first observation, so four values yield three consecutive changes.","GDP growth rates",19,"infer output length from adjacent comparisons",None),
 ("In the improved `analyze_list`, why are both the data items and `word1`/`word2` converted to lowercase?","So capitalization differences do not prevent equivalent labels from matching",["So the list can be sorted numerically","So count() ignores spaces automatically","So the words become immutable"],"Both sides of each equality comparison must be normalized to the same case.","Sheet 4, Exercise 11",36,"explain case normalization",None),
]

essays=[
 {"prompt":"For `nums = [10, 20, 30, 40, 50, 60, 70]`, give the results of `nums[1:4]`, `nums[-3:]`, and `nums[::-1]`. Explain the inclusive/exclusive slice boundary and what the negative step does.","expectedAnswer":"The results are [20,30,40], [50,60,70], and [70,60,50,40,30,20,10]. Slice start is included and stop excluded. A step of -1 traverses from the end to the start.","justification":"The slice rules include the start index, omit the stop index, and use a negative step to traverse backward; applying those rules gives the three stated sequences.","rubric":["Correctly evaluates nums[1:4]","Correctly evaluates nums[-3:]","Correctly evaluates nums[::-1]","Explains that the stop index is excluded","Explains the negative step reverses traversal"],"source":"5_lists_and_strings.md, Slicing; PDF pp. 5–7","operation":"trace slices and explain endpoint rules","code":"nums = [10, 20, 30, 40, 50, 60, 70]\nprint(nums[1:4])\nprint(nums[-3:])\nprint(nums[::-1])"},
 {"prompt":"Trace these operations and report both lists at the end. Explain why `x = y` behaves differently from `x = y.copy()`.\n\n```python\ny = [1, 2]\nx = y\nx.append(3)\n\na = [1, 2]\nb = a.copy()\nb.append(3)\n```","expectedAnswer":"After the first sequence, both x and y refer to [1,2,3]. After the second, a is [1,2] and b is [1,2,3]. Assignment creates another reference to the same list; copy() creates a separate list.","justification":"Mutating an aliased list is visible through every reference to that object, whereas appending to the independent copy leaves the original list unchanged.","rubric":["Gives x and y as [1,2,3]","Gives a as [1,2]","Gives b as [1,2,3]","Explains x=y creates an alias rather than a copy","Explains copy() creates a separate list"],"source":"5_lists_and_strings.md, The copy trap; PDF pp. 11–12","operation":"trace aliasing and copying","code":"y = [1, 2]\nx = y\nx.append(3)\n\na = [1, 2]\nb = a.copy()\nb.append(3)"},
 {"prompt":"Let `base = [0, 10]` and `extra = ['a', 'b', 'c']`. Give the resulting value and length for each: (a) a copy of base followed by `append(extra)`; (b) a copy of base followed by `extend(extra)`; (c) a copy of base concatenated with extra using `+`. Explain which operations add extra as one nested item and which add its elements.","expectedAnswer":"(a) [0,10,['a','b','c']], length 3. (b) and (c) [0,10,'a','b','c'], length 5. append adds the list as one object; extend and + add its individual items.","justification":"append contributes one element regardless of that element being a list; extend iterates over the supplied sequence, and concatenation creates a combined list containing each item.","rubric":["Gives append result as a nested list","Gives append result length 3","Gives extend and + results with the three strings as separate items","Gives extend and + lengths as 5","Explains the one-item versus individual-items distinction"],"source":"5_lists_and_strings.md, append vs extend vs +; PDF p. 13","operation":"compare append, extend, and concatenation","code":"base = [0, 10]\nextra = ['a', 'b', 'c']\na = base.copy(); a.append(extra)\nb = base.copy(); b.extend(extra)\nc = base + extra"},
 {"prompt":"Write or outline a `median_income` function that handles both odd and even non-empty lists. Find the median for `[2500, 3200, 4000, 2800, 5000]` and for `[1, 4, 8, 10]`. Explain why sorting is done first.","expectedAnswer":"Sort the values and set mid=n//2. For odd n, return sorted[mid]; for even n, return (sorted[mid]+sorted[mid-1])/2. The medians are 3200 and (4+8)/2=6. Sorting places values in order so the central position(s) identify the median.","justification":"The median is defined by the central ordered value(s): one center for odd-sized data and the average of two centers for even-sized data.","rubric":["Sorts or otherwise orders input values","Returns the center item for an odd-length list","Averages the two center items for even length","Calculates 3200 for the five values","Calculates 6 for the four values and explains why sorting matters"],"source":"5_lists_and_strings.md, Median income; PDF p. 17","operation":"design and apply an odd/even median function"},
 {"prompt":"Using GDP values `[2.1, 2.3, 2.6, 2.9]` trillion dollars, calculate each year-to-year growth rate to two decimal places. Explain why the loop begins at index 1 and why the output has one fewer value than the input.","expectedAnswer":"The rates are (2.3-2.1)/2.1×100=9.52%, (2.6-2.3)/2.3×100=13.04%, and (2.9-2.6)/2.6×100=11.54%. The first value has no previous year, so there are n-1 comparisons and results.","justification":"Each rate compares the current observation to its predecessor; the first observation cannot form such a pair, leaving three rates from four values.","rubric":["Uses the previous value as denominator","Calculates 9.52% for the first rate","Calculates 13.04% for the second rate","Calculates 11.54% for the third rate","Explains the index-1 start and n-1 output count"],"source":"5_lists_and_strings.md, GDP growth rates; PDF pp. 18–19","operation":"calculate adjacent growth rates and explain indexing"},
 {"prompt":"Use a list comprehension to create the positive even values from `[-8, -7, -3, -1, 0, 1, 3, 4, 5, 7, 6, 8, 10]`. Then explain the roles of the expression, iteration variable, source sequence, and both conditions.","expectedAnswer":"`[i for i in numbers if i % 2 == 0 and i > 0]` returns [4,6,8,10]. The expression i is included; i takes each value from numbers; the sequence is numbers; the conditions retain even and positive values.","justification":"The first condition filters for divisibility by two and the second excludes zero and negatives; the comprehension appends each remaining value to a new list.","rubric":["Provides a syntactically valid comprehension","Uses the given list as its source sequence","Filters for even values","Filters for values greater than zero","Gives [4,6,8,10] and identifies comprehension components"],"source":"5_lists_and_strings.md, List comprehension; PDF pp. 20–21","operation":"construct and explain a filtered comprehension"},
 {"prompt":"For `text = 'BBC: babies have died from cold in Gaza over two weeks'`, state `len(text)`, the number of words from `text.split()`, the result of `text.find('Palestine')`, and the percentage density of `Gaza` among the words to two decimals. Explain the relevant string operations.","expectedAnswer":"len(text)=54, split() gives 11 words, find('Palestine') returns -1, and Gaza density is 1/11×100=9.09%. len counts characters, split creates a word list on whitespace, find returns -1 when absent, and count supplies the occurrence count.","justification":"The string has 54 characters and 11 whitespace-separated words; Gaza occurs once, while Palestine is absent, so the stated count, failed search, and 9.09% density follow.","rubric":["Gives 54 characters","Gives 11 words","Gives -1 for the absent substring","Calculates 9.09% density","Explains len, split, find, and count roles"],"source":"5_lists_and_strings.md, String methods/searching; PDF pp. 22–24","operation":"trace string methods and calculate word density"},
 {"prompt":"Design or describe a function that takes a list of email strings and returns sorted unique provider domains. Explain how it should handle an item with no `@`, how it extracts the domain, and how it avoids duplicates. Show the result for `['a@gmail.com', 'b@yahoo.com', 'c@gmail.com', 'bad-address']`.","expectedAnswer":"For each email, find('@'); skip if the result is -1; otherwise split on '@' and take the text after it. Append the domain only if it is not already in the domain list, then return sorted(domains). The result is ['gmail.com','yahoo.com'].","justification":"Skipping strings without an at sign prevents invalid extraction, membership checking removes repeated providers, and sorting orders the unique domains for the returned list.","rubric":["Checks for a missing @ and skips that entry","Extracts the text after @","Avoids appending a domain already collected","Returns the domains sorted","Gives the expected two-domain result"],"source":"5_lists_and_strings.md, Extract email providers; PDF p. 29","operation":"design a string-processing and de-duplication function"},
]

for i,row in enumerate(essays,1):
 row.update({"id":f"M2L5-E{i:02d}","responseType":"structured response","marks":5,"rubric":[{"criterion":c,"points":1} for c in row["rubric"]]})
essay_code={
 "M2L5-E01":"nums = [10, 20, 30, 40, 50, 60, 70]\nprint(nums[1:4])\nprint(nums[-3:])\nprint(nums[::-1])",
 "M2L5-E02":"y = [1, 2]\nx = y\nx.append(3)\n\na = [1, 2]\nb = a.copy()\nb.append(3)",
 "M2L5-E03":"base = [0, 10]\nextra = ['a', 'b', 'c']\na = base.copy(); a.append(extra)\nb = base.copy(); b.extend(extra)\nc = base + extra",
 "M2L5-E06":"numbers = [-8, -7, -3, -1, 0, 1, 3, 4, 5, 7, 6, 8, 10]\n[i for i in numbers if i % 2 == 0 and i > 0]",
 "M2L5-E07":"text = 'BBC: babies have died from cold in Gaza over two weeks'\nwords = text.split()\nprint(len(text), len(words), text.find('Palestine'))\nprint(round(text.count('Gaza') / len(words) * 100, 2))",
}
for row in essays:
 row.pop("code",None)
 if row["id"] in essay_code:
  row["stimulusCode"]=essay_code[row["id"]]

items=[]
excluded_questions={
 "What is the value of `len([1, 1.0, 'one', False])`?",
 "In a list with n items, what is the index of its final item?",
 "What does `x.clear()` do?",
}
for q,key,distr,why,section,pdf,op,code in raw:
 if q in excluded_questions:
  continue
 i=len(items)+1
 opts=[key]+distr
 target=(i-1)%4; shift=(-target)%4
 opts=opts[shift:]+opts[:shift]
 row={"id":f"M2L5-{i:03d}","question":q,"options":opts,"correctIndex":opts.index(key),"expectedAnswer":key,"explanation":why,"source":f"5_lists_and_strings.md — {section}; Collection Data Types Part 1 PDF p. {pdf}","objective":"lists and strings","operation":op}
 if code: row["stimulusCode"]=code
 items.append(row)

# Rewrite options with conspicuous key-length cues while preserving the balanced key position.
balanced_options={
 "M2L5-001":["A list is unordered but mutable","A list is ordered but immutable","A list stores one data type"],
 "M2L5-010":["append adds w as one item; extend adds all the elements stored inside w","append adds each item; extend nests w as one object","append and extend both add the entire w as one item"],
 "M2L5-013":["The first item whose value is 20","The item at position 20 in the list of values","All items whose value is 20 in the list"],
 "M2L5-015":["reverse sorts values; sort flips their current order in y","reverse returns a new list; sort leaves y unchanged","reverse and sort both reorder y by comparing every value from largest to smallest"],
 "M2L5-016":["Sorts x in place and also returns a second sorted list as a separate object","Sorts x in place and returns its first item as a value","Removes duplicate values and returns a sorted copy of x"],
 "M2L5-017":["It sorts x and gives back its first item","It sorts x in place but returns the entire sorted list as a new value","It creates a sorted copy and keeps x unchanged"],
 "M2L5-019":["Each growth value compares GDP against the first observation instead of the immediately previous year","Index 1 starts the list in reverse order from its final value","Index 0 stores the number of items instead of an observation"],
 "M2L5-022":["Return the smaller of the two middle values instead","Average the first and last values","Divide the sum of all four values by four"],
 "M2L5-023":["All the integers from zero up through twenty-one","Only the even number two is included in the result","The even integers from 0 through 21"],
 "M2L5-025":["A new string with uppercase letters made lowercase after conversion","The original string with punctuation removed from it","A list containing each of the words in uppercase"],
 "M2L5-026":["Splits the string into a separate item for each character","Splits only at newline characters","Returns how many words the string contains in total"],
 "M2L5-031":["Whether the string has at least one digit","Whether the string can be converted into a list","Whether the string contains a decimal point"],
 "M2L5-033":["To alphabetize all domains before returning them","To remove email addresses from repeat providers","To check whether each email address contains an `@`"],
 "M2L5-034":["A list of addresses in their reversed order","The original domains list reordered in place","A set that contains the provider names only"],
 "M2L5-036":["Moderate range","High inequality","Invalid result"],
 "M2L5-037":["Each income's rank in ascending order determines its weight","Sorting first removes repeated income values from the data","The rank-weighted calculation can only be applied after all income values are sorted"],
 "M2L5-040":["So only the data items are converted before comparison","So numeric sorting works on every item in the text list","So count() automatically ignores any whitespace characters that occur inside labels"],
}
for row in items:
 if row["id"] in balanced_options:
  choices=[row["expectedAnswer"]]+balanced_options[row["id"]]
  target=(int(row["id"].rsplit("-",1)[1])-1)%4
  shift=(-target)%4
  row["options"]=choices[shift:]+choices[:shift]
  row["correctIndex"]=row["options"].index(row["expectedAnswer"])

import sys
sys.path.insert(0, str(ROOT.parent))
from explanation_overrides import apply_overrides
apply_overrides(ROOT.name, items)
(ROOT/"final_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in items)+"\n")
(ROOT/"essay_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in essays)+"\n")
print(f"created {len(items)} MCQs and {len(essays)} structured responses")
