import json
from pathlib import Path

ROOT = Path(__file__).parent

raw = [
 ('After `score = 8`, what does the name `score` represent?', "The variable name associated with the stored value 8", ["The operator that adds eight to a value", "A Python keyword that declares an integer", "A command that prints the value"], "The name score refers to the value assigned to it; Python does not require a separate type declaration.", "PDF p. 12; 1_variables_and_operators.md, Variables", "variables_and_types", "interpret a variable assignment", None),
 ('If a program assigns `X = 8` and later asks for `x`, what concept explains why these names differ?', "Python is case sensitive", ["Python converts every name to lowercase", "Uppercase names are reserved keywords", "A variable name must contain a digit"], "Uppercase X and lowercase x are different names in Python.", "PDF p. 12; 1_variables_and_operators.md, Python is case sensitive", "variables_and_types", "apply case sensitivity", "X = 8\nprint(x)"),
 ("Which assignment gives a variable a Boolean value?", "`active = True`", ["`active = 1.0`", "`active = 'True'`", "`active = 1`"], "True without quotation marks is a Boolean; quoted True is text, 1.0 is a float, and 1 is an integer.", "PDF p. 15; 1_variables_and_operators.md, built-in types", "variables_and_types", "classify a literal's type", "active = True"),
 ("What type does Python infer for `rate = 1.387668`?", "float", ["int", "bool", "str"], "A numeric value written with a decimal point is a float in the lesson's examples.", "PDF p. 15; 1_variables_and_operators.md, built-in types", "variables_and_types", "identify an inferred type", "rate = 1.387668"),
 ('Which variable name follows Python naming rules?', "`student_name2`", ["`2student`", "`student-name`", "`student name`"], "Names may contain letters, digits, and underscores, but cannot begin with a digit or contain a hyphen or space.", "PDF p. 13; 1_variables_and_operators.md, naming rules", "variables_and_types", "apply identifier rules", None),
 ('How does Python determine a variable’s type when a value is assigned?', "Python infers a variable's type from the value assigned to it", ["Every variable must be declared as int, float, bool, or str first", "A variable keeps one fixed type before any value is assigned", "Only strings and integers can be stored in variables"], "Python does not require explicit type declarations in these examples; it infers a type from the assigned value.", "PDF p. 15; 1_variables_and_operators.md, built-in types", "variables_and_types", "interpret dynamic type inference", None),
 ('What is the main purpose of an integrated development environment (IDE)?', "Tools that support writing, debugging, and testing code", ["A Python keyword that stores variables", "A file format that can only display program output", "A replacement for the Python interpreter"], "The lecture describes IDEs as coding tools with features such as completion, syntax highlighting, debugging, and variable exploration.", "PDF p. 8; 5. Module 2_1_Conditioning.pdf, Best Python IDEs", "development_tools", "identify an IDE's role", None),
 ("What happens if code evaluates `x = x + 1` before `x` has been assigned?", "Python cannot evaluate the right-hand side because `x` has no value yet", ["Python assumes x is zero and assigns 1", "Python creates x as a string", "Python treats the statement as a comment"], "The right-hand side is evaluated before assignment, so x must be initialized first.", "PDF p. 16; 1_variables_and_operators.md, Updating a variable", "variables_and_types", "explain initialization requirement", "x = x + 1"),
 ("After `x = 6`, what value does `x` hold after `x += 3`?", "9", ["3", "6", "18"], "The augmented assignment is equivalent to x = x + 3.", "PDF p. 17; 1_variables_and_operators.md, increment and decrement", "variables_and_types", "trace an augmented assignment", "x = 6\nx += 3"),
 ('For `a = 15` and `b = 4`, what does `a / b` evaluate to?', "3.75", ["3", "4", "3.0"], "Regular division produces 3.75; the lecture notes that / gives a float.", "PDF p. 20; 1_variables_and_operators.md, arithmetic operators", "arithmetic_operators", "calculate regular division", "a = 15\nb = 4\nprint(a / b)"),
 ("For `a = 17` and `b = 5`, what do `a // b` and `a % b` return, respectively?", "3 and 2", ["3.4 and 0", "2 and 3", "4 and 2"], "Floor division gives the whole quotient 3; modulus gives the remainder 2.", "1_variables_and_operators.md, Where // and % earn their keep; PDF p. 20", "arithmetic_operators", "use quotient and remainder", "a = 17\nb = 5\nprint(a // b, a % b)"),
 ("What is the value of `2 ** 3 ** 2` under Python's exponentiation associativity?", "512", ["64", "256", "36"], "Exponentiation associates right to left: 2 ** (3 ** 2) = 2 ** 9 = 512.", "PDF p. 21; 1_variables_and_operators.md, operator precedence", "arithmetic_operators", "apply right-associative exponentiation", "print(2 ** 3 ** 2)"),
 ("What is the value of `5 + 3 * 2`?", "11", ["16", "13", "10"], "Multiplication happens before addition, so 5 + (3 * 2) = 11.", "PDF p. 22; 1_variables_and_operators.md, precedence example 1", "precedence", "apply arithmetic precedence", "print(5 + 3 * 2)"),
 ("What is the value of `(6 + 2) * 3 ** 2`?", "72", ["30", "576", "64"], "Parentheses first give 8; the exponent gives 9; then 8 * 9 = 72.", "PDF p. 22; 1_variables_and_operators.md, precedence example 4", "precedence", "combine parentheses and exponentiation", "print((6 + 2) * 3 ** 2)"),
 ('Which task is especially suited to a Python notebook rather than a script?', "Exploring data and running code in sections with immediate output", ["Running a larger production project as a whole", "Integrating a program with other software as one script", "Debugging a complete program without separate cells"], "The slides describe notebooks as useful for exploration and immediate section-by-section output; scripts are presented as useful for larger projects and production.", "PDF p. 7; 5. Module 2_1_Conditioning.pdf, Types of Python Files", "development_tools", "select a suitable development format", None),
 ("A group has 17 students and forms groups of 5. Which pair gives the number of complete groups and students left over?", "3 complete groups and 2 students left over", ["3 complete groups and 0 left over", "2 complete groups and 7 left over", "4 complete groups and 3 left over"], "17 // 5 is 3 and 17 % 5 is 2.", "1_variables_and_operators.md, Where // and % earn their keep", "arithmetic_operators", "apply floor division and modulus", "print(17 // 5, 17 % 5)"),
 ("What kind of value does a comparison such as `temperature >= 38` return?", "A Boolean value: True or False", ["Always an integer", "Always a string", "The larger of the two operands"], "Comparison operators evaluate a condition and return a Boolean.", "PDF p. 23; 1_variables_and_operators.md, comparison operators", "comparison_and_logic", "identify a comparison result type", "temperature = 39\nprint(temperature >= 38)"),
 ("Which operator tests whether two values are equal in a Python condition?", "`==`", ["`=`", "`!=`", "`>=`"], "A double equals sign compares values; a single equals sign assigns a value.", "PDF p. 23; 1_variables_and_operators.md, = versus ==", "comparison_and_logic", "distinguish assignment from equality", "if score == 10:\n    print('exactly ten')"),
 ("Which expression is True when `x` is either 4 or 7?", "`x == 4 or x == 7`", ["`x == 4 and x == 7`", "`x != 4 and x != 7`", "`x > 4 and x < 7`"], "The `or` expression accepts either matching value; a single x cannot equal both 4 and 7.", "PDF p. 24; 1_variables_and_operators.md, logical operators", "comparison_and_logic", "construct an either-or condition", None),
 ('For Boolean values `A` and `B`, when is `A and B` true?', "Only when both A and B are True", ["Whenever at least one is True", "Only when both are False", "Whenever A is False"], "Logical and requires both Boolean operands to be True.", "PDF p. 25; 1_variables_and_operators.md, truth table", "comparison_and_logic", "interpret a truth table", None),
 ('What does the built-in `print()` function do?', "It displays the supplied text or value as program output", ["It assigns a value to a variable", "It reads text typed by the user", "It repeats a block until a condition changes"], "The first program uses print() to display the Hello, World! message; input() is used for reading user input.", "PDF pp. 10–11; 5. Module 2_1_Conditioning.pdf, A First Program", "development_tools", "identify the role of a built-in function", "print(\"Hello, World!\")"),
 ("In the expression `not A and B or C`, which grouping follows Python's logical precedence?", "`((not A) and B) or C`", ["`not (A and (B or C))`", "`not ((A and B) or C)`", "`not A and (B or C)`"], "`not` is evaluated before `and`, and `and` before `or`; the expression groups as ((not A) and B) or C.", "PDF pp. 25–26; 1_variables_and_operators.md, logical operators and precedence", "precedence", "interpret logical precedence", None),
 ('In a mixed expression with arithmetic, comparison, and logical operators, what is their evaluation order?', "Arithmetic, then comparison, then logical", ["Logical, then arithmetic, then comparison", "Comparison, then logical, then arithmetic", "The operators are evaluated strictly left to right"], "The lecture states arithmetic → comparison → logical.", "PDF p. 27; 1_variables_and_operators.md, precedence across operator families", "precedence", "recall cross-family precedence", None),
 ('How can parentheses help when a condition’s intended grouping may be unclear?', "Use parentheses to make the intended evaluation order clear", ["Rely on variable capitalization to set the order", "Replace every `and` with `or`", "Put the condition in a comment"], "Parentheses can clarify or change evaluation order and reduce ambiguity.", "PDF p. 26; 1_variables_and_operators.md, logical precedence", "precedence", "select a clarity practice", None),
 ("In the simple-interest example, if P=1000, R=10, and N=5, what is SI before adding it to the principal?", "500", ["50", "1500", "1050"], "SI = P * N * (R / 100) = 1000 * 5 * 0.10 = 500.", "PDF p. 29; 1_variables_and_operators.md, Putting it together", "integrated_program", "calculate simple interest", "P = 1000\nR = 10\nN = 5\nSI = round(P * N * (R / 100), 2)\nprint(SI)"),
 ("What does the `f` do in `f'Amount after {N} years = {A}'`?", "It lets Python insert the values of expressions inside braces into the string", ["It converts every value in the string to a float", "It marks the text as a comment", "It forces the program to read input"], "An f-string formats values by replacing expressions in braces.", "1_variables_and_operators.md, f-strings; PDF p. 29", "integrated_program", "interpret formatted output", "N = 5\nA = 1500\nprint(f'Amount after {N} years = {A}')"),
 ("In a simple `if`/`else`, when does the `else` block run?", "When the `if` condition is False", ["Whenever the `if` condition is True", "Before Python evaluates the condition", "Only when the program reaches a loop"], "The two branches correspond to a True condition and its False alternative.", "PDF p. 31; 2_making_decisions.md, The simple if", "conditionals", "interpret if/else control flow", None),
 ("Why does the `print('Done.')` line run for both positive and negative inputs in this code?", "It is outside the indented `if` block", ["It is inside both the if and else blocks", "Python always runs the last print statement twice", "The condition changes its value after printing"], "Only indented statements belong to the conditional block; the unindented line executes sequentially afterward.", "2_making_decisions.md, Is the number positive?; PDF p. 32", "conditionals", "trace indentation and control flow", "if x > 0:\n    print('positive')\nprint('Done.')"),
 ('Which two details are essential in Python `if` syntax?', "A colon after the condition and indentation for the block", ["A semicolon after the condition and braces around the block", "Capitalizing IF and indenting the condition itself", "A colon after every statement and parentheses around the block"], "The lesson emphasizes the colon and indentation as syntax and block structure.", "PDF p. 31; 2_making_decisions.md, The simple if", "conditionals", "identify conditional syntax requirements", None),
 ("What happens in an `if`/`elif`/`else` chain after Python finds the first true condition?", "It runs that branch and skips the remaining branches", ["It runs every later branch whose condition is true", "It returns to the first condition and checks again", "It always runs the else branch as well"], "Python checks branches in order and executes only the first matching branch.", "PDF p. 33; 2_making_decisions.md, Chained conditions", "conditionals", "interpret chained branch selection", None),
 ("Why can an overly broad `elif a > 0` make a later `elif a > 0 and a % 2 != 0` unreachable?", "Every positive value already matches the earlier branch", ["Python does not allow `and` in an elif", "The earlier branch changes a into zero", "The later condition is checked first"], "Once the broader positive condition matches, the chain skips all later branches.", "2_making_decisions.md, Order matters, and it's silent", "conditionals", "analyze branch ordering", "if a > 0:\n    print('positive')\nelif a > 0 and a % 2 != 0:\n    print('odd positive')"),
 ("Which condition correctly tests whether a whole number `n` is even?", "`n % 2 == 0`", ["`n / 2 == 0`", "`n % 2 == 1`", "`n // 2 == 0`"], "An even integer has remainder zero when divided by 2.", "PDF p. 32; 2_making_decisions.md, Even or odd", "conditionals", "construct a parity condition", None),
 ('Which condition correctly identifies a leap year?', "`year % 400 == 0 or (year % 4 == 0 and year % 100 != 0)`", ["`year % 4 == 0 and year % 100 != 0 and year % 400 == 0`", "`year % 100 == 0 or year % 4 != 0`", "`year % 400 != 0 and year % 4 == 0`"], "A year qualifies if divisible by 400, or divisible by 4 and not by 100.", "PDF pp. 36–37; 2_making_decisions.md, Leap years", "conditional_logic", "combine conditions for a rule", None),
 ('Which applicant meets the loan rule: age at least 21 and income at least 25,000?', "Age 21 and income 25,000", ["Age 20 and income 50,000", "Age 30 and income 24,999", "Age 20 and income 24,999"], "Both thresholds are inclusive and joined with `and`; meeting both exactly is sufficient.", "PDF pp. 36, 38; 2_making_decisions.md, Loan eligibility", "conditional_logic", "apply inclusive compound thresholds", None),
 ("In the electricity tariff code, which rate is applied at exactly 300 units?", "0.15 per unit", ["0.10 per unit", "0.20 per unit", "0.25 per unit"], "The first branch catches up to 100; the next catches remaining units up to and including 300.", "PDF pp. 36, 39; 2_making_decisions.md, The electricity bill", "conditional_logic", "trace ordered tariff boundaries", "if units <= 100:\n    rate = 0.10\nelif units <= 300:\n    rate = 0.15\nelif units <= 500:\n    rate = 0.20\nelse:\n    rate = 0.25"),
 ("In the tariff chain, why is the second branch written `elif units <= 300` rather than `101 <= units <= 300`?", "The first branch has already removed all values at or below 100", ["Python automatically assumes units are integers", "The second branch runs before the first branch", "An elif condition cannot contain two comparisons"], "Only cases not caught by the first condition reach the second branch.", "2_making_decisions.md, Look closely at why elif units <= 300 works", "conditional_logic", "reason about residual branch cases", None),
 ("What is one characteristic of a nested conditional?", "A conditional statement appears inside another conditional's block", ["A condition is automatically repeated until it is false", "It removes the need for indentation", "It requires every branch to use an else"], "Nested conditionals place one decision inside another; the source notes deep nesting can be harder to read.", "PDF p. 35; 2_making_decisions.md, Nested conditions", "conditionals", "identify nested control structure", None),
 ("What is the risk of writing `if x = 10:` in Python?", "It is a syntax error because `=` assigns and cannot serve as the equality test there", ["It compares x with 10 and always returns False", "It assigns 10 to x and then runs the block", "It is valid only when x is a float"], "Python conditions use `==` for equality; a single `=` is assignment and is invalid in the condition syntax.", "PDF p. 32; 1_variables_and_operators.md, = versus ==; 2_making_decisions.md, common mistakes", "comparison_and_logic", "diagnose assignment/comparison misuse", "if x = 10:\n    print('ten')"),
 ("Which value does `A and B or C` produce when A=False, B=True, and C=True?", "True", ["False", "It is undefined", "It raises a TypeError"], "`and` binds first: False and True is False; False or True is True.", "PDF p. 26; 1_variables_and_operators.md, logical precedence", "precedence", "evaluate a compound Boolean expression", "A = False\nB = True\nC = True\nprint(A and B or C)"),
 ("A sensor should trigger an alarm if the pulse is too slow OR blood pressure is too weak. Which operator combines the two trigger conditions?", "`or`, because either condition is sufficient", ["`and`, because both conditions must be true", "`not`, because one condition must be reversed", "`==`, because the conditions must be equal"], "The lecture's heart-monitor example says either alarm condition is enough.", "PDF p. 24; 1_variables_and_operators.md, logical operator examples", "comparison_and_logic", "map a scenario to a logical operator", None),
]

# Focused wording revisions from the keyed-option cue scan. They preserve the
# intended concept and make options more comparable in length.
correct_revisions={
 4:"decimal float",
26:"It inserts brace values into the string",
30:"It runs that branch, then skips the rest",
31:"It matches every positive value first",
 36:"The earlier branch already caught values through 100",
 15:"Exploring data through cells with immediate output",
21:"It displays program output",
22:"`((not A) and B) or C`",
24:"Use parentheses to clarify the intended order",
 38:"It is a syntax error; use `==` to test equality",
 39:"True (Boolean result)"
}
distractor_revisions={
 1:["The operator that adds eight to a value","A Python keyword that declares an integer type in advance","A command that prints the value"],
 2:["Names ignore case","Python converts every name to lowercase","Uppercase names are reserved keywords"],
 4:["integer (int)","text string (str)","Boolean (bool)"],
 5:["`2student`","`student-name2`","`student name`"],
 7:["A file format designed only to display program output during presentations","A replacement for the Python interpreter","A Python keyword that stores variables"],
 8:["Python assumes x starts at zero, adds one, and stores the result as an integer","Python creates x as a string","Python treats the statement as a comment"],
 10:["3.0","3","4 (rounded up)"],
 15:["Integrating a program with other software as one script","Debugging a complete program without separate cells","Running code as one script"],
 16:["3 complete groups and 0 students left over","2 complete groups and 7 students left over","4 complete groups and 4 students left over"],
 20:["Whenever one or both of A and B are True","Only when both are False","Whenever A is False"],
 21:["It assigns a value to a variable","It reads user input","It repeats a block until a condition changes"],
 24:["Use variable capitalization to set the evaluation order","Replace every `and` with `or`","Put the condition in a comment"],
 26:["It forces the program to read input","It converts every value in the string to a floating-point number","It marks the text as a comment"],
 27:["Before evaluation","Only when the program reaches a loop","Whenever the `if` condition is True"],
 28:["It runs after each conditional branch","Python always runs the last print statement twice","The condition changes its value after printing"],
 30:["It always runs the else branch as well","It runs every later branch whose condition is true","It returns to the first condition and checks again"],
 31:["The earlier branch changes a into zero","The later condition is checked first","Python does not allow `and` in an elif"],
 33:["`year % 4 == 0 and year % 100 != 0 and year % 400 == 0 and year > 0`","`year % 100 == 0 or year % 4 != 0`","`year % 400 != 0 and year % 4 == 0`"],
 36:["The second branch condition is evaluated before the first one","The second branch runs before the first branch","An elif condition cannot contain two comparisons"],
 37:["A condition is automatically repeated until it becomes false and the program exits the block","It removes the need for indentation","It requires every branch to use an else"],
 38:["It is valid only when x is a float","It assigns 10 to x before running the indented block","It compares x with 10 and always returns False"],
 39:["It is undefined","It raises a TypeError","False (the result)"],
}

items=[]
for i, (question, correct, distractors, explanation, source, objective, operation, code) in enumerate(raw, 1):
    correct=correct_revisions.get(i,correct)
    distractors=distractor_revisions.get(i,distractors)
    opts = [correct] + distractors
    target = (i - 1) % 4
    # Rotate the right answer into the planned position without changing the key.
    shift = (0 - target) % 4
    opts = opts[shift:] + opts[:shift]
    correct_index = opts.index(correct)
    row={"id":f"M2L1-{i:03d}","question":question,"options":opts,"correctIndex":correct_index,"expectedAnswer":correct,"explanation":explanation,"source":source,"objective":objective,"operation":operation}
    if code: row["stimulusCode"]=code
    items.append(row)

essays = [
{"id":"M2L1-E01","prompt":"A program records a student's name, exam score, whether the student passed, and a decimal average. Give a suitable Python variable assignment for each, identify the four types, and explain how Python determines each type.","marks":5,"responseType":"structured explanation","expectedAnswer":"For example: name='Mona' (str), score=84 (int), passed=True (bool), average=84.5 (float). Python infers each variable's type from its assigned value; no separate declaration is needed.","rubric":[{"criterion":"Provides a valid string assignment for the name","points":1},{"criterion":"Provides a valid integer assignment for score","points":1},{"criterion":"Provides a Boolean assignment for pass status","points":1},{"criterion":"Provides a float assignment for average","points":1},{"criterion":"Explains type inference from assigned values","points":1}],"source":"PDF p. 15; 1_variables_and_operators.md, built-in types","operation":"choose and classify values by type"},
{"id":"M2L1-E02","prompt":"Trace this code and explain why initialization is necessary. State the value printed on each print line.\n\n```python\nx = 6\nprint(x)\nx += 3\nprint(x)\nx -= 2\nprint(x)\n```","marks":5,"responseType":"code trace and explanation","expectedAnswer":"The output is 6, then 9, then 7. The initial assignment creates/initializes x. `+= 3` is equivalent to x=x+3, and `-= 2` is equivalent to x=x-2. Without initialization, Python cannot evaluate the old x on the right-hand side.","rubric":[{"criterion":"Gives first output 6","points":1},{"criterion":"Gives second output 9","points":1},{"criterion":"Gives third output 7","points":1},{"criterion":"Explains += and -= as updates using the old value","points":1},{"criterion":"Explains that x must be initialized before its old value is used","points":1}],"source":"PDF pp. 16–17; 1_variables_and_operators.md, Updating a variable","operation":"trace augmented assignments and explain initialization","stimulusCode":"x = 6\nprint(x)\nx += 3\nprint(x)\nx -= 2\nprint(x)"},
{"id":"M2L1-E03","prompt":"For a=15 and b=4, calculate the results of `a / b`, `a // b`, and `a % b`. Explain what each operator returns and give one practical situation where floor division and modulus are useful.","marks":5,"responseType":"calculation and explanation","expectedAnswer":"a/b=3.75 (regular division, a float); a//b=3 (whole quotient); a%b=3 (remainder). For example, 17 students grouped by 5 gives 3 complete groups and 2 left over.","rubric":[{"criterion":"Calculates regular division as 3.75","points":1},{"criterion":"Calculates floor division as 3","points":1},{"criterion":"Calculates modulus as 3","points":1},{"criterion":"Explains quotient versus remainder roles","points":1},{"criterion":"Gives a sound practical quotient/remainder application","points":1}],"source":"PDF p. 20; 1_variables_and_operators.md, arithmetic operators","operation":"calculate and explain arithmetic operators"},
{"id":"M2L1-E04","prompt":"Evaluate and show the order of operations for both expressions displayed below. State the precedence rules you used.","marks":5,"responseType":"worked evaluation","expectedAnswer":"(a) exponent first: 2**3=8; multiplication: 8*2=16; addition: 8+16=24. (b) arithmetic/comparison first: 4*2>6 is True; 10%3==1 is True; then not True is False; False or True is True. Arithmetic precedes comparison, which precedes logical; within logic, not precedes and precedes or.","rubric":[{"criterion":"Evaluates 2**3 as 8","points":1},{"criterion":"Evaluates expression (a) as 24 with correct order","points":1},{"criterion":"Evaluates left comparison in (b) as True and applies not","points":1},{"criterion":"Evaluates modulus comparison as True and final result as True","points":1},{"criterion":"States relevant arithmetic/comparison/logical precedence","points":1}],"source":"PDF pp. 21–28; 1_variables_and_operators.md, precedence examples","operation":"show and apply multi-level operator precedence","stimulusCode":"8 + 2 ** 3 * 2\nnot (4 * 2 > 6) or 10 % 3 == 1"},
{"id":"M2L1-E05","prompt":"A program should calculate simple interest and the final amount using P=1000, R=10 percent, and N=5 years. Write or describe the calculations for SI and A, give their values, and explain how an f-string can display N and A in a sentence.","marks":5,"responseType":"applied calculation","expectedAnswer":"SI=round(P*N*(R/100),2)=500.0; A=P+SI=1500.0. An f-string such as `f'Amount after {N} years = {A}'` inserts the values inside braces into the output string.","rubric":[{"criterion":"Uses the simple-interest formula with rate divided by 100","points":1},{"criterion":"Calculates SI as 500 (or 500.0)","points":1},{"criterion":"Calculates final amount A as 1500 (or 1500.0)","points":1},{"criterion":"Explains braces in an f-string substitute values","points":1},{"criterion":"Gives a suitable formatted output example or description","points":1}],"source":"PDF p. 29; 1_variables_and_operators.md, Putting it together and f-strings","operation":"apply a formula and describe formatted output"},
{"id":"M2L1-E06","prompt":"Write a conditional outline for an integer `x` that reports whether it is positive, negative, or zero, and whether a nonzero value is even or odd. Explain how the branch order ensures each case is handled once.","marks":5,"responseType":"conditional design","expectedAnswer":"One valid design: if x==0 report zero; elif x>0 and x%2==0 report positive even; elif x>0 report positive odd; elif x%2==0 report negative even; else report negative odd. The conditions are checked in order and the first true branch runs, excluding all later branches.","rubric":[{"criterion":"Handles zero as a separate case","points":1},{"criterion":"Correctly distinguishes positive even and positive odd","points":1},{"criterion":"Correctly distinguishes negative even and negative odd","points":1},{"criterion":"Uses valid if/elif/else structure with sound conditions","points":1},{"criterion":"Explains first-true-branch behavior/order","points":1}],"source":"PDF p. 34; 2_making_decisions.md, Compound conditions","operation":"design and justify a compound conditional"},
{"id":"M2L1-E07","prompt":"An electricity provider uses these rates per unit: up to 100 at 0.10, 101–300 at 0.15, 301–500 at 0.20, and above 500 at 0.25. Complete or describe an ordered `if`/`elif`/`else` structure to select the rate, then state which rate applies at 100, 250, 500, and 501 units.","marks":5,"responseType":"branch design and boundary analysis","expectedAnswer":"Use if units<=100: rate=.10; elif units<=300: rate=.15; elif units<=500: rate=.20; else: rate=.25. The rates at 100, 250, 500, and 501 are .10, .15, .20, and .25. Ordering makes each later upper bound apply only after earlier ranges fail.","rubric":[{"criterion":"Uses ordered if/elif/else upper-bound structure correctly","points":1},{"criterion":"Selects 0.10 at exactly 100","points":1},{"criterion":"Selects 0.15 at 250","points":1},{"criterion":"Selects 0.20 at exactly 500","points":1},{"criterion":"Selects 0.25 at 501 and explains residual branch/order","points":1}],"source":"PDF pp. 36, 39; 2_making_decisions.md, electricity bill","operation":"design a branch chain and test boundary values"},
{"id":"M2L1-E08","prompt":"Compare a simple `if`, an `if`/`else`, an `if`/`elif`/`else` chain, and a nested conditional. Explain how indentation affects their blocks, what happens after the first matching `elif`, and one reason deep nesting can be hard to maintain.","marks":5,"responseType":"structured comparison","expectedAnswer":"A simple if runs a block only when its condition is true; if/else selects between true and false; an elif chain selects the first true condition and skips the rest; nesting places a decision inside another block. Indentation defines membership in blocks. Deep nesting can become harder to read, and an elif chain may express the same decision more clearly.","rubric":[{"criterion":"Explains simple if and if/else roles","points":1},{"criterion":"Explains first-true behavior of an elif chain","points":1},{"criterion":"Describes a nested conditional accurately","points":1},{"criterion":"Explains indentation defines blocks","points":1},{"criterion":"Gives a valid readability/maintenance concern about deep nesting","points":1}],"source":"PDF pp. 31–35; 2_making_decisions.md, conditionals and nesting","operation":"compare conditional structures and control flow"}
]

for i,row in enumerate(essays,1): row["id"]=f"M2L1-E{i:02d}"

import sys
sys.path.insert(0, str(ROOT.parent))
from explanation_overrides import apply_overrides
apply_overrides(ROOT.name, items)
(ROOT/"final_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in items)+"\n")
(ROOT/"essay_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in essays)+"\n")
print(f"created {len(items)} MCQs and {len(essays)} structured responses")
