import json
from pathlib import Path

ROOT = Path(__file__).parent

def mcq(i, q, options, answer, explanation, source, objective, operation, code=None):
    row={"id":f"INTRO-{i:03d}","question":q,"options":options,"correctIndex":answer,"expectedAnswer":options[answer],"explanation":explanation,"source":source,"objective":objective,"operation":operation}
    if code is not None: row["stimulusCode"]=code
    return row

items=[
mcq(1,"Which hardware component is responsible for processing program instructions and asking what comes next?",["Main memory (RAM)","Central Processing Unit (CPU)","Secondary memory","Input/output devices"],1,"The lecture describes the CPU as the part built to process instructions and ask ‘What next?’.","PDF p. 4; intro.md ‘The machine you are talking to’","hardware_architecture","identify a component's role"),
mcq(2,'A CPU is labeled 3.0 GHz. Approximately how many clock cycles per second does that represent?',["3 million cycles","30 million cycles","3 billion cycles","3 billion instructions in every program"],2,"The slide explains that 3.0 GHz corresponds to 3 billion cycles per second; a cycle is not necessarily one instruction.","PDF p. 4; intro.md CPU section","hardware_architecture","interpret a stated clock-rate example"),
mcq(3,'Which property distinguishes main memory (RAM)?',["It is fast for information the CPU needs soon, but loses it when power is off","It is slower than secondary memory and keeps data without power","It is the CPU's control unit","It is used only to connect a computer to a network"],0,"Main memory is nearly as fast as the CPU and its contents vanish when power is removed.","PDF p. 5; intro.md ‘Main memory (RAM)’","hardware_architecture","distinguish volatile main memory"),
mcq(4,'A saved file should remain available after the computer is turned off. Which storage type provides that persistence?',["CPU cache","Main memory only","Secondary memory such as a disk or flash drive","The processor's current instruction"],2,"Secondary memory is slower than RAM but retains information without power.","PDF p. 5; intro.md ‘Secondary memory’","hardware_architecture","select persistent storage"),
mcq(5,"A computer uses a network connection to retrieve information. In the hardware overview, the network is best understood as part of what?",["Secondary memory only","Input/output ways of interacting with the computer","The CPU clock","A programming-language syntax rule"],1,"The slide includes networks among the ways people and computers interact through input/output.","PDF p. 3, 6; intro.md ‘Input / output — the doors’","hardware_architecture","classify an interaction path"),
mcq(6,'Which statement defines programming?',["Designing instructions that tell a computer to carry out tasks","Building computer hardware so it can run faster","Writing only mathematical formulas without an ordered procedure","Translating every program into a flowchart"],0,"Programming is designing or creating instructions for a computer to perform tasks.","PDF p. 8; intro.md ‘What programming actually is’","programming_concepts","interpret a definition"),
mcq(7,"Which pair gives the two phases of a typical programming task in the correct order?",["Implementation, then problem solving","Testing, then input/output","Problem solving, then implementation","Syntax, then semantics"],2,"First define the problem and produce ordered solution steps; then implement them in a programming language.","PDF p. 8; intro.md ‘What programming actually is’","programming_process","recall ordered phases"),
mcq(8,"A student has already planned an algorithm for counting words. What phase begins when they write that algorithm in Python?",["Problem-solving phase","Implementation phase","Hardware-design phase","Semantics phase"],1,"Writing the solution in a programming language is implementation; producing the ordered steps is problem solving.","PDF p. 8; intro.md ‘What programming actually is’","programming_process","classify a phase in context"),
mcq(9,'Which pair of abilities does a programmer need?',["Memorizing machine code and replacing the CPU","Understanding a language's syntax and organizing ideas logically","Designing storage devices and setting clock speed","Using one language's vocabulary in every other language"],1,"The programmer needs language syntax and structure, plus the ability to organize and communicate a solution.","PDF pp. 11–12; intro.md ‘The machine you are talking to’","programmer_skills","combine stated skill requirements"),
mcq(10,'After learning Python, what transfers most directly to learning JavaScript or C++?',["The exact spelling and grammar of Python commands","The problem-solving skills, although vocabulary and grammar change","The Python interpreter itself","The same machine code file"],1,"The lecture says problem-solving skills carry across languages while vocabulary and grammar differ.","PDF p. 12; intro.md programmer-skills section","programmer_skills","distinguish transferable and language-specific knowledge"),
mcq(11,"In a programming language, what does syntax specify?",["The rules for writing statements correctly","The hardware on which a program must run","The meaning of every correct program","The amount of memory a program uses"],0,"Syntax is the set of rules for correctly writing code, analogous to grammar.","PDF p. 14; intro.md ‘Syntax and semantics’","language_concepts","recall a language concept"),
mcq(12,"What does semantics describe in a programming language?",["The spelling rules for keywords","The meaning of code—what it does","The speed of the CPU","The file extension of a compiled program"],1,"Semantics concerns the meaning and behavior of a statement.","PDF p. 14; intro.md ‘Syntax and semantics’","language_concepts","recall a language concept"),
mcq(13,"The two statements below use different syntax but have the same semantics. What do they both do?\n\nPython: print(\"Hello, World\")\nC: printf(\"Hello, World\");",["Display Hello, World","Compile a program into an executable","Read a line from the keyboard","Compare two strings"],0,"Both statements display the text Hello, World; the spellings differ between languages.","PDF p. 14; intro.md syntax/semantics example","language_concepts","interpret two equivalent statements","Python: print(\"Hello, World\")\nC: printf(\"Hello, World\");"),
mcq(14,'Which description matches machine language?',["A high-level language with English-like keywords","A low-level language made entirely of binary digits that the CPU can execute","A domain-specific language for databases","An intermediate language executed by a virtual machine"],1,"Machine language consists of 0s and 1s and is directly executable by the CPU.","PDF p. 16; intro.md language-abstraction section","language_types","identify machine language"),
mcq(15,'How does assembly language relate to machine language?',["It is a more readable representation of machine instructions, but remains low-level","It is the same as a general-purpose high-level language","It is a database-specific language","It is Java's intermediate bytecode"],0,"Assembly gives a more readable representation of machine code while remaining a low-level language.","PDF p. 16; intro.md language-abstraction section","language_types","interpret a relationship between levels"),
mcq(16,'Why are Python, Java, and C++ considered high-level languages?',["They consist only of binary digits","They hide much hardware complexity and are easier for people to write and maintain","They can only be used for one specialized task","They run without translation on every CPU"],1,"High-level languages provide abstraction and more user-friendly syntax, hiding much hardware complexity.","PDF p. 16; intro.md language-abstraction section","language_types","apply abstraction criteria"),
mcq(17,'A language can be classified by abstraction level, execution method, paradigm, and domain. What does this imply?',["A language can receive classifications on several different axes","Every language belongs to exactly one category total","Execution method and paradigm mean the same thing","A high-level language must be domain-specific"],0,"The slide presents several classification criteria, each describing a different aspect of a language.","PDF p. 15; intro.md language-types overview","language_types","infer how classification axes relate"),
mcq(18,"Which pair is given as examples of procedural languages?",["C and Pascal","Prolog and SQL","Java and MATLAB","Python and HTML"],0,"The lecture names C and Pascal as procedural-language examples.","PDF p. 17; intro.md programming-paradigm section","language_types","retrieve examples of a paradigm"),
mcq(19,'What organizes an object-oriented program?',["Binary digits and hardware addresses","Objects and classes, supporting modularity and reuse","Formal logic statements only","Database queries only"],1,"The lecture describes OOP as based on objects and classes for modularity and reuse.","PDF p. 17; intro.md programming-paradigm section","language_types","interpret a paradigm description"),
mcq(20,'Which language is an example of a logic-based language?',["Pascal","Prolog","C++","MATLAB"],1,"Prolog is the listed logic-based-language example.","PDF p. 17; intro.md programming-paradigm section","language_types","retrieve an example"),
mcq(21,'Which language is designed specifically for working with databases?',["Python","C++","SQL","Pascal"],2,"The slide identifies SQL as a database-specific language.","PDF p. 17; intro.md domain-specific section","language_types","classify by application domain"),
mcq(22,"Which language is given as a general-purpose example?",["SQL","MATLAB","Python","HTML"],2,"Python is listed among general-purpose languages used for a wide variety of applications.","PDF p. 17; intro.md domain-specific section","language_types","classify by application scope"),
mcq(23,'Python is commonly described along several classification axes. Which combination is accurate?',["Low-level, logic-based, domain-specific, compiled","High-level, object-oriented example, general-purpose, interpreted","Machine language, procedural, database-specific, hybrid","Assembly, logic-based, general-purpose, compiled"],1,"The lecture places Python among high-level, OOP, general-purpose, and interpreted examples; those labels refer to separate axes.","PDF pp. 16–19; intro.md language-types sections","language_types","coordinate several classification criteria"),
mcq(24,'What does a compiler do?',["Translates source code line by line while it runs","Translates the entire source before execution","Converts a program only into flowchart symbols","Checks semantics but does not translate code"],1,"A compiler translates the whole source before execution.","PDF pp. 18, 20; intro.md ‘Why Python, and what “interpreted” means’","execution_methods","distinguish translation methods"),
mcq(25,'What output does a compiler commonly produce for later execution?',["A flowchart with decision diamonds","An executable file containing translated code","A set of Python comments","A keyboard input stream"],1,"The lecture says a compiler places translated code in a file, often an executable such as .exe or .dll on Windows.","PDF p. 18, 20; intro.md compiler/interpreter table","execution_methods","identify a compiler output"),
mcq(26,'How does an interpreter execute a program in the simplified line-by-line model?',["It translates and executes source code line by line at runtime","It translates the entire source into an executable before running","It changes source code into a flowchart","It runs only machine code written by hand"],0,"The interpreter is described as translating and running code line by line during execution.","PDF pp. 19–20; intro.md compiler/interpreter table","execution_methods","describe interpreter behavior"),
mcq(27,'Which interpreter feature can help with learning and debugging?',["It always runs faster than compiled code","It gives feedback during execution, making testing and debugging more immediate","It generates an executable file before running","It prevents runtime errors"],1,"The source describes interactive feedback as helpful for testing and debugging, while noting interpreted programs are often slower.","PDF pp. 19–20; intro.md ‘The translator in the room’","execution_methods","infer a stated trade-off"),
mcq(28,'What is the typical relationship between compilation and execution speed?',["Interpreted programs are always faster","Compiled programs are typically faster after compilation","Compilers cannot produce machine code","Both methods always run at identical speed"],1,"The slides say compiled programs typically execute faster after compilation; the wording is a general tendency, not an absolute.","PDF pp. 18, 20; intro.md compiler/interpreter table","execution_methods","interpret a qualified comparison"),
mcq(29,'Why is Java described as a hybrid language?',["It uses only machine language","It compiles to intermediate bytecode that runs on a virtual machine","It is both a database language and a flowchart","It translates every line directly without an intermediate form"],1,"The source describes Java as compiling to bytecode and then running that bytecode on a virtual machine.","PDF p. 19; intro.md Java paragraph","execution_methods","explain a hybrid execution path"),
mcq(30,"[Code] What kind of error does this example contain?\n\nif x > 5\n    print(\"x is greater than 5\")",["Syntax error","Runtime error","Logical error","Semantic error"],0,"The if statement is missing its required colon, so the code violates Python syntax before execution.","PDF p. 25; intro.md syntax-errors example","error_types","classify a concrete syntax error","if x > 5\n    print(\"x is greater than 5\")"),
mcq(31,"[Code] Why is the first assignment invalid in Python?\n\ndef = \"Ahmed\"",["def is a reserved keyword and cannot be used as a variable name","The string must use single quotation marks","Python variable names must be numbers","A variable cannot store text"],0,"The source lists def as a reserved keyword, so using it as a variable name is a syntax error.","PDF p. 25; intro.md common syntax mistakes","error_types","diagnose a named syntax rule","def = \"Ahmed\""),
mcq(32,"[Code] What type of error occurs when execution reaches this expression?\n\nresult = 10 / 0",["Syntax error","Runtime error","Logical error","Semantic error"],1,"The expression is syntactically valid, but division by zero raises ZeroDivisionError during execution.","PDF p. 26; intro.md runtime-errors section","error_types","classify an execution-time failure","result = 10 / 0"),
mcq(33,'[Code] Which runtime error is raised by this expression?\n\nvalue = "5" + 2',["TypeError","ValueError","IndexError","ZeroDivisionError"],0,"The operation combines text and an integer, so the source identifies it as TypeError.","PDF p. 26; intro.md runtime-errors section","error_types","match a failure to its named type","value = \"5\" + 2"),
mcq(34,"[Code] What happens when this program is run?\n\nprint(\"This line works fine.\")\nresult = 10 / 0\nprint(\"This line never happens.\")",["Both messages print and the program ends normally","The first message prints, then execution stops with ZeroDivisionError","No line runs because the code has a syntax error","The last message prints before the division occurs"],1,"Execution reaches and prints the first line, then crashes at division by zero; the final print is not reached.","PDF p. 26; intro.md runtime example","error_types","trace execution up to a runtime failure","print(\"This line works fine.\")\nresult = 10 / 0\nprint(\"This line never happens.\")"),
mcq(35,"[Code] If x starts at 2, why does this loop fail to terminate?\n\nwhile x > 0:\n    x = x + 1",["The condition stays true because each pass increases positive x","Python treats > as an assignment symbol","The loop contains a missing colon","The body changes x to zero"],0,"For a positive starting x, adding 1 keeps x positive, so x > 0 never becomes false. The source classifies this as a logical error.","PDF p. 27; intro.md logical-errors section","error_types","diagnose a loop's state change","x = 2\nwhile x > 0:\n    x = x + 1"),
mcq(36,"[Code] Why can the condition below never be true for any single numeric value of x?\n\nif x > 10 and x < 5:",["A value cannot be both greater than 10 and less than 5","The word and always makes a condition true","The code is missing a closing quotation mark","The condition compares x with text"],0,"The two comparisons are mutually incompatible, matching the lecture's wrong-Boolean-logic example.","PDF p. 27; intro.md logical-errors section","error_types","analyze a Boolean condition","if x > 10 and x < 5:"),
mcq(37,"[Code] Starting with a=5 and b=9, what values remain after these two assignments?\n\na = b\nb = a",["a=5 and b=9","a=9 and b=5","a=9 and b=9","a=5 and b=5"],2,"The first line sets a to 9; the second then copies the already changed a into b, so both are 9.","PDF p. 27; intro.md swapping-values example","error_types","trace a mistaken state update","a = 5\nb = 9\na = b\nb = a"),
mcq(38,"[Code] A rectangle's area should be length × width. What kind of mistake is shown?\n\nlength = 10\nwidth = 4\narea = length + width",["Syntax error","Runtime error","Logical error from a loop condition","Semantic error from using the wrong formula"],3,"The expression is legal Python and runs, but its meaning does not match the intended area formula; the source labels this semantic.","PDF p. 28; intro.md semantic-error example","error_types","classify a source-defined semantic mistake","length = 10\nwidth = 4\narea = length + width"),
mcq(39,"[Code] The intended grouping is (tax + price) × discount. Which expression preserves that grouping in Python?\n\ntax = 2\nprice = 10\ndiscount = 0.5",["tax + price * discount","(tax + price) * discount","tax * (price + discount)","tax + price + discount"],1,"Parentheses force tax and price to be added before multiplying by discount, matching the intended grouping.","PDF p. 28; intro.md order-of-operations example","error_types","select an expression with the intended semantics","tax = 2\nprice = 10\ndiscount = 0.5"),
mcq(40,"[Code] In a Python condition that checks whether x equals 10, which operator belongs in the condition?\n\nif x __ 10:",["!=, because it tests that x and 10 have the same value","==, because it compares x with 10","=, because it starts an if statement","Neither; Python conditions cannot compare numbers"],1,"A single = assigns a value; == tests equality. Using = in this condition is a syntax error.","PDF p. 25; intro.md syntax-errors table","error_types","distinguish assignment from comparison","if x __ 10:"),
]

essays=[
{"id":"INTRO-E01","prompt":"A small data-analysis program accepts a file from a user, processes its records, keeps temporary values while running, and saves a report that should remain after shutdown. Identify the likely input/output device, the component that executes instructions, the temporary memory, and the persistent storage. Explain the RAM-versus-secondary-memory difference.","responseType":"structured explanation","marks":5,"expectedAnswer":"The keyboard/network/file selection path is input and the screen is output; the CPU executes instructions; RAM holds working values and is volatile; secondary memory such as a disk/flash drive stores the saved report persistently and is slower than RAM.","rubric":[{"criterion":"Names a suitable input device, such as a keyboard or mouse, and an output device, such as a screen","points":1},{"criterion":"Identifies the CPU as the component that executes instructions","points":1},{"criterion":"Identifies RAM as temporary working memory","points":1},{"criterion":"Identifies secondary storage as persistent report storage","points":1},{"criterion":"Explains that RAM is volatile and faster, while secondary storage is persistent and generally slower","points":1}],"source":"PDF pp. 3–6; intro.md hardware section","operation":"map roles in a hardware scenario"},
{"id":"INTRO-E02","prompt":'A team wants a program that counts words in a document. Describe the problem-solving phase and the implementation phase for this task. Then state one programmer skill needed in each phase.',"responseType":"structured explanation","marks":5,"expectedAnswer":"Problem solving defines the word-counting problem and produces ordered steps, such as reading text, counting words, and reporting counts. Implementation writes those steps in a language such as Python. Problem solving uses logical organization/communication; implementation also requires language vocabulary, syntax, and structure.","rubric":[{"criterion":"Describes defining the problem and its intended result","points":1},{"criterion":"Gives an ordered algorithmic plan for counting words","points":1},{"criterion":"Explains implementation translates the plan into a language","points":1},{"criterion":"Names logical organization/communication as a relevant skill","points":1},{"criterion":"Names syntax/vocabulary/structure as a relevant language skill","points":1}],"source":"PDF pp. 8–12; intro.md programming and programmer-skills sections","operation":"apply the two-phase model and connect skills"},
{"id":"INTRO-E03","prompt":'Explain the difference between syntax and semantics using these two examples. State whether they have the same meaning and name one syntax difference.\n\nPython: print("Hello, World")\nC: printf("Hello, World");',"responseType":"comparison","marks":5,"expectedAnswer":"Syntax is the language-specific form; semantics is what a statement means. Both statements display Hello, World, so they have the same semantics. The C form uses printf and a semicolon; Python uses print and does not require that semicolon.","rubric":[{"criterion":"Defines syntax as rules/form of writing","points":1},{"criterion":"Defines semantics as meaning/behavior","points":1},{"criterion":"States that both examples display the same text","points":1},{"criterion":"Names a correct difference in spelling/function name","points":1},{"criterion":"Names the C semicolon versus Python form distinction","points":1}],"source":"PDF p. 14; intro.md syntax/semantics section","operation":"compare syntax and semantics across examples","stimulusCode":"Python: print(\"Hello, World\")\nC: printf(\"Hello, World\");"},
{"id":"INTRO-E04","prompt":'Classify Python using four different axes: level of abstraction, programming paradigm, domain scope, and execution method. Give one reason or contrast for each classification.',"responseType":"classification with justification","marks":5,"expectedAnswer":"Python is high-level, supports object-oriented programming, is general-purpose, and is commonly executed through an interpreter. These labels describe separate properties, so they can all apply at once.","rubric":[{"criterion":"Classifies Python as high-level and explains its abstraction from hardware details","points":1},{"criterion":"Identifies Python as supporting object-oriented programming and relates this to objects or classes","points":1},{"criterion":"Classifies it as general-purpose","points":1},{"criterion":"Classifies Python as commonly interpreted and describes how the interpreter runs code","points":1},{"criterion":"Explains that these labels describe separate properties","points":1}],"source":"PDF pp. 15–19; intro.md language-types sections","operation":"coordinate multiple independent classification axes"},
{"id":"INTRO-E05","prompt":'Compare a compiler, an interpreter, and Java’s hybrid approach. For each, describe when translation happens and what intermediate or output form it produces. Give one trade-off between compiled and interpreted execution.',"responseType":"comparison","marks":5,"expectedAnswer":"A compiler translates the whole source before execution and produces an executable file. An interpreter translates and runs line by line during execution without producing a separate executable in the lesson's model. Java compiles to bytecode that runs on a virtual machine. Compiled execution is typically faster after compilation; interpretation gives more immediate feedback/easier interactive debugging and is often slower.","rubric":[{"criterion":"Describes whole-source translation before execution by compiler","points":1},{"criterion":"Identifies executable output from compilation","points":1},{"criterion":"Describes line-by-line runtime translation by interpreter","points":1},{"criterion":"Describes Java bytecode and virtual machine","points":1},{"criterion":"States a supported speed/debugging trade-off","points":1}],"source":"PDF pp. 18–20; intro.md compiler/interpreter/hybrid section","operation":"compare translation workflows and trade-offs"},
{"id":"INTRO-E06","prompt":"Classify each example as syntax, runtime, logical, or semantic error, and briefly say when or how it is noticed: (a) `if x > 5` has no colon; (b) `10 / 0`; (c) `while x > 0: x = x + 1` with positive x; (d) `area = length + width` when calculating rectangle area.","responseType":"error classification","marks":5,"expectedAnswer":"(a) Syntax: rejected before execution. (b) Runtime: crashes when the division line executes. (c) Logical: the loop condition remains true and it does not terminate. (d) Semantic: legal code runs but uses the wrong formula/meaning. The lecture notes that logical and semantic errors can both produce wrong behavior without a syntax warning, so the examples distinguish their specific causes.","rubric":[{"criterion":"Classifies missing colon as syntax and says it prevents execution","points":1},{"criterion":"Classifies division by zero as runtime","points":1},{"criterion":"Classifies the nonterminating loop as logical and explains the condition","points":1},{"criterion":"Classifies wrong area formula as semantic","points":1},{"criterion":"Explains the concrete difference between the loop-logic and formula-meaning examples","points":1}],"source":"PDF pp. 23–28; intro.md four-error-types section","operation":"classify and distinguish concrete error causes"},
{"id":"INTRO-E07","prompt":"The program below is intended to count x down to zero and print the final value, but x increases instead. Trace the first three values of x, explain why the loop does not finish when x starts at 2, and give a one-line correction.\n\n```python\nx = 2\nwhile x > 0:\n    x = x + 1\nprint(x)\n```","responseType":"trace and repair","marks":5,"expectedAnswer":"The successive values are 2, 3, 4, ... . Each remains positive, so x > 0 stays true. Change the update to x = x - 1; then the values are 2, 1, 0 and the loop ends.","rubric":[{"criterion":"Gives first three values 2, 3, 4","points":1},{"criterion":"States x stays positive under the shown update","points":1},{"criterion":"Connects that state to the condition remaining true","points":1},{"criterion":"Provides x = x - 1 as a correction","points":1},{"criterion":"Identifies the original problem as a logical loop error","points":1}],"source":"PDF p. 27; intro.md logical-errors example","operation":"trace and correct a logical loop error","stimulusCode":"x = 2\nwhile x > 0:\n    x = x + 1\nprint(x)"},
{"id":"INTRO-E08","prompt":'Given this compound-interest program, identify its inputs and explain what the loop prints at the end of year 1. State the final compound interest and explain the role of `**` in the calculation.\n\n```python\nP = 10000\nR = 12\nT = 1\nn = 4\nyear = 1\nwhile year <= T:\n    A = P * (1 + R / (100 * n)) ** (n * year)\n    print("End of year", year, "-> A =", round(A, 2), "EGP")\n    year = year + 1\nCI = A - P\nprint("Compound interest =", round(CI, 2), "EGP")\n```',"responseType":"code trace and explanation","marks":5,"expectedAnswer":"Inputs are P, R, T, and n. At year 1, A = 10000*(1+12/(100*4))^4 = 10000*(1.03)^4 = 11255.0881, so the rounded year-end amount printed is 11255.09 EGP. The loop runs once for T=1; CI=A-P=1255.0881, so compound interest prints as 1255.09 EGP. `**` raises the base to the power n*year.","rubric":[{"criterion":"Identifies P, R, T, and n as the inputs","points":1},{"criterion":"Correctly evaluates the periodic rate factor as 1.03 and exponent as 4","points":1},{"criterion":"Gives rounded year-end amount 11255.09","points":1},{"criterion":"Computes compound interest as amount minus principal, rounded 1255.09","points":1},{"criterion":"Explains ** as exponentiation and that the loop visits year 1","points":1}],"source":"intro.md ‘Putting the whole module together’; PDF pp. 8, 27–28 for process/error concepts","operation":"trace an integrated program and explain its operators","stimulusCode":"P = 10000\nR = 12\nT = 1\nn = 4\nyear = 1\nwhile year <= T:\n    A = P * (1 + R / (100 * n)) ** (n * year)\n    print(\"End of year\", year, \"-> A =\", round(A, 2), \"EGP\")\n    year = year + 1\nCI = A - P\nprint(\"Compound interest =\", round(CI, 2), \"EGP\")"}
]

choice_revisions={
 1:(0,["CPU: processes the program's next instruction","RAM stores temporary working values","Secondary memory: keeps files when power is off","I/O devices: connect the computer and its user"]),
 3:(0,["It is fast working memory, and loses its contents without power","It is persistent storage that keeps information after the computer is turned off","It is a CPU component that connects networks to programs","It is slower storage that keeps files after power is removed"]),
 4:(2,["CPU cache keeps frequently used information near the processor","RAM holds information for quick access while power is on","Secondary memory on disk or flash retains data without power","A register holds the current instruction being executed"]),
 5:(1,["The CPU clock controls the pace at which instructions are processed","Network access is an input/output route for retrieving information","Secondary memory stores files for use after shutdown","Programming syntax specifies how code is written"]),
 9:(0,["Knowing syntax and arranging a solution clearly","Designing CPUs and choosing their clock speed","Memorizing binary and avoiding all storage devices","Learning one language's grammar for use everywhere"]),
 10:(1,["Python's exact command spelling transfers unchanged to each language","Problem-solving carries over while vocabulary and grammar change","The Python interpreter itself carries over to other languages","A compiled machine-code file is shared across languages"]),
 11:(2,["The rules for choosing hardware, memory, and storage when running code","The amount of memory that a program can use","The rules for writing valid statements in that language","The hardware on which the program must run"]),
 14:(1,["A high-level language with English-like keywords and symbols","A low-level language of binary digits that the CPU can execute","A database-specific language for storing and retrieving records","An intermediate form that runs on a virtual machine"]),
 15:(0,["A more readable low-level form of machine instructions","A domain-specific language designed for database queries","Java's intermediate bytecode for a virtual machine","A high-level language intended for many kinds of tasks"]),
 16:(1,["They are limited to a single specialized application","They abstract hardware details and use readable syntax","They consist entirely of binary digits for the CPU","They execute directly on every CPU without translation"]),
 17:(0,["Each criterion describes a different property of a language","Every language belongs to exactly one category and cannot have other labels","Execution method means the same thing as paradigm","High-level languages must be domain-specific"]),
 18:(1,["Python only","C and Pascal are procedural examples","Java and MATLAB are procedural-language examples","Python and HTML are procedural-language examples"]),
 19:(2,["They organize programs around binary digits and addresses","They use formal logic statements for every operation","They organize code around objects and classes for reuse","They are limited to database queries and tables"]),
 23:(0,["High-level, object-oriented, general-purpose, interpreted","Low-level, logic-based, domain-specific, compiled","Machine language, procedural, database-specific, hybrid language","Assembly, logic-based, general-purpose, compiled"]),
 25:(0,["A translated executable file prepared for later execution","A flowchart that displays every program decision before execution begins","A collection of comments added to Python source code","A stream of keyboard input sent to the running program"]),
 27:(2,["It prevents runtime errors from occurring in a program","It always executes faster than compiled code","It gives feedback as code runs, which can help debugging","It creates a standalone executable before running the source"]),
 28:(3,["Compiled programs always run faster in every situation","Both methods run at precisely the same speed","Interpreted programs are always faster than compiled ones","Compiled code typically runs faster after translation"]),
 29:(0,["Java compiles to bytecode that runs on a virtual machine","Java runs only as machine code written by a programmer directly on the processor","Java combines a database language with a flowchart","Java interprets each line without an intermediate form"]),
 30:(1,["Runtime error: execution crashes on an operation","Syntax error: the code is rejected before execution","Logical error: the code runs but gives a wrong result","Semantic error: a legal expression uses the wrong formula"]),
 31:(2,["Python requires variable names to contain at least one number and start with a letter","Python allows only single-quoted text values","Python reserves def as a keyword, so it cannot name a variable","Python does not allow text to be stored in a variable"]),
 33:(0,["TypeError: adding text and an integer is incompatible","ValueError: an argument has a suitable type but invalid value","IndexError: a requested position is not present in a sequence","ZeroDivisionError: a number is divided by zero"]),
 34:(1,["The first and last messages print, and the program completes normally","The first message prints; division by zero then stops execution","No message prints because the file has a syntax error","Only the final message prints after division is attempted"]),
 35:(2,["Each pass reduces x until it reaches zero","The comparison symbol assigns a new value to x","Each pass raises positive x, so x > 0 stays true","A missing colon prevents the loop from being parsed"]),
 36:(3,["The word and always makes a condition true","The code is missing a closing quotation mark","The condition compares x with text","No number satisfies both x > 10 and x < 5"]),
 38:(1,["Logical error: the loop condition causes incorrect behavior","Semantic error: the formula gives the wrong meaning","Syntax error: a required symbol or keyword is missing","Runtime error: execution crashes on an operation"])
}
for row in items:
    number=int(row['id'][-3:])
    if number in choice_revisions:
        idx,options=choice_revisions[number]
        row['options']=options
        row['correctIndex']=idx
        row['expectedAnswer']=options[idx]

code_objectives={13,30,31,32,33,34,35,36,37,38,39,40}
for row in items:
    if row["id"].startswith("INTRO-") and int(row["id"][-3:]) in code_objectives and "stimulusCode" not in row:
        # Each code-led MCQ has a clean snippet separate from explanatory prose.
        row["stimulusCode"] = row["question"].partition("\n\n")[2].strip()

for i,row in enumerate(items):
    target=i%4
    current=row["options"].index(row["expectedAnswer"])
    shift=current-target
    row["options"]=row["options"][shift:]+row["options"][:shift]
    row["correctIndex"]=target

import sys
sys.path.insert(0, str(ROOT.parent))
from explanation_overrides import apply_overrides
apply_overrides(ROOT.name, items)
(ROOT/"final_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in items)+"\n")
(ROOT/"essay_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in essays)+"\n")
print(f"created {len(items)} MCQs and {len(essays)} structured-response prompts")
