import json
from pathlib import Path
ROOT=Path(__file__).parent

raw=[
 ("When is a `for` loop usually the more direct choice?","When the number of repetitions or items to visit is known",["When repetition should continue until an unknown condition changes","When the program must skip every other line","When no block of code should repeat"],"The lesson recommends for when the repeat count is known or a sequence is available.","Choosing a loop","select a loop from known repetition count",None),
 ("When does the lesson recommend a `while` loop?","When a condition controls how long repetition continues",["Only when the loop must visit every item in a collection","Only when exactly five repetitions are required","When the loop body contains no condition"],"A while loop suits repetition whose duration is not known in advance and is controlled by a condition.","Choosing a loop","select a loop for condition-controlled repetition",None),
 ("Which sequence gives the four parts of the while-loop pattern in the lesson?","Initialize, test, body, update",["Test condition, output, break, return","Input value, print, compare, stop","Define, call, import, update"],"The lesson carries forward initialize, test, body, and update from the earlier flowchart model.","The while loop","recall the while-loop structure",None),
 ("In a counter-controlled `while` loop, what is the usual purpose of the update statement?","Move the control variable toward a false condition",["Reset the counter to its initial value on every pass","Skip evaluation of the condition entirely","Run the loop body one extra time after termination"],"An update changes the control variable so the while condition can eventually fail.","The while loop","explain the update's role","i = 1\nwhile i <= 5:\n    print(i)\n    i += 1"),
 ("How many times does the body run in this loop?","5",["4","6","It never stops"],"The values 1 through 5 satisfy the condition, then i becomes 6 and the test fails.","The while loop","trace a bounded while loop","i = 1\nwhile i <= 5:\n    print(i)\n    i += 1"),
 ("After the loop finishes, what value does `i` have?","6",["5","4","1"],"The last body pass uses i=5 and increments it to 6; then i<=5 is false.","The while loop","trace a loop's final control value","i = 1\nwhile i <= 5:\n    i += 1"),
 ("What values are produced by `range(5)`?","0, 1, 2, 3, 4",["1, 2, 3, 4, 5","0, 1, 2, 3, 4, 5","5 only"],"range(stop) starts at zero and stops before stop.","How range() works","interpret range(stop)",None),
 ("Which values are visited by `range(2, 6)`?","2, 3, 4, 5",["2, 3, 4, 5, 6","1, 2, 3, 4, 5","3, 4, 5, 6"],"The start value is included and the stop value 6 is excluded.","How range() works","interpret range(start, stop)",None),
 ("Which sequence comes from `range(0, 21, 5)`?","0, 5, 10, 15, 20",["0, 5, 10, 15, 20, 25","5, 10, 15, 20","0, 1, 2, 3, 4, 5"],"The start is 0, the step is 5, and values stop before 21.","How range() works","trace range with a step","print(list(range(0, 21, 5)))"),
 ("What is the last value visited by `range(1, 101)`?","100",["99","101","1"],"range excludes its stop, so 101 is not included and 100 is the last value.","range() stops before the last number","avoid an off-by-one error",None),
 ("Which range visits every integer from 1 through 100, including 100?","`range(1, 101)`",["`range(1, 100)`","`range(0, 100)`","`range(1, 100, 2)`"],"Because the stop is excluded, use 101 to include 100.","range() stops before the last number","choose an inclusive counting range",None),
 ("What sum is produced by adding all integers from 1 through 100?","5050",["5000","4950","5051"],"The loop and built-in example both sum 1 through 100 to 5050.","Sum 1 to 100","calculate an accumulation result","total = 0\nfor n in range(1, 101):\n    total += n\nprint(total)"),
 ("Which built-in expression gives the sum of integers from 1 through 100?","`sum(range(1, 101))`",["`sum(range(1, 100))`","`range(sum(1, 101))`","`sum(range(1, 101, 2))`"],"The source shows sum(range(1,101)) as the compact version of the loop.","Sum 1 to 100","select an equivalent built-in expression",None),
 ("How can a for loop visit each country in a list without using `range()`?","Visit list items directly, one per pass",["Convert the list length into a while condition only","Call break once for each country","Use the list as the loop's Boolean condition"],"A for loop can walk a collection directly, one item at a time.","Looping over a collection","choose direct collection iteration",None),
 ("How many characters does `for letter in 'Python'` visit?","6",["5","7","1"],"The string Python contains six characters, and the loop visits each one.","Looping over a collection","count string iterations","for letter in 'Python':\n    print(letter)"),
 ("What does `break` do when executed inside a loop?","Leaves the loop immediately",["Skips only the current pass and continues with the next one","Restarts the loop from its first value","Waits for more input"],"break exits the loop at once.","break and continue","identify break behavior",None),
 ("What does `continue` do when executed inside a loop?","Skip the rest of this pass and move to the next",["Stop the loop right away","Restarts the program from its first line","Finishes every remaining loop pass without testing"],"continue advances to the next iteration without running the rest of the current pass.","break and continue","identify continue behavior",None),
 ("In the search loop, what happens after the first odd number 15 is found?","The loop exits because `break` runs",["The loop skips 15 and checks 23","The loop prints every remaining number","The loop restarts at 4"],"The loop prints 4 and 8 as even, prints the first odd number 15, then break exits.","break and continue","trace early loop exit","for n in [4, 8, 15, 23, 42]:\n    if n % 2 != 0:\n        print(n)\n        break\n    print(n, 'is even')"),
 ("Which values are printed by the continue example that keeps multiples of 3 from 1 through 10?","3, 6, 9",["1, 2, 3, 4, 5, 6, 7, 8, 9, 10","3, 6, 8","1, 4, 7, 10"],"Nonmultiples trigger continue; the multiples 3, 6, and 9 reach print.","break and continue","trace a filtering loop","for n in range(1, 11):\n    if n % 3 != 0:\n        continue\n    print(n)"),
 ("With an outer loop of 3 iterations and an inner loop of 4 iterations on every pass, how many times does the inner body run?","12",["14","4","3"],"The inner loop runs four times for each of the three outer iterations: 3*4=12.","Nested loops","calculate nested iteration count","for row in range(3):\n    for col in range(4):\n        pass"),
 ("How many product values are placed in a 5-row by 5-column multiplication table built with nested loops?","25",["10","20","5"],"Each of five outer passes runs five inner passes, giving 5*5=25 cells.","A multiplication table","count nested-loop body executions","for row in range(1, 6):\n    for col in range(1, 6):\n        print(row * col)"),
 ("Two nested loops that each run 1,000 times have how many combined inner-body passes?","1,000,000",["2,000,000","1,000","100,000"],"Nested iteration counts multiply: 1,000*1,000 is one million.","Nested loops multiply, they don't add","reason about nested work",None),
 ("Why should an accumulating loop usually set `total = 0` before it starts?","Initialize the accumulator at zero",["So the loop condition is automatically true","So break can reset the total","So range() knows its stop value"],"The accumulator needs an initial value before each loop pass adds to it.","Sum 1 to 100","explain accumulator initialization",None),
 ("In the lesson's while-loop pattern, what should happen before the first condition test?","Initialize the control variable",["Update the variable using its old value","Run the body once","Call continue"],"The control value must exist before the condition is evaluated.","The while loop","identify initialization placement",None),
 ("A population starts at 1,000 and grows by 2% in one year. What is its value after that update?","1,020",["1,002","1,200","980"],"The update is 1000 + 1000*0.02 = 1020.","Population growth","calculate one growth step","population = 1000\nrate = 0.02\npopulation += population * rate"),
 ("A population of 1,000 grows by 2% each year. Approximately what is it after 10 yearly updates?","1,218.99",["1,200.00","1,020.00","1,000.20"],"Repeated growth gives 1000*(1.02)^10, approximately 1218.99.","Population growth","calculate repeated exponential growth",None),
 ("A price of 250 increases by 8% for one year. What is the new price before rounding?","270",["258","250.08","230"],"One update is 250 + 250*0.08 = 270.","Inflation","calculate one inflation update",None),
 ("A price of 250 rises by 8% per year for five years. Approximately what is the final price?","367.33",["350.00","290.00","367.00"],"Repeated growth gives 250*(1.08)^5 = 367.332..., rounded to 367.33.","Inflation","calculate repeated inflation",None),
 ("If a growth-model rate is -0.05, what does the sign indicate in the lesson's model?","The quantity decays by 5% per period",["The quantity grows by 5% per period","The quantity becomes negative immediately","The loop must execute five times"],"The same update formula models decay when the rate is negative.","The two modelling exercises","interpret a negative growth rate",None),
 ("In `quantity += quantity * rate`, what is added to the current quantity each period?","The current quantity multiplied by the rate",["The rate multiplied by the year number only","A fixed amount unrelated to the current quantity","The current quantity divided by the rate"],"The loop adds the current value's rate-sized change, producing proportional growth or decay.","The two modelling exercises","interpret the growth update","quantity += quantity * rate"),
 ("In the lesson's response list, how many Male entries are present?","2",["3","4","6"],"The list contains Male twice and Female four times.","Counting things in a list","count category occurrences","genders = ['Male', 'Female', 'Female', 'Male', 'Female', 'Female']"),
 ("For 2 Male responses out of 6 total, what percentage is Male to two decimal places?","33.33%",["25.00%","50.00%","66.67%"],"2/6*100 is 33.333..., which rounds to 33.33%.","Counting responses","calculate a category percentage",None),
 ("Why does the lesson set `total = len(genders)` before calculating percentages?","Use list length as the denominator",["It counts only Male responses","It converts every item to a string","It stops the for loop after the last item"],"The percentage for each category divides its count by the total list length.","Counting things in a list","interpret the percentage denominator",None),
 ("When does the majority message report Male in the response-counting example?","When `count_male > count_female`",["When `count_male == count_female`","When `count_male < count_female`","Whenever the list has six items"],"The example compares the two counters and reports Male when the male count is greater.","Counting things in a list","interpret a majority comparison",None),
 ("What does the loop variable `item` represent in `for item in genders`?","The current item in the list for this pass",["The position number assigned to every list item","The total number of list elements","A copy of the entire list on every pass"],"A for loop takes one item from the sequence on each pass and binds it to the loop variable.","Counting things in a list","interpret a for-loop variable",None),
 ("In `range(start, stop, step)`, is the stop value included?","No; range stops before that value",["Yes, always","Only if step is positive","Only when start is zero, unless the step is positive"],"range excludes its stop value, including the three-argument form.","How range() works","interpret range endpoint semantics",None),
 ("Why does the multiples-of-3 loop use `continue` for values where `n % 3 != 0`?","Skip the rest of this pass and continue",["Those values terminate the loop immediately","Those values are added to a total","Those values restart the range at 1"],"continue skips the remaining body for a nonmultiple and advances the loop.","break and continue","explain a filter using continue", "for n in range(1, 11):\n    if n % 3 != 0:\n        continue\n    print(n)"),
 ("What repeated-code pattern does the lesson say can signal that a function would help?","Repeated counting loops for gender and vote data",["A loop that visits a string one character at a time","A range with a step of five","A single break statement in a search"],"The repeated counting block for different categories is described as a sign to extract a reusable function.","Counting things in a list","recognize duplication as a refactoring cue",None),
 ("Why can the same growth loop model population, inflation, interest, or currency depreciation?","Reuse the update pattern with different inputs",["Each topic requires a different kind of loop keyword","The loop body never changes the value","All four quantities use the same numerical rate"],"The lesson emphasizes one reusable growth pattern with different quantities and parameters.","Same loop, four different questions","identify a shared model structure",None),
 ("When is a `while` loop's condition checked?","Before each possible body pass",["Only once, before the loop starts","Only after the body runs","Only after the update statement"],"A while loop tests its condition before each body pass; if it is false initially, the body does not run.","The while loop","identify pre-test loop behavior",None),
]

essays=[
{"id":"M2L3-E01","prompt":"Trace this loop. List each value printed and state the value of `i` after the loop ends. Explain how the test and update make it terminate.\n\n```python\ni = 1\nwhile i <= 5:\n    print(i)\n    i += 1\n```","responseType":"code trace","expectedAnswer":"It prints 1, 2, 3, 4, 5. The update makes i become 6; the next test 6<=5 is false, so the loop ends with i=6.","rubric":[{"criterion":"Lists the printed values 1 through 5","points":1},{"criterion":"Gives final i as 6","points":1},{"criterion":"Explains the condition is tested before each body pass","points":1},{"criterion":"Explains the increment moves i toward failing the test","points":1},{"criterion":"Identifies termination when i<=5 becomes false","points":1}],"source":"3_loops.md, four parts of a while loop","operation":"trace a while loop and explain termination","stimulusCode":"i = 1\nwhile i <= 5:\n    print(i)\n    i += 1","marks":5},
{"id":"M2L3-E02","prompt":"For each expression, list every value generated and explain the stop-exclusive endpoint: (a) `range(5)`; (b) `range(2, 6)`; (c) `range(0, 21, 5)`. Then give the range that counts from 1 through 100 inclusive.","responseType":"range analysis","expectedAnswer":"(a) 0,1,2,3,4; (b) 2,3,4,5; (c) 0,5,10,15,20. The stop is excluded. To include 100, use range(1,101).","rubric":[{"criterion":"Lists range(5) values correctly","points":1},{"criterion":"Lists range(2,6) values correctly","points":1},{"criterion":"Lists range(0,21,5) values correctly","points":1},{"criterion":"Explains that stop is excluded","points":1},{"criterion":"Gives range(1,101) for 1 through 100 inclusive","points":1}],"source":"3_loops.md, How range() works","operation":"analyze range signatures and endpoints","marks":5},
{"id":"M2L3-E03","prompt":"Write both a while-loop outline and a for-loop outline to add the integers from 1 through 100. State the common total and explain why the for-loop range stops at 101.","responseType":"algorithm comparison","expectedAnswer":"While: total=0; n=1; while n<=100: add n; increment n. For: total=0; for n in range(1,101): add n. Both give 5050; range excludes its stop, so 101 is used to include 100.","rubric":[{"criterion":"Initializes the accumulator and counter for while","points":1},{"criterion":"Uses a correct while condition and update","points":1},{"criterion":"Uses range(1,101) for the for version","points":1},{"criterion":"Gives total 5050","points":1},{"criterion":"Explains the excluded endpoint","points":1}],"source":"3_loops.md, Sum 1 to 100","operation":"compare loop forms for an accumulation","marks":5},
{"id":"M2L3-E04","prompt":"Trace the search loop over `[4, 8, 15, 23, 42]`. State each printed line and explain exactly what `break` changes. Then explain how `continue` in the multiples-of-3 example changes one pass.","responseType":"control-flow trace","expectedAnswer":"It prints `4 is even`, `8 is even`, then `15` as the first odd and exits immediately; 23 and 42 are not visited. break leaves the loop. continue skips the remaining statements in its current pass and starts the next pass.","rubric":[{"criterion":"Gives the two even outputs for 4 and 8","points":1},{"criterion":"Identifies 15 as the first odd value printed","points":1},{"criterion":"States later list items are not processed after break","points":1},{"criterion":"Explains break exits the loop","points":1},{"criterion":"Explains continue skips to the next iteration","points":1}],"source":"3_loops.md, break and continue","operation":"trace and compare loop-control statements","stimulusCode":"for n in [4, 8, 15, 23, 42]:\n    if n % 2 != 0:\n        print('First odd number found:', n)\n        break\n    print(n, 'is even, keep looking')","marks":5},
{"id":"M2L3-E05","prompt":"A 5-by-5 multiplication table uses `for row in range(1, 6)` and, inside it, `for col in range(1, 6)`. State how many times the inner body runs, describe the order of repetition, and explain why nested iteration counts multiply.","responseType":"nested-loop analysis","expectedAnswer":"The inner body runs 25 times. For each of the five row values, the inner loop visits all five column values. Thus 5*5=25, rather than 5+5.","rubric":[{"criterion":"Identifies five outer iterations","points":1},{"criterion":"Identifies five inner iterations per outer pass","points":1},{"criterion":"Calculates 25 total body executions","points":1},{"criterion":"Explains the inner loop completes on each outer pass","points":1},{"criterion":"Explains why iteration counts multiply","points":1}],"source":"3_loops.md, Nested loops and multiplication table","operation":"analyze nested-loop execution count","stimulusCode":"for row in range(1, 6):\n    for col in range(1, 6):\n        print(row * col)","marks":5},
{"id":"M2L3-E06","prompt":"A population starts at 1,000 and grows by 2% annually for 10 years. Write the repeated update and loop bounds, give the approximate final population, and explain why this is exponential growth rather than adding a fixed 20 each year.","responseType":"growth model","expectedAnswer":"Initialize population=1000, rate=0.02, year=1; while year<=10: population += population*rate; year +=1. Final value is 1000*(1.02)^10 = about 1218.99. Each year's increase depends on the current population, so the increase itself grows rather than staying fixed at 20.","rubric":[{"criterion":"States the proportional update population += population*rate","points":1},{"criterion":"Gives a loop that repeats for 10 years with a changing year counter","points":1},{"criterion":"Calculates approximately 1218.99","points":1},{"criterion":"Explains the next increase depends on the current population","points":1},{"criterion":"Distinguishes the model from fixed addition of 20 each year","points":1}],"source":"3_loops.md, Population growth and modelling exercises","operation":"specify and interpret repeated proportional growth","marks":5},
{"id":"M2L3-E07","prompt":"For the list `['Male','Female','Female','Male','Female','Female']`, give the two counts and their percentages to two decimal places. Describe the loop counters and explain why `len(list)` is the denominator.","responseType":"counting and percentages","expectedAnswer":"Male count=2 (33.33%); Female count=4 (66.67%). Initialize both counters at zero, visit each item and increment its matching counter. The total is six, so each percentage is count/6*100.","rubric":[{"criterion":"Counts 2 Male responses","points":1},{"criterion":"Counts 4 Female responses","points":1},{"criterion":"Calculates percentages 33.33% and 66.67%","points":1},{"criterion":"Describes initialization and per-item counter updates","points":1},{"criterion":"Explains the full-list length is the denominator","points":1}],"source":"3_loops.md, Counting things in a list","operation":"calculate category frequencies and percentages","marks":5},
{"id":"M2L3-E08","prompt":"The lesson repeats nearly identical counting code once for gender responses and again for votes. Explain why this duplication suggests a function, and identify which parts of the logic can stay the same and which data should vary between calls.","responseType":"structured explanation","expectedAnswer":"A repeated block signals an opportunity to define reusable code as a function, avoiding duplicated logic. The traversal and counting pattern can stay the same, while the input list and category values (such as Male/Female or candidate names) vary between calls.","rubric":[{"criterion":"Identifies repeated code as duplication","points":1},{"criterion":"Explains a function can package reusable logic","points":1},{"criterion":"States the traversal/counting pattern can remain the same","points":1},{"criterion":"Identifies the input data/categories as varying","points":1},{"criterion":"Connects reuse to reduced duplication or easier maintenance","points":1}],"source":"3_loops.md, Counting things in a list; Same loop, four different questions","operation":"identify an abstraction opportunity from repeated loop logic","marks":5}
]

# Mark curated Bloom anchors with lesson 3 IDs and give every response its stable ID.
for i,row in enumerate(essays,1): row["id"]=f"M2L3-E{i:02d}"
items=[]
for i,(q,key,distr,why,section,operation,code) in enumerate(raw,1):
    opts=[key]+distr
    target=(i-1)%4
    shift=(-target)%4
    opts=opts[shift:]+opts[:shift]
    row={"id":f"M2L3-{i:03d}","question":q,"options":opts,"correctIndex":opts.index(key),"expectedAnswer":key,"explanation":why,"source":f"3_loops.md — {section}","objective":"loops","operation":operation}
    if code: row["stimulusCode"]=code
    items.append(row)
import sys
sys.path.insert(0, str(ROOT.parent))
from explanation_overrides import apply_overrides
apply_overrides(ROOT.name, items)
(ROOT/"final_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in items)+"\n")
(ROOT/"essay_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in essays)+"\n")
print(f"created {len(items)} loops MCQs and {len(essays)} structured responses")
