import json
import random
import re
from collections import Counter
from html import escape
from pathlib import Path

ROOT = Path(__file__).parent
random.seed(33026)

# question, answer, three distractors, explanation, PDF page, objective, operation, code
raw = [
    ("A column contains 8 non-missing values and 2 missing values. What does `df.count()` report for that column?", "8", ["10", "2", "The sum of the values"], "`count()` reports the number of non-null observations in each column, rather than the total row count.", 34, "count non-missing observations", "interpret count", "# One column has 10 rows, 2 missing\nprint(df.count())"),
    ('For a numeric DataFrame, what does `df.mean()` calculate by default?', "The mean of each column", ["The mean of each row", "The median of each column", "The mean of the index labels"], "The example uses the default axis to calculate a mean down each column; `axis=1` would operate across rows.", 34, "calculate column summaries", "interpret the default axis", None),
    ("What is the result type of `df.agg(['mean', 'median', 'std'])`?", "A DataFrame", ["A single number", "A Boolean mask", "A list of column labels"], "The aggregation applies several functions and returns a DataFrame with statistics as rows and variables as columns.", 35, "aggregate multiple statistics", "identify result structure", "vstat = df.agg(['mean', 'median', 'std'])"),
    ("Which statistic in numeric `describe()` output is the 50th percentile?", "`50%`", ["`25%`", "`std`", "`count`"], "The 50th percentile is the median, shown as `50%` in `describe()` output.", 36, "read describe output", "identify the median", None),
    ("A numeric column's `describe()` output has count 40, min 2, max 98. What does `count` mean here?", "There are 40 non-null observations", ["There are 40 unique values", "The average value is 40", "The column has 40 missing observations"], "For numerical columns, describe's count is the number of non-null observations.", 36, "interpret describe output", "interpret a summary statistic", None),
    ('A mixed DataFrame has numeric and categorical columns. By default, what does plain `df.describe()` summarize in pandas?', "The numerical columns", ["Only categorical columns", "Every column using the same eight statistics", "Only the index"], "The PDF notes that a mixed DataFrame's default `describe()` returns numerical-variable summaries.", 36, "summarize mixed data", "predict default describe scope", None),
    ("Which set of fields is characteristic of `describe()` on a categorical column?", "count, unique, top, freq", ["mean, std, min, max", "sum, median, variance, range", "true, false, null, total"], "Categorical describe output reports non-null count, number of unique values, most frequent value (`top`), and its frequency.", 36, "summarize categorical data", "recognize categorical summary fields", None),
    ("A variable's mean is much higher than its median. What is a reasonable interpretation to investigate?", "The distribution may be right-skewed, making the mean a less representative summary", ["The variable must be normally distributed", "There are no extreme values", "The median is necessarily calculated incorrectly"], "A large separation between mean and median can signal skew; inspect the distribution and context before choosing a summary.", 36, "interpret mean and median", "reason about skew", None),
    ("A survey summary reports a minimum age of −4. What should the analyst do first?", "Investigate it as a possible data-quality problem", ["Treat it as evidence that negative age is common", "Delete the whole dataset", "Replace every age with the mean without checking"], "An impossible minimum can indicate a data-quality issue rather than a meaningful finding.", 36, "audit summary statistics", "respond to an implausible value", None),
    ("The value of `df.corr()['GDP']['population']` is 0.78. What does this describe?", "A positive association between GDP and population in the observed data", ["GDP causes population to increase", "Population causes GDP to increase", "GDP and population are identical variables"], "Correlation describes co-movement; it does not establish causal direction or causation.", 37, "interpret correlation", "avoid causal overclaim", "r = df.corr()['GDP']['population']\nprint(r)  # 0.78"),
    ("Why should an analyst be cautious about a correlation computed from only four countries?", "A strong-looking value from so few observations is weak evidence and may occur by chance", ["Correlation is undefined for any dataset with fewer than five rows", "Four observations prove the relationship is causal", "A correlation matrix always removes sampling uncertainty"], "The lesson specifically warns that correlations based on four observations are not persuasive evidence.", 37, "assess correlation evidence", "evaluate sample-size limits", None),
    ("What does `data.isna()` produce?", "A same-shaped Boolean DataFrame marking missing values as True", ["A Series of means", "A DataFrame with all missing rows removed", "A count of distinct values"], "`isna()` marks missing entries as True and observed entries as False in a Boolean structure matching the data.", 39, "locate missing data", "interpret isna", None),
    ("What does `data.isna().sum()` normally give in a DataFrame with columns A and B?", "A missing-value count for each column", ["The number of rows after dropping missing data", "A Boolean for each entire column", "The sum of all observed numeric values"], "Summing the True values from `isna()` yields the number of missing entries in each column.", 39, "count missing data", "interpret missingness counts", "missing_by_column = data.isna().sum()"),
    ("What happens to the original `data` after `clean = data.dropna()` when `inplace` is not set?", "`clean` has rows with missing values removed; `data` remains unchanged", ["Both variables are changed in place", "`clean` is None and `data` is changed", "Only columns with missing values are removed from `data`"], "The default `dropna()` returns a cleaned object and leaves the original DataFrame unchanged.", 39, "remove incomplete rows", "trace dropna return behavior", "clean = data.dropna()"),
    ("A table has missing values in columns A and B. You want to retain rows whenever A is present, even if B is missing. Which call fits?", "`data.dropna(subset=['A'])`", ["`data.dropna(axis=1)`", "`data.dropna(subset=['B'])`", "`data.isna(subset=['A'])`"], "The subset argument restricts the missingness check to A, so rows are removed only when A is missing.", 39, "drop rows based on selected fields", "choose a subset rule", None),
    ("What does `data.dropna(axis=1)` remove by default?", "Columns that contain missing values", ["Rows that contain missing values", "Only rows where every value is missing", "The index column"], "`axis=1` selects columns as the objects to drop; with default how='any', columns containing a missing value are removed.", 39, "remove columns with missing data", "interpret axis in dropna", "data_without_gap_columns = data.dropna(axis=1)"),
    ('Before using `dropna()`, why should you count missing values and report removals?', "Removing incomplete cases can change who remains in the analysis and may bias conclusions", ["`dropna()` automatically replaces every missing value with zero", "Rows with missing data are always duplicates", "A reported sample size is unrelated to data cleaning"], "Missingness may be systematic, so deleting those cases changes the analyzed population and needs justification.", 39, "make a responsible missing-data decision", "evaluate deletion consequences", None),
    ("Which sequence best describes `groupby()`?", "Split rows into groups, apply a calculation, combine the results", ["Sort columns, delete rows, and rename the index", "Read a CSV, draw a plot, and save an image", "Convert each value to text, then concatenate columns"], "Groupby follows the split–apply–combine pattern described in the source.", 40, "explain groupby", "identify the workflow", None),
    ("Given groups A, B, C each appear twice, what does `df.groupby('key').size()` report?", "The number of rows in each group", ["The sum of the data values in each group", "The number of columns in the original table", "The count of distinct key labels in each row"], "Group size counts rows in each group, irrespective of whether a separate value column contains missing data.", 41, "count rows in groups", "interpret group size", "df = pd.DataFrame({'key':['A','B','C','A','B','C'], 'data':range(6)})\nprint(df.groupby('key').size())"),
    ("For `key` values A, B, C, A, B, C and `data` values 0–5, what is the sum for group A?", "3", ["2", "6", "9"], "Group A contains data values 0 and 3, whose sum is 3.", 41, "aggregate within groups", "compute a grouped sum", "df = pd.DataFrame({'key':['A','B','C','A','B','C'], 'data':range(6)})\nprint(df.groupby('key')['data'].sum())"),
    ("Which expression computes both the sum and count of `data` within each `key` group?", "`df.groupby('key')['data'].agg(['sum', 'count'])`", ["`df.groupby('key').size(['sum', 'count'])`", "`df.agg('key', ['sum', 'count'])`", "`df['data'].groupby(['sum', 'count'])`"], "Select the value column after grouping and pass both aggregation names to `agg()`.", 41, "apply multiple group aggregations", "construct a grouped aggregation", None),
    ("What does `df.groupby('key').get_group('A')` return?", "The subset of original rows whose key is A", ["A scalar equal to the mean of group A", "The group-size table for all keys", "The original DataFrame with key renamed to A"], "`get_group` retrieves the rows belonging to the specified group.", 41, "retrieve a group", "interpret get_group", None),
    ("In `df.groupby('Department')['Salary'].mean()`, which quantity is computed for each department?", "The average Salary among rows in that department", ["The total number of departments", "The average of all columns for each employee", "The median Salary across all departments combined"], "The grouping key partitions records by department, then mean is applied to the selected Salary column.", 44, "summarize a numeric measure by category", "interpret grouped mean", None),
    ("What does grouping by both `Department` and `Year` do before aggregation?", "Creates groups for each observed Department–Year combination", ["Creates one group for each row regardless of values", "Uses Year only and ignores Department", "Adds Year to every salary value"], "Multiple grouping keys define subgroups for each combination of their values.", 43, "group by multiple categories", "interpret composite groups", "df.groupby(['Department', 'Year'])['Salary'].mean()"),
    ('After grouping by Department and Year, what does `.unstack()` do to the table?', "Moves one index level, such as Year, into columns", ["Removes all rows containing missing values", "Calculates a second mean", "Sorts each group's salary values"], "Unstack pivots an inner index level into columns, producing a wider cross-tabular result.", 44, "reshape grouped results", "interpret unstack", None),
    ("Which expression returns both mean and standard deviation of Salary for each Department–Year group?", "`df.groupby(['Department','Year'])['Salary'].agg(['mean','std'])`", ["`df.groupby('Salary').mean(['Department','Year'])`", "`df.agg(['Department','Year'], ['mean','std'])`", "`df.groupby(['Department','Year']).size()`"], "Grouped `agg()` applies both requested summary functions to the Salary values in each combined group.", 44, "summarize groups with multiple measures", "select grouped aggregations", None),
    ("To count employees in every Department–Year group, which operation is most direct?", "`df.groupby(['Department', 'Year']).size()`", ["`df.groupby(['Department', 'Year']).mean()`", "`df.describe()`", "`df['Department'].value_counts(normalize=True)`"], "The source uses groupby size to count records in each pair of groups.", 44, "count records in composite groups", "choose a grouped count", None),
    ("A group contains 5 rows, but one row has a missing Salary. What are `group.size()` and `group['Salary'].count()` respectively?", "5 rows and 4 non-missing salaries", ["4 rows and 5 non-missing salaries", "5 for both because count includes missing values", "1 row and 4 unique salaries"], "`size()` counts rows; `count()` on Salary counts only non-null Salary entries.", 40, "distinguish group size and non-null count", "compare counting methods", None),
    ("What does Boolean indexing such as `df[df['Country'] == 'UK']` keep?", "Rows for which the condition is True", ["Columns for which the label equals UK", "Rows for which the condition is False", "Only the Boolean mask, not the matching records"], "The comparison creates a Boolean Series; using it inside brackets keeps rows marked True.", 49, "filter with a Boolean condition", "interpret Boolean indexing", "mask = df['Country'] == 'UK'\nselected = df[mask]"),
    ("Which expression filters for rows where City is not London?", "`df[df['City'] != 'London']`", ["`df[df['City'] == 'London']`", "`df['City'] != 'London'`", "`df.drop(columns='City')`"], "The Boolean condition uses not-equal and is applied to the DataFrame to retain matching rows.", 49, "filter rows by inequality", "write a filter", None),
    ("Which `query()` call is equivalent to `df[df['Country'] == 'UK']`?", "`df.query(\"Country == 'UK'\")`", ["`df.query(\"Country != 'UK'\")`", "`df.query(Country == UK)`", "`df['Country'].query('UK')`"], "The query string expresses the same equality condition in a readable form.", 48, "filter with query", "translate between filter syntaxes", None),
    ('When combining two pandas Series conditions element by element, which operators represent AND and OR?', "`&` for AND and `|` for OR", ["`and` for AND and `or` for OR", "`&&` for AND and `||` for OR", "`+` for AND and `*` for OR"], "Pandas conditions operate across Series values, so use element-wise `&` and `|` rather than Python's scalar `and` and `or`.", 49, "combine Boolean conditions", "select elementwise operators", None),
    ("In a filter like `(df['age'] >= 18) & (df['score'] > 70)`, why should each comparison be parenthesized?", "Because of operator precedence: parentheses ensure each comparison is evaluated before combining", ["Parentheses convert strings to numbers", "Pandas requires every DataFrame to have two conditions", "The parentheses cause the filter to sort its results"], "The lesson cautions that `&` binds more tightly than comparisons, so each condition must be grouped explicitly.", 49, "write valid combined filters", "explain parentheses", "df[(df['age'] >= 18) & (df['score'] > 70)]"),
    ("A researcher wants rows from Egypt OR Sweden. Which combined filter has the intended meaning?", "`(df['Country'] == 'Egypt') | (df['Country'] == 'Sweden')`", ["`(df['Country'] == 'Egypt') & (df['Country'] == 'Sweden')`", "`df['Country'] == ('Egypt' | 'Sweden')`", "`df[df['Country'] != 'Egypt'] & 'Sweden'`"], "A row cannot have both values at once; OR combines the two equality conditions to keep either category.", 49, "combine alternative categories", "apply Boolean OR", None),
    ("Which call reads a local comma-separated file named `survey.csv` into a DataFrame?", "`pd.read_csv('survey.csv')`", ["`pd.to_csv('survey.csv')`", "`pd.read_excel('survey.csv')`", "`pd.DataFrame.read('survey.csv')`"], "`read_csv` reads a CSV file into a DataFrame.", 50, "read CSV data", "select a file-reading function", None),
    ("Which expression writes a DataFrame summary to a CSV file named `summary.csv`?", "`summary.to_csv('summary.csv')`", ["`summary.read_csv('summary.csv')`", "`pd.read_csv(summary, 'summary.csv')`", "`summary.to_excel('summary.csv')`"], "The DataFrame method `to_csv` writes the object to a comma-separated file.", 53, "write CSV output", "select a CSV export method", "summary = df.describe().round(2)\nsummary.to_csv('summary.csv')"),
    ('A researcher needs an Excel workbook rather than a CSV. Which method exports to Excel?', "`summary.to_excel('summary.xlsx')`", ["`summary.to_csv('summary.xlsx')`", "`pd.read_excel(summary)`", "`summary.to_xlsx('summary.xlsx')`"], "The lesson uses `to_excel` to save a DataFrame to an Excel workbook.", 53, "write Excel output", "select an Excel export method", None),
    ("What does `df['sex'].value_counts()` return?", "A Series with counts for each distinct sex category", ["A DataFrame of means for every numerical column", "A Boolean Series marking missing values", "The number of rows in the whole DataFrame only"], "`value_counts()` tabulates how often each unique category appears.", 52, "count categorical values", "interpret value_counts", "counts = df['sex'].value_counts()"),
    ("What changes when calling `df['sex'].value_counts(normalize=True)`?", "The output gives proportions rather than raw counts", ["It sorts category labels alphabetically", "It removes categories with fewer than two records", "It returns only missing values"], "The normalize option expresses category frequencies as proportions of the total.", 52, "calculate category proportions", "interpret normalization", None),
    ('`pclass.value_counts()` orders categories by frequency. What does `.sort_index()` change?', "Orders the result by category label, such as class 1, 2, 3", ["Orders the result from largest count to smallest", "Converts counts to proportions", "Removes the index labels"], "`value_counts()` sorts by frequency; `sort_index()` reorders by the category labels, useful when they have a meaningful order.", 52, "order category counts", "distinguish sorting by label and frequency", "class_count = df['pclass'].value_counts().sort_index()"),
]

essays = [
    {"prompt":"A numeric dataset has columns for income and age. Explain what `describe()` reports for a numeric variable, how you would use count, quartiles, mean, median, minimum, and maximum to inspect it, and identify two warning signs that merit follow-up.",
     "expectedAnswer":"Numeric describe reports count, mean, standard deviation, min, 25%, 50% (median), 75%, and max. Compare counts across variables to detect missingness; compare mean and median for possible skew; check min/max for impossible values or outliers. These are diagnostic clues requiring contextual inspection, not automatic proof of an error.",
     "justification":"The answer follows the numerical describe checklist and the lesson's guidance to treat unequal counts, mean–median gaps, and impossible extrema as prompts for investigation.",
     "rubric":[{"criterion":"Names the main numerical describe statistics", "points":1},{"criterion":"Explains count as non-null observations", "points":1},{"criterion":"Uses mean/median separation to discuss skew", "points":1},{"criterion":"Identifies an implausible min/max as a data-quality warning", "points":1},{"criterion":"Frames warnings as requiring investigation", "points":1}],
     "source":"3_summarising_and_filtering.md — describe(); PDF pp. 36–38", "operation":"interpret and critique descriptive summaries", "stimulusCode":"df['income'].describe()\n# count, mean, std, min, 25%, 50%, 75%, max"},
    {"prompt":"An analyst finds a correlation of 0.78 between GDP and population across four countries. Explain the numerical direction, two reasons this result is weak evidence, and what cannot be concluded from the correlation alone.",
     "expectedAnswer":"The positive value indicates that GDP and population move together positively in these observations. With only four countries, the estimate is highly uncertain and strong-looking correlations can arise by chance. More broadly, correlation does not establish that GDP causes population changes or identify causal direction; other factors or data patterns may explain co-movement.",
     "justification":"The source explicitly cautions against treating four-point correlations as evidence and distinguishes association from causation.",
     "rubric":[{"criterion":"Interprets 0.78 as positive association", "points":1},{"criterion":"Notes the very small sample", "points":1},{"criterion":"Explains chance/instability as a limitation", "points":1},{"criterion":"States correlation does not prove causation", "points":1},{"criterion":"Avoids asserting causal direction", "points":1}],
     "source":"3_summarising_and_filtering.md — Correlation; PDF pp. 37–38", "operation":"evaluate correlation evidence", "stimulusCode":"r = 0.78\nobservations = 4 countries"},
    {"prompt":"A six-row dataset has missing values in columns A and B. A researcher wants to keep every row where A is observed, even if B is missing. Describe how to count missingness, produce that subset, and explain why deleting all incomplete rows without checking can distort the study.",
     "expectedAnswer":"Use `data.isna().sum()` to count missing entries per column, then `data.dropna(subset=['A'])` to return rows with non-missing A while allowing B to remain missing. Default dropna returns a new DataFrame, so assign it if the cleaned result should be retained. Removing all incomplete rows may exclude people or cases systematically associated with missingness, changing the population represented and potentially biasing results; report how many rows are removed and why.",
     "justification":"This applies the lesson's missingness diagnosis, subset behavior, default return semantics, and caution that deletion is an analytical decision.",
     "rubric":[{"criterion":"Uses isna().sum() to count per-column gaps", "points":1},{"criterion":"Uses subset=['A'] correctly", "points":1},{"criterion":"Notes B may remain missing and/or default non-mutation", "points":1},{"criterion":"Explains selection/bias risk from deletion", "points":1},{"criterion":"Recommends reporting the number removed and rationale", "points":1}],
     "source":"3_summarising_and_filtering.md — Missing data; PDF p. 39", "operation":"choose and justify a missing-data operation", "stimulusCode":"A: [1, 2, None, 4, 5, 6]\nB: [0.2, None, None, 4, 5, 6]"},
    {"prompt":"Using a dataset with Department, Year, and Salary, write a workflow to find mean salary for each department and year, then show how to produce means and standard deviations together and reshape years into columns. Explain split–apply–combine and the role of `unstack()`.",
     "expectedAnswer":"For example, `df.groupby(['Department','Year'])['Salary'].mean()` groups records by both keys and computes a mean per combination. For two measures, use `.agg(['mean','std'])` after selecting Salary. `.unstack()` pivots one grouped index level, such as Year, into columns. Split–apply–combine means partition records by groups, calculate within each group, and combine summaries into a result.",
     "justification":"The answer integrates the two-key employee example, aggregation, and the lesson's explanation of reshaping multi-index group results.",
     "rubric":[{"criterion":"Groups by both Department and Year", "points":1},{"criterion":"Computes mean Salary by group", "points":1},{"criterion":"Uses agg for mean and std", "points":1},{"criterion":"Explains split–apply–combine", "points":1},{"criterion":"Explains unstack as moving an index level into columns", "points":1}],
     "source":"3_summarising_and_filtering.md — groupby(); PDF pp. 40–46", "operation":"construct and explain a multi-key grouped summary", "stimulusCode":"df.groupby(['Department', 'Year'])['Salary'].mean().unstack()"},
    {"prompt":"A table contains Country and City columns. Write both Boolean-indexing and `query()` expressions to select rows where Country is Egypt and City is not Cairo. Explain why the conditions use parentheses and `&` rather than Python's `and`.",
     "expectedAnswer":"Boolean indexing: `df[(df['Country'] == 'Egypt') & (df['City'] != 'Cairo')]`. Query form: `df.query(\"Country == 'Egypt' and City != 'Cairo'\")` (using the lesson's query syntax). Each Boolean comparison is parenthesized before combining with `&`; pandas combines elementwise Boolean Series, whereas Python `and` expects single truth values and is ambiguous for a Series.",
     "justification":"The response tests both filter forms and the course's key warning about elementwise logical operators and precedence.",
     "rubric":[{"criterion":"Writes a correct Boolean filter for both conditions", "points":1},{"criterion":"Uses parentheses around each comparison", "points":1},{"criterion":"Uses elementwise `&`", "points":1},{"criterion":"Writes equivalent query expression", "points":1},{"criterion":"Explains why Series conditions cannot use Python `and`", "points":1}],
     "source":"3_summarising_and_filtering.md — Filtering; PDF pp. 48–49", "operation":"write and explain a compound row filter", "stimulusCode":"Country == 'Egypt'\nCity != 'Cairo'"},
    {"prompt":"Outline a reproducible workflow for reading `survey.csv`, inspecting its dimensions and structure, previewing records, summarizing numeric fields, and saving the summary as both CSV and Excel. Name the relevant pandas calls and distinguish reading from writing.",
     "expectedAnswer":"Read with `df = pd.read_csv('survey.csv')`. Inspect using `df.shape`, `df.info()`, and `df.head()` (or `tail`/`sample`). Create a summary such as `summary = df.describe().round(2)`. Export with `summary.to_csv('summary.csv')` and `summary.to_excel('summary.xlsx')`. `read_csv` loads a file into a DataFrame; `to_csv` and `to_excel` write a DataFrame to files.",
     "justification":"The answer reflects the lesson's CSV reading, inspection, summary, and CSV/Excel export examples while distinguishing input and output methods.",
     "rubric":[{"criterion":"Uses read_csv to load the file", "points":1},{"criterion":"Uses shape/info or preview to inspect it", "points":1},{"criterion":"Creates a numeric summary", "points":1},{"criterion":"Exports CSV with to_csv", "points":1},{"criterion":"Exports Excel with to_excel and distinguishes directions", "points":1}],
     "source":"3_summarising_and_filtering.md — Reading and writing CSV files; PDF pp. 50–53", "operation":"plan an import-summary-export workflow", "stimulusCode":"df = pd.read_csv('survey.csv')\nsummary = df.describe().round(2)"},
    {"prompt":"For a categorical variable such as passenger class, explain what `value_counts()` reports, how normalization changes the result, and why `sort_index()` may be useful after counting. Contrast this with grouping a numeric variable to calculate its mean by category.",
     "expectedAnswer":"`value_counts()` returns a Series counting how often each unique category occurs. `normalize=True` expresses those counts as proportions. Counts are sorted by frequency by default; `.sort_index()` orders by category labels, useful for naturally ordered classes. For a numeric variable, `df.groupby('category')['value'].mean()` instead calculates a numerical summary within each category rather than category frequencies.",
     "justification":"The response draws on the final categorical-count examples and links them to the group's numerical summarization approach taught earlier in the lesson.",
     "rubric":[{"criterion":"Explains category frequencies", "points":1},{"criterion":"Explains normalization as proportions", "points":1},{"criterion":"Explains frequency sort versus index sort", "points":1},{"criterion":"Gives a valid numeric groupby mean", "points":1},{"criterion":"Distinguishes counts from within-category numeric summaries", "points":1}],
     "source":"3_summarising_and_filtering.md — value_counts(); PDF pp. 40–46, 52", "operation":"compare categorical and numeric group summaries", "stimulusCode":"df['pclass'].value_counts(normalize=True).sort_index()"},
    {"prompt":"A policy dataset contains Department, Year, Employee, and Salary. Describe a set of group summaries that would answer (1) average salary by department, (2) average salary by department and year, (3) group size by department and year. State when `count()` and `size()` would differ if Salary contains missing values.",
     "expectedAnswer":"Use `df.groupby('Department')['Salary'].mean()` for department means; `df.groupby(['Department','Year'])['Salary'].mean().unstack()` for department-year means; and `df.groupby(['Department','Year']).size().unstack()` for row counts. `size()` counts all rows in a group; `count()` applied to Salary counts only non-missing salary entries, so it is lower when some salaries are missing.",
     "justification":"The task combines the employee case study's main group questions with the conceptual difference between counting records and counting observed field values.",
     "rubric":[{"criterion":"Gives department-level salary mean", "points":1},{"criterion":"Gives department-year salary mean", "points":1},{"criterion":"Uses size for group record counts", "points":1},{"criterion":"Explains count excludes missing Salary", "points":1},{"criterion":"Explains size includes every row", "points":1}],
     "source":"3_summarising_and_filtering.md — groupby(); PDF pp. 40–46", "operation":"select group summaries and interpret counts", "stimulusCode":"# Department | Year | Employee | Salary"},
]

mcqs = []
positions = [0, 1, 2, 3] * 10
for i, (question, answer, distractors, explanation, page, objective, operation, code) in enumerate(raw, 1):
    options = list(distractors)
    options.insert(positions[i-1], answer)
    item = {"id":f"M3L3-{i:03d}", "question":question, "options":options, "correctIndex":positions[i-1],
            "expectedAnswer":answer, "explanation":explanation,
            "source":f"3_summarising_and_filtering.md — {objective}; Module 3 Lecture 3_1 PDF p. {page}",
            "objective":objective, "operation":operation}
    if code:
        item["stimulusCode"] = code
    mcqs.append(item)

for i, item in enumerate(essays, 1):
    item.update({"id":f"M3L3-E{i:02d}", "responseType":"structured response", "marks":5})

def dump_jsonl(name, rows):
    (ROOT / name).write_text("\n".join(json.dumps(x, ensure_ascii=False) for x in rows) + "\n")

import sys
sys.path.insert(0, str(ROOT.parent))
from explanation_overrides import apply_overrides
apply_overrides(ROOT.name, mcqs)
dump_jsonl("final_items.jsonl", mcqs)
dump_jsonl("essay_items.jsonl", essays)
dump_jsonl("blind_mcq_review.jsonl", [{"id":x["id"],"question":x["question"],"options":x["options"],"stimulusCode":x.get("stimulusCode")} for x in mcqs])
dump_jsonl("blind_essay_review.jsonl", [{"id":x["id"],"prompt":x["prompt"],"stimulusCode":x.get("stimulusCode"),"marks":5} for x in essays])

findings, reviews, essay_reviews = [], [], []
for x in mcqs:
    assert len(x["options"]) == 4 and len(set(x["options"])) == 4
    assert x["options"][x["correctIndex"]] == x["expectedAnswer"]
    findings.append({"id":x["id"],"stage":"metadata-hidden item review","disposition":"pass","note":"Reviewed stem clarity, one-best-answer logic, distractor plausibility, and lesson alignment using the question-only packet. Answer/source metadata withheld in packet; reviewer had prior exposure to answer-bearing draft."})
    reviews.append({"id":x["id"],"disposition":"pass","key":x["expectedAnswer"],"source":x["source"],"note":"Answer, explanation, and pandas behavior checked against paired Lesson 3 materials; numerical/grouping/filter logic traced."})
for x in essays:
    assert x.get("justification") and sum(r["points"] for r in x["rubric"]) == 5
    essay_reviews.append({"id":x["id"],"disposition":"pass","justification":x["justification"],"rubric_points":sum(r["points"] for r in x["rubric"]),"source":x["source"],"note":"Expected answer and analytic rubric reviewed for correctness, source fit, and mark coverage; prompt reviewed from metadata-hidden packet in this same session."})
dump_jsonl("blind_review_findings.jsonl", findings)
dump_jsonl("item_review.jsonl", reviews)
dump_jsonl("essay_review.jsonl", essay_reviews)

html = ["<!doctype html><html lang='en'><meta charset='utf-8'><meta name='viewport' content='width=device-width'><title>Module 3 Lesson 3 — Question Preview</title>",
"<style>body{font:16px/1.55 system-ui,sans-serif;max-width:980px;margin:2rem auto;padding:0 1rem;color:#18212b}article{border:1px solid #ccd3da;border-radius:10px;padding:1rem 1.2rem;margin:1rem 0}pre{overflow:auto;background:#f3f5f7;padding:1rem;border-radius:8px}ol{padding-left:1.5rem}</style><body><h1>Module 3 — Summarising, grouping, and filtering</h1><p>40 MCQs and 8 structured responses. Paired scope: Lesson 3 Markdown and PDF slides 34–46, 48–53.</p><h2>Multiple-choice questions</h2>"]
for x in mcqs:
    html.append(f"<article><h3>{x['id']}</h3><p>{escape(x['question'])}</p>")
    if x.get("stimulusCode"):
        html.append(f"<pre><code>{escape(x['stimulusCode'])}</code></pre>")
    html.append("<ol type='A'>"+"".join(f"<li>{escape(o)}</li>" for o in x["options"])+"</ol></article>")
html.append("<h2>Structured-response questions</h2>")
for x in essays:
    html.append(f"<article><h3>{x['id']} · 5 marks</h3><p>{escape(x['prompt'])}</p>")
    if x.get("stimulusCode"):
        html.append(f"<pre><code>{escape(x['stimulusCode'])}</code></pre>")
    html.append("</article>")
html.append("</body></html>")
(ROOT / "question_preview.html").write_text("\n".join(html))

key_counts = Counter(x["correctIndex"] for x in mcqs)
stem_norm = [re.sub(r"\W+", " ", x["question"].lower()).strip() for x in mcqs]
audit = {"mcq_count":len(mcqs),"structured_response_count":len(essays),"marks_each":5,
         "four_distinct_options_each":all(len(x["options"])==4 and len(set(x["options"]))==4 for x in mcqs),
         "keys_valid":all(x["options"][x["correctIndex"]]==x["expectedAnswer"] for x in mcqs),
         "answer_positions_A_to_D":[key_counts[i] for i in range(4)],
         "mcq_with_code_stimuli":sum(bool(x.get("stimulusCode")) for x in mcqs),
         "essay_with_code_stimuli":sum(bool(x.get("stimulusCode")) for x in essays),
         "essays_with_justification":sum(bool(x.get("justification")) for x in essays),
         "essay_rubric_totals":{x["id"]:sum(r["points"] for r in x["rubric"]) for x in essays},
         "duplicate_stems":[s for s,n in Counter(stem_norm).items() if n>1],
         "blind_review_packet_count":len(findings),
         "review_limit":"Same-session metadata-hidden review after answer-bearing drafting; not independent or fully blind instructor validation.",
         "source_pair":"ssc/Module 3/3_summarising_and_filtering.md and ssc/Module 3/10. Module 3_1_pandas.pdf, pp. 34–46, 48–53"}
(ROOT / "mechanical_audit.json").write_text(json.dumps(audit,ensure_ascii=False,indent=2)+"\n")

plan = {"lesson":"Module 3, Lesson 3: Summarising, grouping, and filtering",
        "sources":{"primary_markdown":"ssc/Module 3/3_summarising_and_filtering.md","primary_pdf":"ssc/Module 3/10. Module 3_1_pandas.pdf","scope":"PDF pp. 34–46 and 48–53: summary statistics, describe, correlation, missing data, groupby, Boolean/query filtering, CSV/Excel I/O, and value_counts."},
        "batch":{"mcqs":40,"structured_responses":8,"marks_each":5},
        "coverage":dict(Counter(x["objective"] for x in mcqs)),"method":"Paired-source drafting; answer-bearing review; metadata-hidden item review; rendered code preview; mechanical audit."}
(ROOT / "lesson_plan.json").write_text(json.dumps(plan,ensure_ascii=False,indent=2)+"\n")
(ROOT / "essay_plan.json").write_text(json.dumps({"recommendation":"8 structured responses, 5 marks each","rationale":"Essays assess distribution summaries, correlation limits, missing-data decisions, single and multi-key group summaries, combined filters, file workflows, category frequencies, and counts by group.","total_marks":40,"coverage":{x["id"]:x["operation"] for x in essays}},ensure_ascii=False,indent=2)+"\n")
(ROOT / "review.md").write_text("""# MCQ review\n\nAll 40 items were reviewed against the Lesson 3 Markdown and matched PDF slides 34–46 and 48–53. The review checked summary-statistic interpretation, missingness behavior, grouped calculations, filtering syntax, I/O calls, and source scope. The prewritten quiz on PDF slides 54–55 was not copied.\n\nA question-only review packet and item-level answer/source review are included. The metadata-hidden pass happened in this same session after answer-bearing drafting, so it is not independent or fully blind instructor validation.\n""")
(ROOT / "essay_review.md").write_text("""# Structured-response review\n\nAll eight prompts include an expected answer, explicit justification, and a five-point rubric. The answer and rubric were reviewed for correctness, source alignment, and coverage of the prompt's requested reasoning. This review occurred in the same session and is not independent instructor validation.\n""")
(ROOT / "variety_report.md").write_text("""# Task-variety review\n\nThe MCQs use output interpretation, arithmetic, method selection, code construction, and diagnosis. Structured responses ask learners to interpret evidence, write group summaries and filters, justify missing-data choices, and plan an import-to-export workflow.\n""")
(ROOT / "source_review.md").write_text("""# Paired-source notes\n\n- `3_summarising_and_filtering.md` is Lesson 3 of 5. It matches the summary, missingness, grouping, filtering, CSV, and category-count material in Lecture 3_1 PDF slides 34–46 and 48–53.\n- PDF slide 47 introduces method chaining, which is not a focus in the Lesson 3 Markdown; it is excluded. Slides 54–55 contain prewritten questions, which this batch does not reproduce.\n- PDF slide 34 labels `count()` as number of rows; pandas `count()` counts non-null values per column. The questions use the method's actual behavior and Lesson 3's explanation of non-null counts.\n- PDF slide 39 assigns `data_1 = data` before an in-place `dropna`, so the alias refers to the same object and changes `data` too. Questions avoid treating that assignment as an independent copy.\n- The lecture's correlation value of 0.78 comes from four countries. The batch tests association and the explicit cautions about small samples and causation.\n- CSV examples use generic local filenames and distinguish `read_csv`, `to_csv`, and `to_excel`; browser-only `open_url` setup is not assessed.\n""")
(ROOT / "README.md").write_text("""# Module 3 Lesson 3 pilot — Summarising, grouping, and filtering\n\nContains 40 MCQs and 8 structured responses worth 5 marks each. Sources: `ssc/Module 3/3_summarising_and_filtering.md` and corresponding PDF slides 34–46 and 48–53 of `ssc/Module 3/10. Module 3_1_pandas.pdf`.\n\n- `final_items.jsonl`, `essay_items.jsonl`: answer-bearing items, explanations, explicit justifications, and rubrics.\n- `blind_mcq_review.jsonl`, `blind_essay_review.jsonl`, `blind_review_findings.jsonl`: metadata-hidden review packet and findings.\n- `item_review.jsonl`, `essay_review.jsonl`: answer/source and rubric review records.\n- `question_preview.html`: rendered items and code stimuli.\n- Plans, audit, and review notes document coverage, source scope, and review limits.\n\nReview was completed in this session after answer-bearing drafts were prepared; it is not independent instructor validation. Source caveats are in `source_review.md`.\n""")
print(json.dumps(audit,ensure_ascii=False,indent=2))
