import json
import os
import re
from collections import Counter
from html import escape
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/thanaweya-matplotlib-config")
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

ROOT = Path(__file__).parent
CHARTS = ROOT / "charts"
CHARTS.mkdir(exist_ok=True)
DATA = pd.read_csv(ROOT / "source_data" / "titanic.csv")
FIELDS = ["sex", "age", "pclass", "survived", "fare"]
selected = DATA[FIELDS]
age_complete = selected.dropna(subset=["age"])
clean = age_complete.drop_duplicates().copy()
PALETTE = ["#3977b8", "#e18b3a", "#4b9b70", "#9564a6"]
plt.rcParams["svg.fonttype"] = "none"

def save(fig, name, subtitle=""):
    if subtitle:
        fig.text(.5, .96, subtitle, ha="center", va="top", fontsize=9, color="#52647a")
        fig.tight_layout(rect=(0, 0, 1, .93))
    else:
        fig.tight_layout()
    fig.savefig(CHARTS / name, format="svg", bbox_inches="tight")
    preview_dir = Path("/tmp/thanaweya-titanic-preview")
    preview_dir.mkdir(exist_ok=True)
    fig.savefig(preview_dir / name.replace(".svg", ".png"), format="png", dpi=100, bbox_inches="tight")
    plt.close(fig)

# The charts below use the source records and the exact cleaning sequence taught.
fig, ax = plt.subplots(figsize=(8.8, 5.1))
pd.Series({"All rows": len(DATA), "Age recorded": len(age_complete), "After duplicate removal": len(clean)}).plot.bar(ax=ax, color=PALETTE[0], edgecolor="white")
ax.set_title("Rows retained through the lesson's cleaning steps", pad=15)
ax.set_ylabel("Rows"); ax.set_xlabel(""); ax.tick_params(axis="x", rotation=0)
for container in ax.containers: ax.bar_label(container, padding=3)
save(fig, "cleaning_flow.svg", "The last step treats identical values in the five selected fields as duplicates")

fig, ax = plt.subplots(figsize=(8.8, 5.1))
clean["age"].plot.hist(bins=20, ax=ax, color=PALETTE[0], edgecolor="white")
ax.set_title("Age distribution after cleaning", pad=15); ax.set_xlabel("Age (years)"); ax.set_ylabel("Frequency")
save(fig, "age_histogram.svg", "n = 670 passengers with recorded age after selected-field duplicate removal")

fig, ax = plt.subplots(figsize=(8.8, 5.1))
clean.plot.scatter(x="age", y="fare", ax=ax, alpha=.48, s=28, color=PALETTE[0])
ax.set_title("Passenger age versus fare", pad=15); ax.set_xlabel("Age (years)"); ax.set_ylabel("Fare")
save(fig, "age_fare_scatter.svg", "The plot shows association in the cleaned sample, not cause")

class_counts = clean["pclass"].value_counts().sort_index()
fig, ax = plt.subplots(figsize=(8.2, 5.1))
class_counts.plot.bar(ax=ax, color=PALETTE[0], edgecolor="white", rot=0)
ax.set_title("Passenger counts by class", pad=15); ax.set_xlabel("Passenger class"); ax.set_ylabel("Passengers")
for container in ax.containers: ax.bar_label(container, padding=3)
save(fig, "passenger_counts_by_class.svg", "Counts are for the cleaned 670-row sample")

sex_rates = pd.crosstab(clean["sex"], clean["survived"], normalize="index").rename(columns={0:"Did not survive", 1:"Survived"})
fig, ax = plt.subplots(figsize=(8.2, 5.1))
sex_rates.plot.bar(stacked=True, ax=ax, color=[PALETTE[1], PALETTE[2]], edgecolor="white", rot=0)
ax.set_title("Survival proportions by sex", pad=15); ax.set_xlabel("Sex"); ax.set_ylabel("Share within each sex"); ax.set_ylim(0, 1)
ax.legend(title="Outcome", bbox_to_anchor=(1.02, 1), loc="upper left", frameon=False)
save(fig, "survival_by_sex.svg", "Each bar totals 100%; rates describe this cleaned sample")

class_rates = pd.crosstab(clean["pclass"], clean["survived"], normalize="index").rename(columns={0:"Did not survive", 1:"Survived"})
fig, ax = plt.subplots(figsize=(8.2, 5.1))
class_rates.plot.bar(stacked=True, ax=ax, color=[PALETTE[1], PALETTE[2]], edgecolor="white", rot=0)
ax.set_title("Survival proportions by passenger class", pad=15); ax.set_xlabel("Passenger class"); ax.set_ylabel("Share within each class"); ax.set_ylim(0, 1)
ax.legend(title="Outcome", bbox_to_anchor=(1.02, 1), loc="upper left", frameon=False)
save(fig, "survival_by_class.svg", "Each bar totals 100%; rates describe this cleaned sample")

fig, ax = plt.subplots(figsize=(8.8, 5.1))
clean.boxplot(column="fare", by="survived", sym="", ax=ax, grid=True, patch_artist=True,
              boxprops={"facecolor":"#86b7d8", "edgecolor":"#25364a"}, medianprops={"color":"#d45b4b", "linewidth":2})
fig.suptitle(""); ax.set_title("Fare distribution by survival outcome", pad=15)
ax.set_xlabel("Survived (0 = no, 1 = yes)"); ax.set_ylabel("Fare")
save(fig, "fare_boxplot_by_survival.svg", "The lesson hides outlier points; the plotted sample is cleaned")

interaction = clean.groupby(["sex", "pclass"])["survived"].mean().unstack()
fig, ax = plt.subplots(figsize=(8.8, 5.1))
interaction.plot.bar(ax=ax, color=PALETTE[:3], edgecolor="white", rot=0)
ax.set_title("Survival proportion by sex and class", pad=15); ax.set_xlabel("Sex"); ax.set_ylabel("Survival proportion"); ax.set_ylim(0, 1)
ax.legend(title="Passenger class", frameon=False)
save(fig, "survival_by_sex_and_class.svg", "Small groups need their counts read alongside their rates")

missing_by_class = DATA.groupby("pclass")["age"].apply(lambda x: x.isna().mean()).sort_index().mul(100)
fig, ax = plt.subplots(figsize=(8.2, 5.1))
missing_by_class.plot.bar(ax=ax, color=PALETTE[3], edgecolor="white", rot=0)
ax.set_title("Share of ages missing by passenger class", pad=15); ax.set_xlabel("Passenger class"); ax.set_ylabel("Age missing (%)")
for container in ax.containers: ax.bar_label(container, fmt="%.1f%%", padding=3)
save(fig, "missing_age_by_class.svg", "Calculated before dropping passengers with missing age")

group_sizes = clean.groupby(["sex", "pclass"]).size().unstack()
fig, ax = plt.subplots(figsize=(7.8, 4.5))
group_sizes.plot.bar(ax=ax, color=PALETTE[:3], edgecolor="white", rot=0)
ax.set_title("Passenger counts by sex and class", pad=15); ax.set_xlabel("Sex"); ax.set_ylabel("Passengers")
ax.legend(title="Passenger class", frameon=False)
for container in ax.containers: ax.bar_label(container, padding=2)
save(fig, "group_sizes_by_sex_class.svg", "Counts help judge how stable each displayed rate may be")

raw = [
 ("Which library is used in the lesson to load its example Titanic dataset?", "Seaborn", ["Matplotlib", "NumPy", "Bokeh"], "The PDF loads the built-in sample with `sns.load_dataset('titanic')`; the Markdown uses the course-hosted CSV copy.", 61, "load the lesson dataset", "identify the dataset provider", None, None, None),
 ("What does `df.shape` report for the full Titanic table in the lesson?", "891 rows and 15 columns", ["714 rows and 5 columns", "670 rows and 15 columns", "891 rows and 5 columns"], "The full table has 891 records and 15 fields before selecting or cleaning columns.", 62, "inspect dataset dimensions", "read shape", None, None, None),
 ("Which pair of calls previews records and reports column types and non-null counts?", "`df.head()` and `df.info()`", ["`df.describe()` and `df.mean()`", "`df.value_counts()` and `df.corr()`", "`df.plot()` and `df.shape`"], "The lesson uses `info()` for structure and `head()` for a first look at records.", 62, "inspect a DataFrame", "choose inspection methods", None, None, None),
 ("Which five variables does the lesson retain for its focused analysis?", "sex, age, pclass, survived, and fare", ["sex, age, cabin, ticket, and embarked", "name, age, fare, deck, and alive", "pclass, sibsp, parch, deck, and class"], "The lesson selects `sex`, `age`, `pclass`, `survived`, and `fare` from the larger table.", 61, "select analysis variables", "identify selected columns", None, None, None),
 ("What does `df_cleaned.isnull().sum()` help identify?", "The number of missing values in each selected column", ["The number of duplicate rows in every column", "The mean of each numerical column", "The number of survivors by class"], "`isnull()` marks missing entries and `sum()` counts them column by column.", 62, "inspect missingness", "interpret a missingness summary", None, None, None),
 ("After selecting the five fields, which step produces the 714-row table?", "Drop rows with missing `age`", ["Drop all rows with any repeated value", "Keep only first-class passengers", "Remove passengers who did not survive"], "Dropping rows with missing age reduces the selected table from 891 to 714 rows.", 62, "clean missing data", "trace the row count", "charts/cleaning_flow.svg", "Bar chart showing 891 full rows, 714 after missing-age removal, and 670 after duplicate removal.", None),
 ("How many rows does the lesson report after removing duplicate rows from the 714 age-complete records?", "670", ["891", "714", "44"], "The lesson reports 44 duplicate signatures among the selected fields and 670 rows after `drop_duplicates()`.", 62, "remove duplicate records", "read a cleaning result", "charts/cleaning_flow.svg", "Bar chart showing 891 full rows, 714 after missing-age removal, and 670 after duplicate removal.", None),
 ("Two passengers match on all five selected fields. What is the lesson's key caution before treating them as the same person?", "Distinct passengers can have identical values on the fields being compared", ["Pandas cannot compare rows for equality", "A duplicate row proves one passenger survived twice", "A matching fare means their ages must be missing"], "The same sex, age, class, outcome, and fare can belong to two different people; identical selected values do not establish identity.", 62, "evaluate duplicate removal", "recognize a false-duplicate risk", None, None, None),
 ("Which statement best describes the 670-row analysis table?", "It contains passengers with recorded age after duplicate removal on the five selected fields", ["It contains every passenger from the original table", "It contains only people who survived", "It contains all 714 age-complete rows"], "The stated cleaning steps restrict later results to age-recorded rows and remove selected-field duplicates.", 62, "describe the analysis population", "identify scope after cleaning", None, None, None),
 ("About what percentage of the original 891 rows remains after the lesson's two row-removal steps?", "75.2%", ["19.9%", "24.8%", "80.1%"], "670 divided by 891 is about 75.2%; this is a retention share, not a survival rate.", 62, "quantify cleaning cost", "calculate retained proportion", "charts/cleaning_flow.svg", "Bar chart showing 891 full rows, 714 after missing-age removal, and 670 after duplicate removal.", None),
 ("In `df_cleaned['age'].describe()`, which statistic is shown at `50%`?", "The median age", ["The mean age", "The maximum age", "The number of unique ages"], "The 50th percentile is the median.", 63, "read numerical summaries", "identify a percentile", None, None, None),
 ("What is the median age in the lesson's cleaned 670-row sample?", "28.25 years", ["29.82 years", "20 years", "39 years"], "The `describe()` output gives a 50th percentile (median) of 28.25 years; 29.82 is the mean.", 63, "interpret age summary statistics", "read the median", None, None, None),
 ("Which variable is treated as numerical in the lesson's descriptive-statistics step?", "age", ["sex", "pclass", "survived"], "The lesson uses `age.describe()` as its numerical summary and counts sex and class as categorical variables.", 63, "classify variables", "identify a numerical field", None, None, None),
 ("What does `df_cleaned['sex'].value_counts()` produce?", "The number of retained records in each sex category", ["The survival proportion within each sex", "The mean age for each sex", "The percentage of missing ages by sex"], "`value_counts()` counts category occurrences; a normalized crosstab is used for within-category survival proportions.", 63, "summarize categories", "interpret value_counts", None, None, None),
 ("After age and duplicate cleaning, how many third-class passengers are in the sample?", "331", ["155", "184", "491"], "Sorting the cleaned class counts by class gives 184 first-class, 155 second-class, and 331 third-class passengers.", 63, "read category counts", "read a frequency table", "charts/passenger_counts_by_class.svg", "Bar chart showing 184 class 1, 155 class 2, and 331 class 3 passengers in the cleaned sample.", None),
 ("How does the lesson calculate the overall survival rate from a 0/1 `survived` column?", "Take the mean of `survived` and convert it to a percentage", ["Count the number of unique `survived` values", "Divide the mean age by the row count", "Use `value_counts()` without selecting an outcome"], "For a binary 0/1 column, its mean is the proportion of 1s; multiplying by 100 expresses it as a percentage.", 63, "calculate a binary rate", "interpret a binary mean", None, None, None),
 ("Which pair of variable types is appropriate for the lesson's survival crosstab?", "A categorical grouping variable and the categorical/binary survival outcome", ["Two numerical measurements only", "A date and a continuous time series", "A numerical distribution and its histogram bins"], "The crosstab counts combinations of categories, such as sex with survived or class with survived.", 64, "cross-tabulate categories", "choose crosstab variables", None, None, None),
 ("In `pd.crosstab(group, survived, normalize='index')`, what does each row represent?", "Outcome proportions within one value of `group`", ["Outcome proportions across the entire dataset", "Counts divided by the number of columns", "A mean for each numerical field"], "`normalize='index'` divides each row by its own total, yielding within-group proportions.", 64, "normalize a crosstab", "interpret row normalization", "charts/survival_by_sex.svg", "100%-stacked bars show within-sex survival proportions; each sex bar totals 100%.", None),
 ("In the cleaned sample, approximately what share of women survived?", "75%", ["22%", "50%", "96%"], "The lesson's row-normalized sex crosstab gives about 75% survival for women in this cleaned sample.", 64, "interpret survival by sex", "read a row percentage", "charts/survival_by_sex.svg", "100%-stacked bars show 75% survival among women and 22% among men in the cleaned sample." , None),
 ("The cleaned-sample survival rates are about 75% for women and 22% for men. What is a careful numerical description?", "The women's observed rate is a little over three times the men's rate", ["The rates differ by exactly 75 percentage points", "The data prove sex alone caused the outcome", "The men's rate is three times the women's rate"], "75 divided by 22 is about 3.4; this describes a ratio of observed rates, not a causal effect.", 64, "compare observed rates", "compare proportions without causal overclaim", "charts/survival_by_sex.svg", "100%-stacked bars show 75% survival among women and 22% among men in the cleaned sample.", None),
 ("Which cleaned-sample survival proportions by passenger class match the lesson, in class order 1, 2, 3?", "66%, 50%, 25%", ["25%, 50%, 66%", "96%, 91%, 45%", "40%, 17%, 16%"], "The normalized class crosstab gives about 66% for first, 50% for second, and 25% for third class.", 64, "interpret survival by class", "read row percentages", "charts/survival_by_class.svg", "100%-stacked bars show 66%, 50%, and 25% survival in classes 1, 2, and 3.", None),
 ("A 100%-stacked bar chart is used for the survival crosstabs. What does that normalization make easy to compare?", "Outcome proportions across groups with different sizes", ["Absolute passenger counts in each group", "The order of individual passengers", "Missing ages in every original row"], "Every bar is normalized to 100%, so readers can compare within-group proportions even when group sizes differ.", 65, "interpret normalized stacked bars", "explain proportion comparison", "charts/survival_by_class.svg", "100%-stacked bars show 66%, 50%, and 25% survival in classes 1, 2, and 3.", None),
 ("Why do the lesson's class counts use `.sort_index()` before plotting?", "To show class labels in their meaningful order 1, 2, 3", ["To remove missing ages", "To sort passengers by fare", "To change frequency counts into rates"], "`value_counts()` sorts by frequency; `sort_index()` restores the natural numeric class order.", 65, "order categories for display", "explain sort_index", "charts/passenger_counts_by_class.svg", "Bar chart displays passenger classes in natural order 1, 2, 3, with counts 184, 155, and 331.", None),
 ("What does a histogram of `age` with `bins=20` show?", "How the recorded ages are distributed across 20 intervals", ["Survival rates across 20 passenger classes", "The relationship between age and fare", "The exact age of each passenger in row order"], "A histogram bins one numerical variable and displays the frequency in each interval.", 65, "visualize a numerical distribution", "identify histogram purpose", "charts/age_histogram.svg", "Histogram of age for 670 cleaned records with recorded age, using 20 bins.", None),
 ("What is the correct reading of the lesson's age-versus-fare scatter plot?", "It displays paired age and fare values to inspect whether the numerical variables vary together", ["It compares survival composition by class", "It bins ages and counts each interval", "It reports the median fare for each survival group"], "A scatter plot places two numerical variables on paired axes; the lesson notes the relationship is weak.", 65, "interpret a scatter plot", "identify variables and purpose", "charts/age_fare_scatter.svg", "Scatter plot of age and fare for the 670-row cleaned sample; no strong age-fare pattern is apparent.", None),
 ("Which conclusion should a student avoid drawing from an age–fare scatter plot alone?", "That age caused a passenger to pay a particular fare", ["That each point represents paired numerical values", "That fare varies among passengers", "That the plot is a visual summary of two fields"], "A descriptive scatter plot shows association and variation, not a causal mechanism.", 65, "interpret a relationship cautiously", "avoid causal overclaim", "charts/age_fare_scatter.svg", "Scatter plot of age and fare for the 670-row cleaned sample; no strong age-fare pattern is apparent.", None),
 ("Why can a few high fares make most points in an age–fare scatter plot look compressed near the bottom?", "The fare axis must span the unusually large values too", ["The scatter plot removes low fares", "The age variable is categorical", "The points are normalized to 100%"], "A wide fare range expands the vertical scale and compresses the visual spacing among lower fares.", 65, "read scatterplot scale effects", "explain visual compression", "charts/age_fare_scatter.svg", "Scatter plot includes a small number of very high fares that stretch the vertical scale.", None),
 ("In the fare box plot, which outcome group has the higher median fare?", "Passengers recorded as surviving", ["Passengers recorded as not surviving", "Both medians are exactly equal", "The plot has no median"], "The median fare is higher in the survived group in the cleaned sample.", 65, "interpret a box plot", "compare medians", "charts/fare_boxplot_by_survival.svg", "Fare box plot grouped by survived 0 or 1; the median for 1 is higher, with overlapping distributions.", None),
 ("What does the fare box plot show beyond the difference between the medians?", "The two fare distributions overlap", ["Every survivor paid more than every non-survivor", "Fare is recorded only for survivors", "The groups have identical ranges and quartiles"], "The boxes and whiskers overlap; a difference in medians does not separate every passenger into distinct fare ranges.", 65, "interpret distribution overlap", "avoid individual-level overclaim", "charts/fare_boxplot_by_survival.svg", "Fare box plot grouped by survived 0 or 1; the median for 1 is higher, with overlapping distributions.", None),
 ("What does `df_cleaned.boxplot(column='fare', by='survived', sym='')` do in the lesson?", "Compares fare distributions across survival groups while hiding outlier markers", ["Removes every passenger with an unusual fare", "Plots survival proportions as stacked bars", "Calculates a fare mean for each class"], "The lesson says `sym=''` suppresses displayed outlier points; it does not remove those records from the data.", 65, "read boxplot code", "interpret a plotting parameter", None, None, "df_cleaned.boxplot(column='fare', by='survived', sym='')"),
 ("In the two-variable grouping, what does `groupby(['sex', 'pclass'])['survived'].mean()` summarize?", "The observed survival proportion for each sex-and-class group", ["The number of missing ages for each sex", "The average fare across every class combined", "The 20-bin age histogram by group"], "The mean of the binary outcome within each combined category is that group's survival proportion.", 66, "group by multiple categories", "interpret grouped binary mean", "charts/survival_by_sex_and_class.svg", "Grouped bars show survival proportion by sex and passenger class for the cleaned sample.", None),
 ("In the cleaned sample, which displayed sex-and-class group has the highest survival proportion?", "First-class women, about 96%", ["Third-class men, about 16%", "Second-class men, about 17%", "Third-class women, about 45%"], "The combined summary gives the highest rate for first-class women, near 0.96.", 66, "interpret a two-factor summary", "identify the largest subgroup rate", "charts/survival_by_sex_and_class.svg", "Grouped bars show survival proportion by sex and passenger class for the cleaned sample.", None),
 ("Which sex-and-class cell has the largest count in the cleaned sample?", "Men in third class, 231", ["Women in third class, 100", "Men in first class, 100", "Women in first class, 84"], "The size table shows 231 men in third class, the largest of the six cells.", 66, "read group sizes", "identify the largest cell", "charts/group_sizes_by_sex_class.svg", "Grouped bars show the six sex-by-class counts; the largest is 231 men in class 3.", None),
 ("Why does the lesson print group sizes next to rates in the combined analysis?", "A rate from a very small cell can be unstable despite having precise-looking decimals", ["Group sizes convert the rate into a median", "Rates cannot be calculated without group sizes", "Small groups always have a survival rate of zero"], "The lesson warns that rates based on few passengers are less reliable and that the denominator should be visible.", 66, "qualify subgroup rates", "explain the value of denominators", "charts/group_sizes_by_sex_class.svg", "Grouped bars show passenger counts for each sex-by-class rate group.", None),
 ("The cleaned sample's average fare is higher among survivors. What does that comparison establish by itself?", "A descriptive difference in this cleaned sample, not that fare caused survival", ["That fare alone determined every outcome", "That the sample represents every passenger with recorded age", "That all survivors paid more than all non-survivors"], "Group means describe an observed difference; they do not isolate causal effects or describe all individual values.", 66, "interpret grouped means", "qualify a descriptive comparison", "charts/fare_boxplot_by_survival.svg", "Fare distributions overlap even though the survived group's mean and median fares are higher.", None),
 ("Before dropping passengers with missing age, which class has the largest share of ages missing?", "Third class", ["First class", "Second class", "All three classes have the same missing share"], "Missing age is about 27.7% in class 3, compared with 13.9% in class 1 and 6.0% in class 2.", 62, "evaluate missingness patterns", "read group-specific missingness", "charts/missing_age_by_class.svg", "Before cleaning, age is missing for 13.9% in class 1, 6.0% in class 2, and 27.7% in class 3.", None),
 ("Why can dropping every row with missing age change the population represented by later results?", "Missing ages are concentrated differently across passenger classes, so the removed rows may not be representative", ["Dropping ages changes every recorded survival value", "All classes lose exactly the same share of rows", "Missing values are automatically replaced by the mean"], "Age missingness differs by class, so complete-age records may differ systematically from the original passenger table.", 62, "reason about missing-data bias", "explain a selection limitation", "charts/missing_age_by_class.svg", "Before cleaning, age is missing for 13.9% in class 1, 6.0% in class 2, and 27.7% in class 3.", None),
 ("Which write-up is best supported after the lesson's cleaning steps?", "Among passengers with recorded age retained after selected-field duplicate removal, the observed survival rates differed by sex and class", ["Sex and class alone caused the outcomes for every passenger", "The analysis includes every one of the original 891 passengers", "Removing duplicate rows proves the remaining observations are unique people"], "A sound report names the cleaned analysis population and describes associations without causal certainty.", 66, "communicate scope and findings", "write a qualified conclusion", None, None, None),
 ("Which order best matches the lesson's end-to-end exploratory analysis?", "Load and inspect, select and clean, describe, cross-tabulate, visualize, then examine groups together", ["Plot first, delete missing outcomes, fit a model, then inspect columns", "Remove all repeated values before deciding which fields matter, then infer causes", "Calculate correlations, discard small groups, and report only the highest rate"], "The lesson moves from load/inspect through cleaning, description, categorical relationships, plots, and two-factor grouping.", 67, "sequence an EDA workflow", "integrate lesson steps", None, None, None),
 ("What is the overall survival rate in the lesson's cleaned 670-row sample?", "About 41.9%", ["About 25.0%", "About 50.0%", "About 75.2%"], "There are 281 survivors among 670 cleaned rows; 281/670 is about 41.9%. The 75.2% figure is the share of original rows retained, not survival.", 63, "read overall survival", "calculate a binary outcome proportion", None, None, None),
]

essays = [
 {"prompt":"Describe the lesson's cleaning pipeline from the full table to the analysis table. Give the row counts at each stage, calculate the approximate percentage retained, and explain why the final results must be described as applying to a restricted sample.","expectedAnswer":"The full dataset has 891 rows and 15 columns. Selecting sex, age, pclass, survived, and fare keeps the row count at 891. Dropping rows with missing age leaves 714; dropping 44 duplicate patterns across the selected fields leaves 670. The final retention is 670/891, about 75.2%. Later summaries describe age-recorded rows after selected-field duplicate removal, not all original passengers; missingness and duplicate handling may affect who remains.","justification":"This response integrates the lesson's exact preprocessing sequence and requires students to account for the population change caused by those decisions.","rubric":[{"criterion":"States the original 891-row table and five selected fields", "points":1},{"criterion":"Gives 714 rows after dropping missing ages", "points":1},{"criterion":"Gives 670 rows after duplicate removal", "points":1},{"criterion":"Calculates approximately 75.2% retained", "points":1},{"criterion":"Qualifies the analysis population and cleaning limitation", "points":1}],"source":"5_titanic.md — Step 2; PDF p. 62","operation":"trace and critique cleaning decisions","stimulusAsset":"charts/cleaning_flow.svg","stimulusAssetAlt":"Bar chart showing the successive 891, 714, and 670 row totals."},
 {"prompt":"The lesson removes 44 duplicate rows after selecting five fields. Explain why matching values do not prove that two rows are the same passenger. Recommend a cautious next step and describe one way this decision could affect later summaries.","expectedAnswer":"Two distinct passengers can share sex, age, class, survival outcome, and fare, so equality on those five selected fields does not establish identity. Before dropping rows, inspect candidate duplicates and use a genuine record identifier or additional fields if available; otherwise retain them or document the assumption. Removing real passengers can change counts, rates, means, and subgroup sizes.","justification":"The prompt tests the lesson's explicit warning that the 44 repeated signatures may represent different people, not duplicate records in the real-world sense.","rubric":[{"criterion":"Explains that distinct passengers can match on selected fields", "points":1},{"criterion":"Distinguishes identical selected values from identity", "points":1},{"criterion":"Recommends reviewing candidates or using a true identifier", "points":1},{"criterion":"Notes that removal can change summaries or rates", "points":1},{"criterion":"States a transparent retention/documentation alternative", "points":1}],"source":"5_titanic.md — Step 2, duplicate-record caution; PDF p. 62","operation":"critique duplicate handling"},
 {"prompt":"Use the survival-by-sex and survival-by-class charts. Report the approximate survival proportion for women, men, and each passenger class. Explain how `normalize='index'` creates those proportions, then give one careful interpretation and one limitation.","expectedAnswer":"In the cleaned sample, about 75% of women and 22% of men survived. By class, about 66% of first, 50% of second, and 25% of third-class passengers survived. `normalize='index'` divides each outcome count by the total for that row/group, so each group sums to 100%. These are associations in the cleaned sample; they do not show that sex or class alone caused an individual outcome, and age-missing and duplicate filtering limit the scope.","justification":"The response reads the two central lesson figures, explains row normalization, and qualifies what the observed proportions can establish.","rubric":[{"criterion":"Reports female and male rates approximately correctly", "points":1},{"criterion":"Reports class rates approximately correctly", "points":1},{"criterion":"Explains row-wise normalization", "points":1},{"criterion":"Gives a non-causal interpretation", "points":1},{"criterion":"Names the cleaned-sample limitation", "points":1}],"source":"5_titanic.md — Step 4; PDF pp. 63–64","operation":"read and qualify categorical rates","stimulusAssets":["charts/survival_by_sex.svg","charts/survival_by_class.svg"],"stimulusAssetsAlt":["100%-stacked bars show 75% survival among women and 22% among men in the cleaned sample.","100%-stacked bars show 66%, 50%, and 25% survival in classes 1, 2, and 3."]},
 {"prompt":"A reader sees the passenger-count-by-class chart and the 100%-stacked survival-by-class chart. Explain the different question each chart answers, read one result from each, and explain why a 100%-stacked chart cannot compare the absolute class sizes.","expectedAnswer":"The count bar chart answers how many cleaned passengers are in each class: 184 in class 1, 155 in class 2, and 331 in class 3. The stacked chart answers how outcomes are composed within each class: survival is about 66%, 50%, and 25% for classes 1, 2, and 3. Since each stacked bar is rescaled to total 100%, it shows proportions and hides the original group totals; the count chart is needed for sizes.","justification":"This paired-chart response distinguishes marginal counts from within-group rates and checks the interpretation of normalization.","rubric":[{"criterion":"Explains the counts chart's purpose", "points":1},{"criterion":"Reads at least one class count accurately", "points":1},{"criterion":"Explains the stacked chart's within-class purpose", "points":1},{"criterion":"Reads a class survival share accurately", "points":1},{"criterion":"Explains that normalization hides absolute group size", "points":1}],"source":"5_titanic.md — Steps 4–5; PDF pp. 64–65","operation":"compare count and rate visualizations","stimulusAssets":["charts/passenger_counts_by_class.svg","charts/survival_by_class.svg"],"stimulusAssetsAlt":["Cleaned sample counts are 184, 155, and 331 for classes 1, 2, and 3.","100%-stacked bars show 66%, 50%, and 25% survival in classes 1, 2, and 3."]},
 {"prompt":"Interpret the survival-by-sex-and-class chart alongside the grouped count chart. Identify the highest and lowest observed rates, give their denominators, and explain why the counts belong beside the rates.","expectedAnswer":"First-class women have the highest observed rate, about 96%, among 84 passengers. Third-class men have the lowest, about 16%, among 231 passengers. The rate is a proportion within each sex/class cell; denominators show how many observations support it. A small cell can produce an unstable rate, so a precise-looking decimal should not be treated as equally reliable across groups. These remain descriptive results for the cleaned sample.","justification":"The prompt directly combines the lesson's two-factor rate table with its follow-up group-size table and caution about small cells.","rubric":[{"criterion":"Identifies first-class women as the highest-rate cell", "points":1},{"criterion":"Gives its denominator of 84", "points":1},{"criterion":"Identifies third-class men as the lowest-rate cell", "points":1},{"criterion":"Gives its denominator of 231", "points":1},{"criterion":"Explains why rates need group counts and cautious interpretation", "points":1}],"source":"5_titanic.md — Step 6; PDF p. 66","operation":"interpret subgroup rates with denominators","stimulusAssets":["charts/survival_by_sex_and_class.svg","charts/group_sizes_by_sex_class.svg"],"stimulusAssetsAlt":["Grouped bars show survival proportion by sex and passenger class for the cleaned sample.","Grouped count bars show the six sex-by-class sample sizes; the largest is 231 men in class 3."]},
 {"prompt":"Use the age histogram, age–fare scatter plot, and fare box plot to explain what each view contributes. State one result visible in the figures and two limits on what these plots can establish.","expectedAnswer":"The histogram displays the distribution of recorded ages; the scatter plot displays paired age and fare values and shows no strong age–fare relationship, with a few high fares stretching the scale; the box plot compares fare distributions by survival outcome and shows a higher median among survivors with substantial overlap. These are descriptive plots of the cleaned age-complete, deduplicated sample. They do not establish causation or imply that every survivor paid more; the box plot also hides individual points and uses `sym=''` to suppress outlier markers.","justification":"The response asks students to integrate the lesson's three distinct visual purposes while resisting causal and individual-level overclaims.","rubric":[{"criterion":"Explains histogram as one-variable age distribution", "points":1},{"criterion":"Explains scatter as paired numerical relationship", "points":1},{"criterion":"Explains box plot as fare-distribution comparison by outcome", "points":1},{"criterion":"States a correct visible pattern", "points":1},{"criterion":"Gives a valid limitation such as sample scope, causation, overlap, or hidden outliers", "points":1}],"source":"5_titanic.md — Step 5; PDF pp. 65–66","operation":"interpret complementary plots","stimulusAssets":["charts/age_histogram.svg","charts/age_fare_scatter.svg","charts/fare_boxplot_by_survival.svg"],"stimulusAssetsAlt":["Histogram of age for the 670 cleaned records with recorded age, using 20 bins.","Scatter plot of age and fare for the 670-row cleaned sample; no strong age-fare pattern is apparent.","Fare box plot grouped by survived 0 or 1; the median for 1 is higher, with overlapping distributions."]},
 {"prompt":"The lesson notes that age was missing more often for third-class passengers. Use the missing-age chart to quantify the pattern and explain why dropping all missing ages could make later results less representative. Suggest one sensitivity check that stays within the lesson's exploratory-analysis level.","expectedAnswer":"Before cleaning, age is missing for about 27.7% of third-class passengers, versus 13.9% of first-class and 6.0% of second-class passengers. Because missingness differs by class, the 714 complete-age rows may not reflect the original class mix; removing them can affect later class counts and survival summaries. A simple sensitivity check is to compare class/survival distributions before age removal with the age-complete subset, and clearly report the denominators. This does not recover unknown ages, but it shows how selection changes the summaries.","justification":"This response examines a concrete missingness pattern behind the lesson's warning that the retained analysis population may differ from all passengers.","rubric":[{"criterion":"Reads third-class missing-age share approximately", "points":1},{"criterion":"Compares with at least one other class correctly", "points":1},{"criterion":"Explains how differential missingness can alter representation", "points":1},{"criterion":"Suggests a relevant before/after descriptive check", "points":1},{"criterion":"States that the check does not recover missing ages", "points":1}],"source":"5_titanic.md — Step 2 missingness discussion; PDF p. 62","operation":"evaluate missingness and selection","stimulusAsset":"charts/missing_age_by_class.svg","stimulusAssetAlt":"Before cleaning, age is missing for 13.9% in class 1, 6.0% in class 2, and 27.7% in class 3."},
 {"prompt":"Plan the lesson's exploratory analysis for a new passenger-like CSV. Write a compact pandas workflow to load and inspect it, select fields, quantify and handle missing age, summarize numerical and categorical variables, compute survival proportions by two categorical fields, and create one appropriate plot. Include a sentence explaining how you would report the cost of cleaning.","expectedAnswer":"For example: `df = pd.read_csv('passengers.csv')`; inspect with `df.shape`, `df.info()`, and `df.head()`; select `df[['sex','age','pclass','survived','fare']]`; check `df.isnull().sum()`; then create a cleaned analysis table with `dropna(subset=['age'])` while documenting the removed rows. Use `age.describe()` and `sex.value_counts()`/`pclass.value_counts().sort_index()`. For survival proportions use `pd.crosstab(clean['pclass'], clean['survived'], normalize='index')`. Plot `clean['age'].plot.hist(bins=20)` or a suitable categorical comparison. Report the original and retained row counts and state that conclusions refer to the retained sample.","justification":"The task transfers the complete EDA sequence to a new dataset while requiring method choice, code, visualization, and transparent reporting of row loss.","rubric":[{"criterion":"Loads and inspects the DataFrame with suitable pandas methods", "points":1},{"criterion":"Selects relevant fields and checks missingness", "points":1},{"criterion":"Summarizes numerical and categorical fields appropriately", "points":1},{"criterion":"Writes a valid normalized crosstab or appropriate plotting call", "points":1},{"criterion":"Reports row loss and qualifies the analysis population", "points":1}],"source":"5_titanic.md — What you just did and Test your ability; PDF pp. 67–68","operation":"transfer the EDA workflow","stimulusCode":"df = pd.read_csv('passengers.csv')\nprint(df.shape)\ndf.info()\nclean = df[['sex', 'age', 'pclass', 'survived', 'fare']].dropna(subset=['age'])\nrates = pd.crosstab(clean['pclass'], clean['survived'], normalize='index')"},
]

if len(raw) != 40 or len(essays) != 8:
    raise ValueError(f"Expected 40 MCQs and 8 essays; got {len(raw)} and {len(essays)}")

positions = [0, 1, 2, 3] * 10
mcqs = []
for n, (q, answer, distractors, explanation, page, objective, operation, asset, alt, code) in enumerate(raw, 1):
    options = list(distractors)
    options.insert(positions[n-1], answer)
    item = {"id":f"M3L5-{n:03d}", "question":q, "options":options, "correctIndex":positions[n-1], "expectedAnswer":answer,
            "explanation":explanation, "source":f"5_titanic.md — {objective}; Module 3 Lecture 3_1 PDF p. {page}", "objective":objective, "operation":operation}
    if asset: item.update({"stimulusAsset":asset, "stimulusAssetAlt":alt})
    if code: item["stimulusCode"] = code
    mcqs.append(item)
for n, essay in enumerate(essays, 1):
    essay.update({"id":f"M3L5-E{n:02d}", "responseType":"structured response", "marks":5})

def dump_jsonl(name, rows):
    (ROOT / name).write_text("\n".join(json.dumps(x, ensure_ascii=False) for x in rows) + "\n")

def figures(item):
    if item.get("stimulusAsset"):
        return [(item["stimulusAsset"], item.get("stimulusAssetAlt", ""))]
    return list(zip(item.get("stimulusAssets", []), item.get("stimulusAssetsAlt", [])))

import sys
sys.path.insert(0, str(ROOT.parent))
from explanation_overrides import apply_overrides
apply_overrides(ROOT.name, mcqs)
dump_jsonl("final_items.jsonl", mcqs)
dump_jsonl("essay_items.jsonl", essays)
dump_jsonl("blind_mcq_review.jsonl", [{"id":x["id"],"question":x["question"],"options":x["options"],"stimulusAsset":x.get("stimulusAsset"),"stimulusAssetAlt":x.get("stimulusAssetAlt"),"stimulusCode":x.get("stimulusCode")} for x in mcqs])
dump_jsonl("blind_essay_review.jsonl", [{"id":x["id"],"prompt":x["prompt"],"stimulusAsset":x.get("stimulusAsset"),"stimulusAssetAlt":x.get("stimulusAssetAlt"),"stimulusAssets":x.get("stimulusAssets"),"stimulusAssetsAlt":x.get("stimulusAssetsAlt"),"stimulusCode":x.get("stimulusCode"),"marks":5} for x in essays])

html = ["<!doctype html><html lang='en'><meta charset='utf-8'><meta name='viewport' content='width=device-width'><title>Module 3 Lesson 5 — Titanic Case Study</title>",
"<style>body{font:16px/1.55 system-ui,sans-serif;max-width:1000px;margin:2rem auto;padding:0 1rem;color:#18212b}article{border:1px solid #ccd3da;border-radius:10px;padding:1rem 1.2rem;margin:1rem 0}figure{margin:1rem 0}img{display:block;max-width:100%;height:auto;margin:auto;border:1px solid #e1e5e9}figcaption{font-size:.88rem;color:#52647a;text-align:center}pre{overflow:auto;background:#f3f5f7;padding:1rem;border-radius:8px}ol{padding-left:1.5rem}</style><body><h1>Module 3 — Titanic case study</h1><p>40 MCQs and 8 structured responses. Figures use the lesson's Titanic dataset and cleaning steps. All rates shown after cleaning refer to the 670-row sample unless the caption states otherwise.</p><h2>Multiple-choice questions</h2>"]
for item in mcqs:
    html.append(f"<article><h3>{item['id']}</h3><p>{escape(item['question'])}</p>")
    for asset, alt in figures(item): html.append(f"<figure><img src='{escape(asset)}' alt='{escape(alt)}'><figcaption>{escape(alt)}</figcaption></figure>")
    if item.get("stimulusCode"): html.append(f"<pre><code>{escape(item['stimulusCode'])}</code></pre>")
    html.append("<ol type='A'>" + "".join(f"<li>{escape(o)}</li>" for o in item["options"]) + "</ol></article>")
html.append("<h2>Structured-response questions</h2>")
for item in essays:
    html.append(f"<article><h3>{item['id']} · 5 marks</h3><p>{escape(item['prompt'])}</p>")
    for asset, alt in figures(item): html.append(f"<figure><img src='{escape(asset)}' alt='{escape(alt)}'><figcaption>{escape(alt)}</figcaption></figure>")
    if item.get("stimulusCode"): html.append(f"<pre><code>{escape(item['stimulusCode'])}</code></pre>")
    html.append("</article>")
html.append("</body></html>")
(ROOT / "question_preview.html").write_text("\n".join(html))

# Mechanical checks; the authoring review is recorded separately and is not independent.
for item in mcqs:
    assert len(item["options"]) == 4 and len(set(item["options"])) == 4
    assert item["options"][item["correctIndex"]] == item["expectedAnswer"]
    for asset, _ in figures(item): assert (ROOT / asset).is_file(), (item["id"], asset)
for item in essays:
    assert item.get("justification") and sum(r["points"] for r in item["rubric"]) == 5
    assert len(item.get("stimulusAssets", [])) == len(item.get("stimulusAssetsAlt", []))
    for asset, _ in figures(item): assert (ROOT / asset).is_file(), (item["id"], asset)
keys = Counter(x["correctIndex"] for x in mcqs)
all_items = mcqs + essays
assets = {asset for item in all_items for asset, _ in figures(item)}
audit = {"mcq_count":len(mcqs),"essay_count":len(essays),"four_distinct_options_each":True,"keys_valid":True,
         "answer_positions_A_to_D":[keys[i] for i in range(4)],"unique_chart_assets":len(assets),
         "mcqs_with_visuals":sum(bool(figures(x)) for x in mcqs),"essays_with_visuals":sum(bool(figures(x)) for x in essays),
         "essay_justifications":sum(bool(x.get("justification")) for x in essays),"essay_rubric_totals":{x["id"]:sum(r["points"] for r in x["rubric"]) for x in essays},
         "preview_image_count":(ROOT/"question_preview.html").read_text().count("<img "),
         "review_status":"Authoring review completed and mechanical checks passed; no independent blind review performed.",
         "duplicate_stems":[s for s,n in Counter(re.sub(r"\W+"," ",x["question"].lower()).strip() for x in mcqs).items() if n>1]}
(ROOT / "mechanical_audit.json").write_text(json.dumps(audit, ensure_ascii=False, indent=2) + "\n")

renderers = {"cleaning_flow.svg":"pandas.Series.plot.bar / Matplotlib",
 "age_histogram.svg":"pandas.Series.plot.hist / Matplotlib", "age_fare_scatter.svg":"pandas.DataFrame.plot.scatter / Matplotlib",
 "passenger_counts_by_class.svg":"pandas.Series.plot.bar / Matplotlib", "survival_by_sex.svg":"pandas.DataFrame.plot.bar(stacked=True) / Matplotlib",
 "survival_by_class.svg":"pandas.DataFrame.plot.bar(stacked=True) / Matplotlib", "fare_boxplot_by_survival.svg":"pandas.DataFrame.boxplot / Matplotlib",
 "survival_by_sex_and_class.svg":"pandas.DataFrame.plot.bar / Matplotlib", "missing_age_by_class.svg":"pandas.Series.plot.bar / Matplotlib",
 "group_sizes_by_sex_class.svg":"pandas.DataFrame.plot.bar / Matplotlib"}
(CHARTS / "manifest.json").write_text(json.dumps({"note":"Figures plot the Seaborn Titanic sample after the lesson's selected-column, missing-age, and duplicate-removal steps unless stated otherwise. SVGs are rendered by the named course libraries.","renderers":renderers}, ensure_ascii=False, indent=2) + "\n")

(ROOT / "lesson_plan.json").write_text(json.dumps({"lesson":"Module 3, Lesson 5: Titanic case study","sources":{"markdown":"ssc/Module 3/5_titanic.md","pdf":"ssc/Module 3/10. Module 3_1_pandas.pdf, pp. 60–68","dataset":"Seaborn Titanic sample, copied from mwaskom/seaborn-data; source_data/titanic.csv"},"batch":{"mcqs":40,"structured_responses":8,"marks_each":5},"scope":"Load and inspect; select five fields; assess missingness and duplicates; describe numerical/categorical data; row-normalized crosstabs; actual dataset plots; combined sex/class rates and group sizes; qualify findings."}, ensure_ascii=False, indent=2) + "\n")
(ROOT / "essay_plan.json").write_text(json.dumps({"recommendation":"8 structured responses, 5 marks each","total_marks":40,"rationale":"This capstone lesson integrates data loading, cleaning, descriptive statistics, cross-tabulation, plotting, group analysis, and limitations.","coverage":{x["id"]:x["operation"] for x in essays}}, ensure_ascii=False, indent=2) + "\n")
(ROOT / "review.md").write_text("""# Review status\n\nThe authoring review checked all questions, keys, explanations, chart claims, and essay answers against the paired lesson sources and computed them against the exact CSV included in `source_data/`. It checked the 891 → 714 → 670 cleaning flow, all cited row-normalized rates, plotted subgroup counts, and the distinction between observed associations and causes. The review also checked that results are scoped to the cleaned sample and that equal selected fields are not described as proof of passenger identity.\n\nMechanical checks confirmed four distinct options per MCQ, valid keys, balanced answer positions, all visual files referenced by the preview, explicit essay justifications, and five marks per rubric. Question-only packets are included, but **no independent blind review has been performed**.\n""")
(ROOT / "essay_review.md").write_text("""# Structured-response review\n\nEach of the eight responses has an expected answer, explicit justification, and five-point analytic rubric. I reviewed each expected answer and rubric against the lesson, exact dataset results, and attached figures. This is an authoring review; an independent reviewer has not reviewed the essays.\n""")
(ROOT / "source_review.md").write_text("""# Paired-source notes\n\n- The Markdown `5_titanic.md` aligns with the capstone case study in Module 3 Lecture 3_1 PDF, pp. 60–68.\n- The PDF loads the Seaborn Titanic sample; the Markdown loads the course-hosted CSV copy. This package uses the Seaborn sample CSV in `source_data/titanic.csv`, consistent with the reported 891 rows and 15 columns.\n- The stated cleaning sequence is reproduced exactly: select sex, age, pclass, survived, fare; remove missing ages (891 → 714); remove duplicate rows among those five selected fields (714 → 670).\n- Survival rates and group counts in the items and figures were calculated from that 670-row table. Missing-age chart values are calculated from the full 891-row data before row removal.\n- The lesson itself warns that identical values on five fields do not establish that two real passengers are the same person. Items preserve that caution and avoid treating the 44 removals as verified identity duplicates.\n- Plots use pandas plotting with Matplotlib, for all charts, matching the course’s pandas plotting methods. All generated figures are SVG.\n""")
(ROOT / "variety_report.md").write_text("""# Visual and task variety

The package contains ten distinct SVG figures generated from the lesson's Titanic sample: a cleaning-flow bar chart, age histogram, age–fare scatter plot, passenger-class counts, survival proportions by sex and class, fare box plot, sex/class interaction rates, missing-age shares by class, and sex/class group counts. Every figure uses pandas plotting backed by Matplotlib, matching the plotting approach shown in the lesson. The preview attaches each visual to the questions that need it; alt text describes the data and sample scope.

Tasks cover code reading, dataset inspection, cleaning counts and risks, numerical/categorical summaries, row-normalized crosstabs, visual interpretation, subgroup denominators, and qualified reporting.
""")
(ROOT / "dataset_source.md").write_text("""# Dataset source\n\n`source_data/titanic.csv` is the 891-row, 15-column Titanic sample used by Seaborn's `load_dataset('titanic')`, retrieved from the Seaborn example-data repository on 2026-10-06. The lesson's Markdown accesses its course-hosted CSV; its PDF explicitly loads the sample through Seaborn.\n\nUpstream: https://github.com/mwaskom/seaborn-data/blob/master/titanic.csv\nRaw file: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv\n\nAll rates in this question bank are recomputed from the supplied source CSV using the lesson's selected fields and cleaning sequence.\n""")
(ROOT / "README.md").write_text("""# Module 3 Lesson 5 — Titanic case study\n\nContains 40 MCQs and 8 structured responses worth 5 marks each. The package pairs `ssc/Module 3/5_titanic.md` with the corresponding PDF pages 60–68. It includes the source CSV, ten figures rendered as SVG with pandas/Matplotlib, and a preview that embeds the figures in the questions.\n\n- `final_items.jsonl`, `essay_items.jsonl`: answer-bearing items with explanations, justifications, and rubrics.\n- `question_preview.html`: visual questions with the actual plotted figures.\n- `charts/manifest.json`: renderer for every chart asset.\n- `variety_report.md`: visual and task coverage.\n- `source_data/titanic.csv`, `dataset_source.md`: reproducible data input and provenance.\n- `blind_mcq_review.jsonl`, `blind_essay_review.jsonl`: question-only packets for independent review; no independent blind review is claimed.\n- `mechanical_audit.json`, `review.md`, `essay_review.md`, `source_review.md`, and plans: audit and source scope.\n\nData-dependent figures and keys use the lesson's exact cleaning sequence. Later results describe only the 670-row cleaned sample unless a question or chart explicitly says otherwise.\n""")
print(json.dumps(audit, ensure_ascii=False, indent=2))
