import json
from pathlib import Path

ROOT = Path(__file__).parent
raw = [
    ("A city project combines statistical analysis, software tools, and knowledge of local housing policy. What feature of this work makes it data science?", "It brings statistical, computational, and domain expertise together", ["It uses only machine-learning predictions", "It avoids interpreting the subject matter", "It replaces statistics with software"], "Data science is interdisciplinary: it combines statistics, computer science, and expertise about the field being studied.", "What is Data Science?", 4, "recognize interdisciplinary practice", None),
    ("Which example is unstructured data in the lesson's distinction?", "A collection of free-text interview responses", ["A table with one row per respondent", "A spreadsheet with labeled numeric columns", "A database table with fixed fields"], "Free text does not arrive in a predefined tabular row-and-column structure, while the other options do.", "What is Data Science?", 4, "distinguish structured and unstructured data", None),
    ("A research team cleans records, analyzes them, and presents evidence to help a ministry choose a policy. Which goal best describes the work?", "Use data to uncover insights and support decisions", ["Store information without interpreting it", "Produce predictions without considering a decision", "Replace domain knowledge with an algorithm"], "The stated goal of data science is to find patterns and insights that inform real decisions.", "What is Data Science?", 4, "apply the data science goal", None),
    ("A dataset contains duplicate records and inconsistent date formats. Which data science objective addresses this first?", "Data preparation", ["Advanced analytics", "Data visualization and communication", "Ethical considerations"], "Preparation restructures, cleans, and organizes data before analysis.", "Data Science Objectives", 4, "identify data preparation", None),
    ("An analyst turns a complex result into a clear chart and short narrative for community leaders. Which objective is this?", "Data visualization and communication", ["Data preparation", "Advanced analytics", "Model training"], "This objective presents findings through visual tools and clear narratives.", "Data Science Objectives", 4, "identify communication work", None),
    ("A team trains a model to find patterns in past cases and forecast future demand. Which objective does this most directly represent?", "Advanced analytics", ["Data preparation", "Data visualization and communication", "Ethical considerations"], "The lesson connects advanced analytics with machine learning, pattern discovery, and predictive models.", "Data Science Objectives", 4, "identify advanced analytics", None),
    ("Why does the lesson treat ethical considerations as a data science objective?", "Data collection and use can have social consequences", ["Ethics is needed only after a model is deployed", "Ethics removes the need to examine data quality", "Ethics is a plotting method for model results"], "The social implications of collecting, analyzing, and using data are part of the work itself.", "Why objective 4 is on the list", 4, "explain the role of ethics", None),
    ("A loan-default model is trained on past lending decisions that systematically excluded a community. What risk does the lesson highlight?", "The model may reproduce historical discrimination", ["The model automatically corrects historical decisions", "The model cannot learn from structured data", "The model becomes a rule-based expert system"], "A model can learn patterns in human decisions, including discriminatory patterns present in historical data.", "Why objective 4 is on the list", 4, "identify a historical-bias risk", None),
    ("Which description best fits machine learning as introduced in the lesson?", "Computers use patterns learned from data to make predictions or decisions", ["Programmers write every decision as a fixed rule", "Computers store data without finding relationships", "A statistical model is always specified before data are collected"], "Machine learning lets computers learn from data rather than relying only on explicitly written decision rules.", "What is Machine Learning?", 5, "define machine learning", None),
    ("A telecom company examines earlier customer records and learns that high bills combined with low usage often precede cancellation. What has it identified?", "A pattern relating variables to later churn", ["A guaranteed rule that applies to every customer", "A data visualization objective", "An expert system written only from IF/THEN rules"], "The lesson describes a pattern as a reliable relationship among variables, not a universal guarantee.", "Learning a pattern, not a rule", 6, "interpret a learned pattern", None),
    ("Why can a trained churn model be applied to a customer not present in its training records?", "It has learned a pattern intended to generalize to new cases", ["It memorized a human-written decision for every possible customer", "It can only describe the historical dataset", "The new customer's data are already part of the training table"], "The lesson describes applying learned patterns to new, unseen customers as generalization.", "What is Machine Learning?", 6, "explain generalization", None),
    ("What distinguishes a learned pattern from a pre-programmed sorting rule in the lesson's analogy?", "The pattern is inferred from historical examples rather than fully specified in advance", ["The pattern is a chart chosen by an analyst", "The rule is learned from examples, while a pattern is typed by a programmer", "There is no difference between the two"], "The lesson contrasts discovering relationships from data with following explicit rules written beforehand.", "What is Machine Learning?", 6, "compare learning and explicit rules", None),
    ("An analyst wants a system to apply a fixed policy: if an account is overdue by 60 days, flag it. No examples are used to learn the condition. Is that by itself machine learning?", "No; it is an explicitly programmed rule", ["Yes; every automated decision is machine learning", "Yes; using a computer makes it machine learning", "No; only a statistical chart can apply rules"], "A fixed IF/THEN condition does not learn its decision rule from data, even if it may be part of a broader AI system.", "Artificial Intelligence: The Big Picture", 7, "distinguish programmed rules from ML", None),
    ("A rule-based expert system makes recommendations from rules entered by specialists. How does the lesson classify it?", "It can be AI without being machine learning", ["It is machine learning but not AI", "It is data science only if it uses pandas", "It is deep learning because it uses rules"], "The lesson gives expert systems as AI systems that need not learn from data.", "Artificial Intelligence: The Big Picture", 7, "classify a rule-based expert system", None),
    ("An AI system uses a neural network with several layers. Where does the lecture's hierarchy place deep learning?", "Inside neural networks, which are inside machine learning and AI", ["Outside AI and separate from machine learning", "Above AI as a broader field", "Inside data preparation but not machine learning"], "The slide presents AI as the broad set, with ML, neural networks, and deep learning nested within it.", "Artificial Intelligence: The Big Picture", 8, "read the AI and ML hierarchy", None),
    ("Which statement about AI and machine learning follows from the lesson's hierarchy?", "Some AI systems use rules and do not learn from data", ["Every AI system must be trained on examples", "Machine learning is broader than artificial intelligence", "An expert system is not a form of AI"], "AI includes approaches such as expert systems that use explicit rules instead of learning from data.", "Artificial Intelligence: The Big Picture", 7, "infer a consequence of the AI hierarchy", None),
    ("A data science project cleans survey data and communicates a descriptive result but uses no AI. How should this be classified?", "It can be data science without being AI", ["It must be machine learning because it analyzes data", "It cannot be data science without neural networks", "It is AI because all data analysis simulates intelligence"], "Data science includes preparation, analysis, visualization, and communication; it is not contained entirely within AI.", "The key relationships", 9, "distinguish data science from AI", None),
    ("A policy researcher asks whether education is associated with employment and wants to quantify uncertainty. Which emphasis matches the lesson's description of statistics?", "Model-based inference and explanation", ["Automating decisions at scale as the only goal", "Predicting new cases without interpreting relationships", "Replacing data with domain knowledge"], "The lecture characterizes statistics as emphasizing inference, relationships, uncertainty, and explanation.", "Data Science versus statistics", 9, "apply the statistics emphasis", None),
    ("A service provider wants to predict which customers may cancel next month so it can offer retention support. Which emphasis matches the lesson's data science contrast?", "Prediction and actionable problem-solving", ["Testing only whether a prespecified model fits", "Estimating uncertainty as the sole project outcome", "Avoiding computational methods"], "The lesson emphasizes prediction, automation, and large-scale problem-solving in its data science contrast.", "Data Science versus statistics", 9, "apply the data science emphasis", None),
    ("A team begins with a regression model and tests whether observed data fit it to explain an association. How does the lecture characterize this approach?", "Model-driven", ["Data-driven in the lecture's contrast", "Unstructured", "Ethics-driven rather than analytical"], "The lecture calls an approach model-driven when it starts by assuming a mathematical model and assesses its fit.", "Data Science versus statistics", 9, "interpret model-driven analysis", None),
    ("Another team explores a large mixed-format dataset to discover useful patterns without beginning with one specified model. How does the lecture characterize this approach?", "Data-driven", ["Model-driven", "Rule-based AI", "Data preparation only"], "The lecture uses data-driven for letting data reveal patterns rather than beginning with a predefined model.", "Data Science versus statistics", 9, "interpret data-driven analysis", None),
    ("Which is the most careful way to use the lecture's statistics-versus-data-science comparison?", "Treat it as a contrast in typical goals and starting points, while recognizing overlap", ["Assume statistics never uses prediction and data science never explains", "Assume the fields use completely separate methods", "Assume any project belongs to exactly one field"], "The source says the fields answer different questions, but they share statistical and computational methods; the contrast is a teaching summary, not a strict boundary.", "Data Science versus statistics", 9, "critically interpret a disciplinary comparison", None),
    ("Which library is identified as a foundation for multidimensional arrays and linear algebra?", "NumPy", ["Matplotlib", "Seaborn", "Scikit-learn"], "NumPy provides multidimensional arrays and useful linear algebra functions.", "The libraries", 11, "match NumPy to its role", None),
    ("A researcher needs a Python library for tabular data structures and analysis. Which one is the direct match in the lesson?", "pandas", ["Matplotlib", "NumPy", "Scikit-learn"], "Pandas provides data structures and tools for analyzing tabular data.", "The libraries", 11, "select a tabular-data library", None),
    ("Which library is described as the foundational plotting library?", "Matplotlib", ["NumPy", "pandas", "Scikit-learn"], "The lesson identifies Matplotlib as the foundational plotting library.", "The libraries", 11, "match Matplotlib to its role", None),
    ("How does the lesson distinguish Seaborn from Matplotlib?", "Seaborn is built on Matplotlib and offers statistics-oriented graphics with convenient defaults", ["Matplotlib is built on Seaborn and is only for machine learning", "Seaborn is the core array and linear algebra library", "They are two names for the same Python package"], "Seaborn builds on Matplotlib and is designed for statistical graphics with attractive defaults.", "The libraries", 11, "compare visualization libraries", None),
    ("A project requires tools for classification, regression, and clustering. Which library best fits the lesson's description?", "scikit-learn", ["Matplotlib", "pandas", "NumPy"], "Scikit-learn provides tools for common machine-learning tasks such as classification, regression, and clustering.", "The libraries", 11, "match scikit-learn to ML tasks", None),
    ("Which statement best describes pandas in the lecture?", "An open-source tool with data structures and analysis features for tabular data", ["A plotting language that replaces Python", "A database format used only for financial records", "A machine-learning algorithm for neural networks"], "The lecture presents pandas as an open-source data structure and analysis tool for tabular data.", "Pandas", 12, "describe pandas", None),
    ("What does the name pandas refer to, according to the lecture?", "Panel Data", ["Python Analysis and Data System", "Predictive Analytics and Numerical Data", "Parallel Arrays and Data Structures"], "The lecture says the name comes from the econometrics term Panel Data.", "Pandas", 12, "identify the origin of the pandas name", None),
    ("Which historical statement about pandas matches the lecture?", "Wes McKinney created it in 2008 for financial data analysis at AQR", ["It was created by Guido van Rossum in 1991 for plotting", "It was created in 2018 as part of scikit-learn", "It began as a database format at Microsoft"], "The source gives Wes McKinney, 2008, and financial analysis at AQR as its origin.", "Pandas", 12, "recall pandas history from the source", None),
    ("Why does the standard import `import pandas as pd` use `pd`?", "It is a widely used convention, but another alias can be chosen", ["Python requires pandas to be named pd", "pd is a built-in module that contains pandas", "The alias makes DataFrames store data faster"], "The lecture describes pd as a standard alias, not a requirement of Python.", "Pandas", 12, "interpret an import alias", "import pandas as pd\n# pd is conventional; the alias is chosen by the programmer"),
    ("Which set of file types is explicitly mentioned as supported by pandas for import or export?", "CSV, text, Excel, and SQL data", ["PNG, MP3, and video files only", "Python source files and compiled executables only", "HTML pages only"], "The lecture names CSV, text, Excel, and SQL as supported formats or sources.", "Pandas", 12, "identify pandas input and output formats", None),
    ("What is the main structural feature of a DataFrame?", "It is a two-dimensional structure organized into rows and columns", ["It is a one-dimensional sequence with no labels", "It is a function that draws statistical charts", "It is an immutable tuple of column names"], "The lecture describes a DataFrame as a two-dimensional table with rows and columns.", "What is a DataFrame?", 13, "define a DataFrame", None),
    ("In the student score DataFrame, what does a row represent?", "One student's record", ["A variable such as Math", "A single score cell", "A plotting command"], "Each row is an individual record; here, each record is a student.", "What is a DataFrame?", 13, "interpret DataFrame rows", None),
    ("In a DataFrame whose columns are Math and Science, what does a column represent?", "A variable or feature", ["An individual student record", "One particular cell value", "A file format"], "Columns represent variables or features, while rows represent records.", "What is a DataFrame?", 13, "interpret DataFrame columns", None),
    ("In the lesson's table, what is the cell at row Ali and column Math?", "Ali's Math score, 90", ["Ali's Science score, 88", "Mona's Math score, 85", "The column label Math"], "A cell contains the value at the intersection of a record and a variable; Ali's Math value is 90.", "What is a DataFrame?", 13, "read a DataFrame cell", "scores = pd.DataFrame({'Math': [90, 85, 78], 'Science': [88, 92, 80]}, index=['Ali', 'Mona', 'Sara'])\nprint(scores.loc['Ali', 'Math'])"),
    ("Which analogy does the lesson use for pandas?", "A programmatic spreadsheet with additional data-analysis features", ["A static picture of a spreadsheet", "A replacement for statistical reasoning", "A database that stores only unstructured text"], "The Markdown calls pandas like a programmatic Excel sheet and describes DataFrames as tables with analysis capabilities.", "Pandas", 12, "interpret the spreadsheet analogy", None),
    ("Which task belongs to data science even when no machine-learning model is trained?", "Cleaning and communicating an analysis", ["Only training a neural network", "Only automating a decision", "Only writing a fixed IF/THEN rule"], "Data science includes preparation and communication as well as advanced analytics; it is broader than machine learning.", "The key relationships", 9, "distinguish data science work from ML", None),
    ("Why might a data scientist compare several machine-learning algorithms for the same project?", "Different algorithms suit different kinds of problems", ["Only one algorithm can learn from data", "All algorithms produce the same results", "Algorithms are chosen only by the size of a dataset"], "The lecture names regression, decision trees, and neural networks as different techniques suited to particular problems.", "What is Machine Learning?", 5, "explain why algorithm choice depends on the task", None),
    ("Which capability helps distinguish a DataFrame from a plain dictionary of columns?", "It adds table-oriented tools such as labeled access, aggregation, and missing-data handling", ["It can store only one data type in the whole table", "It removes the need to organize data into rows and columns", "It is immutable once constructed"], "The lecture describes DataFrames as dictionary-like column structures enhanced with indexing, aggregation, plotting, merging, and missing-data support.", "What is a DataFrame?", 13, "identify DataFrame capabilities", None),
]

essays = [
    {"prompt": "A city team plans a study of housing affordability. Explain how statistics, computer science, and domain expertise each contribute to the project. Name two data science objectives the team should include beyond modeling, and explain why ethics belongs in the analysis.", "expectedAnswer": "Statistics can quantify patterns and uncertainty; computer science provides tools to store and process data; housing or policy expertise helps interpret what the variables mean. Beyond modeling, the team should prepare/clean data and communicate results visually or in narrative. Ethics matters because data collection and decisions can affect communities and reproduce historical inequities.", "justification": "The answer follows the interdisciplinary definition and the four objectives in the paired sources, while linking ethical review to the social consequences of data use.", "rubric": ["Explains the contribution of statistics", "Explains the computational contribution", "Explains the role of domain expertise", "Names and explains two non-modeling objectives", "Connects ethics to social consequences or bias"], "source": "1_what's_ds.md, Data science and objectives; PDF pp. 4, 11", "operation": "apply the interdisciplinary model to a social-science project", "stimulusCode": "# Housing affordability study\nrecords = 'rent, income, household size, neighborhood'"},
    {"prompt": "A telecom company wants to reduce customer churn. Describe how a machine-learning approach could learn a pattern from past customers and use it on new customers. Distinguish this from writing a fixed IF/THEN rule, and state one limitation that the company should consider.", "expectedAnswer": "The company can use historical records containing features such as bills, usage, and whether a customer left. An algorithm learns relationships associated with churn, then estimates risk for customers not in the training records. A fixed rule is written in advance rather than inferred from examples. One limitation is that learned patterns are not guarantees and may reflect bias or changes in customer behavior; decisions should be evaluated and monitored.", "justification": "The source's churn example defines learning as finding reliable relationships in historical data and applying the resulting model to unseen cases, while contrasting that with explicit rules.", "rubric": ["Identifies historical customer data as examples", "Describes learning relationships/patterns", "Explains applying the model to unseen customers", "Distinguishes learning from a prewritten rule", "States a meaningful limitation or ethical concern"], "source": "1_what's_ds.md, Machine learning and churn; PDF pp. 5–6", "operation": "explain a supervised prediction scenario and its limits", "stimulusCode": "past_customers = ['bill', 'usage', 'left_or_stayed']\nnew_customer = ['bill', 'usage', '?']"},
    {"prompt": "Classify each system as AI, machine learning, both, or neither based on the lecture: (a) an expert system that follows specialists' IF/THEN rules; (b) a model that learns churn patterns from historical data; (c) a deep neural network trained on examples. Explain the nesting relationships among AI, ML, neural networks, and deep learning.", "expectedAnswer": "(a) AI, not necessarily ML; (b) ML and therefore AI; (c) deep learning within neural networks, within ML, within AI. The lecture treats AI as the broad field; ML is a subset, and deep learning is a narrower neural-network approach.", "justification": "This applies the source's explicit example of rule-based expert systems and its hierarchy in which ML is within AI and deep learning is nested inside neural-network approaches.", "rubric": ["Classifies the rule-based expert system as AI but not necessarily ML", "Classifies the learned churn model as ML and AI", "Places the deep neural network within ML and AI", "Explains deep learning's narrower position", "States that not all AI learns from data"], "source": "1_what's_ds.md, AI/ML nesting; PDF pp. 7–8", "operation": "classify AI systems and explain their hierarchy", "stimulusCode": "A: specialist-written IF/THEN rules\nB: patterns learned from past customers\nC: a multi-layer neural network trained on examples"},
    {"prompt": "A public-health agency has survey data with inconsistent categories and missing values. It wants to describe trends, present them to local councils, forecast next year's demand, and assess possible harms from using the data. Map each activity to the four data science objectives and explain why all four matter.", "expectedAnswer": "Standardize categories and address missingness under data preparation; present trends clearly under visualization and communication; forecast demand under advanced analytics; assess privacy, fairness, and social effects under ethical considerations. All four support a reliable and responsible decision process.", "justification": "The four activities correspond directly to the four objectives defined in the lesson, and together cover preparation, interpretation, prediction, and social responsibility.", "rubric": ["Maps cleaning/missing-data work to preparation", "Maps council presentation to visualization/communication", "Maps forecasting to advanced analytics", "Maps harm assessment to ethics", "Explains how the objectives work together"], "source": "1_what's_ds.md, The four objectives; PDF p. 4", "operation": "map a project workflow to data science objectives", "stimulusCode": "project = ['clean survey', 'describe trends', 'forecast demand', 'assess harms']"},
    {"prompt": "A team must choose tools for (a) multidimensional arrays and linear algebra, (b) tabular data manipulation, (c) plotting, (d) statistical graphics with convenient defaults, and (e) classification or clustering. Name a suitable library for each and explain one reason pandas DataFrames are useful in the workflow.", "expectedAnswer": "(a) NumPy; (b) pandas; (c) Matplotlib; (d) Seaborn; (e) scikit-learn. A DataFrame represents tabular data with rows, columns, and cells and supports analysis operations such as selection, aggregation, plotting, and handling missing values.", "justification": "The library roles match the lesson's descriptions; DataFrames provide a flexible table structure connecting data preparation and analysis to later visualization and modeling.", "rubric": ["Matches NumPy to arrays/linear algebra", "Matches pandas to tabular data", "Matches Matplotlib and Seaborn to their plotting roles", "Matches scikit-learn to ML tasks", "Explains a useful DataFrame feature"], "source": "1_what's_ds.md, Libraries and Pandas; PDF pp. 11–13", "operation": "select tools for a data workflow", "stimulusCode": "tools = {\n    'arrays': 'NumPy', 'tables': 'pandas',\n    'plots': 'Matplotlib', 'statistical graphics': 'Seaborn',\n    'classification': 'scikit-learn'\n}"},
    {"prompt": "Using the student table below, explain which parts are rows, columns, and cells. Identify Ali's Math score and describe what the DataFrame analogy to a dictionary of columns means.\n\n```python\nscores = pd.DataFrame({\n    'Math': [90, 85, 78],\n    'Science': [88, 92, 80]\n}, index=['Ali', 'Mona', 'Sara'])\n```", "expectedAnswer": "Rows are student records (Ali, Mona, Sara); columns are Math and Science; cells are individual scores. Ali's Math score is 90. The dictionary-of-columns analogy means each column label maps to a sequence of values, with DataFrame machinery for labels, alignment, aggregation, missing data, and other analysis.", "justification": "The table directly associates three student rows with two subject columns; the value at Ali/Math is 90, illustrating the row-column-cell structure.", "rubric": ["Identifies rows as student records", "Identifies columns as variables", "Identifies cells as individual observations", "Gives Ali's Math score as 90", "Explains the dictionary-of-columns analogy or added capabilities"], "source": "1_what's_ds.md, A DataFrame is a table; PDF p. 13", "operation": "read and explain a DataFrame structure", "stimulusCode": "scores = pd.DataFrame({\n    'Math': [90, 85, 78],\n    'Science': [88, 92, 80]\n}, index=['Ali', 'Mona', 'Sara'])"},
    {"prompt": "The lecture contrasts statistics as more model-driven and data science as more data-driven. Explain these two starting points using one question about explaining an association and one question about predicting future behavior. Then discuss why the contrast should not be treated as a strict boundary between the fields.", "expectedAnswer": "An explanatory question may begin with a model such as a regression and test whether data support an association, emphasizing inference and uncertainty. A predictive question may explore patterns in varied data to forecast a new case or support an action. The distinction is a useful summary of goals and starting points, but the fields overlap and share statistical and computational methods.", "justification": "The source contrasts typical goals and modeling strategies, while also noting that the disciplines answer different questions rather than being mutually exclusive; recognizing shared methods prevents overgeneralization.", "rubric": ["Explains model-driven analysis", "Explains data-driven pattern discovery", "Provides an explanatory example/question", "Provides a predictive example/question", "Recognizes overlap and avoids an absolute divide"], "source": "1_what's_ds.md, Data science versus statistics; PDF p. 9", "operation": "critically interpret the statistics/data science distinction", "stimulusCode": "# Explain an association: Does education relate to employment?\n# Predict a new case: Which customers may leave next month?"},
    {"prompt": "A university plans to use past admissions decisions to predict which applicants will succeed. Identify how this could be a data science and machine-learning project, describe the role of domain expertise, and analyze two ethical risks the university should address before acting on predictions.", "expectedAnswer": "The project can combine admissions records and outcomes, computational tools, and statistical analysis to learn predictive patterns. Domain expertise is needed to interpret measures of success and admissions context. Risks include reproducing historical discrimination, using proxies for protected or socioeconomic status, privacy concerns, and treating probabilistic predictions as certain. The university should audit data and outcomes, communicate limitations, and keep human accountability.", "justification": "The lesson explicitly warns that models learn from historical decisions and may encode discrimination; its interdisciplinary and ethics objectives require domain interpretation and scrutiny of social effects.", "rubric": ["Connects historical admissions data with pattern learning/prediction", "Explains the contribution of domain expertise", "Identifies historical bias or proxy discrimination", "Identifies another ethical/social risk", "Recommends responsible evaluation or communication"], "source": "1_what's_ds.md, Domain expertise; Ethical considerations; PDF p. 4 and pp. 5–7", "operation": "evaluate ethical risks in a predictive social-science application", "stimulusCode": "historical = ['application features', 'past decision', 'later outcome']\n# prediction should inform review, not automatically decide admission"},
]

for i, row in enumerate(essays, 1):
    row.update({"id": f"M3L1-E{i:02d}", "responseType": "structured response", "marks": 5, "rubric": [{"criterion": c, "points": 1} for c in row["rubric"]]})

items = []
for question, key, distractors, explanation, section, page, operation, code in raw:
    i = len(items) + 1
    options = [key] + distractors
    target = (i - 1) % 4
    shift = (-target) % 4
    options = options[shift:] + options[:shift]
    item = {
        "id": f"M3L1-{i:03d}", "question": question, "options": options,
        "correctIndex": options.index(key), "expectedAnswer": key,
        "explanation": explanation,
        "source": f"1_what's_ds.md — {section}; Module 3 Lecture 3_1 PDF p. {page}",
        "objective": "data science foundations", "operation": operation,
    }
    if code:
        item["stimulusCode"] = code
    items.append(item)

key_rewrites = {
    "M3L1-001": "It combines statistics, computing, and domain expertise",
    "M3L1-002": "Free-text interview responses",
    "M3L1-004": "Data preparation: cleaning and organizing",
    "M3L1-012": "The pattern is learned from historical examples, not written in advance",
    "M3L1-013": "No; the condition is a fixed rule written in advance",
    "M3L1-021": "Data-driven pattern discovery",
    "M3L1-022": "Use it as a contrast in typical aims, not an absolute boundary",
    "M3L1-026": "Seaborn builds on Matplotlib for statistical graphics",
    "M3L1-028": "An open-source tool for tabular-data analysis",
    "M3L1-033": "A two-dimensional table with rows and columns",
    "M3L1-036": "Ali's Math score, 90",
    "M3L1-037": "A programmatic spreadsheet for analysis",
    "M3L1-038": "Cleaning and communicating analysis results",
    "M3L1-039": "Algorithms are selected to suit a problem",
    "M3L1-040": "It adds table-analysis tools to dictionary-like columns",
}
balanced_options = {
    "M3L1-001": ["It uses only machine learning to make every decision", "It avoids subject knowledge and relies only on software tools", "It combines two disciplines but leaves out domain expertise"],
    "M3L1-002": ["A spreadsheet", "A database table with fixed fields and labeled variables", "A fixed-schema set of records arranged in named columns"],
    "M3L1-004": ["Advanced analytics", "Data visualization and communication", "Ethical review of collection, analysis, and data use"],
    "M3L1-005": ["Data preparation", "Advanced analytics", "Ethical review of data collection and its public impact"],
    "M3L1-007": ["Ethics removes the need to examine data quality", "Ethics is a plotting method for model results", "Ethics matters only when findings are communicated publicly"],
    "M3L1-009": ["Programmers write every decision as a fixed rule", "Computers store data without finding relationships", "Computers find patterns but still require programmers to specify each prediction in advance"],
    "M3L1-012": ["The pattern is a chart chosen by an analyst", "The rule is learned from examples, while a pattern is typed by a programmer", "There is no difference between the two"],
    "M3L1-013": ["Yes; every automated decision is machine learning", "Yes; using a computer makes it machine learning", "Yes; account records automatically teach the system that condition"],
    "M3L1-014": ["It is deep learning because it uses rules", "It is machine learning but not AI because specialists wrote the rules", "It is data science only if it uses pandas"],
    "M3L1-015": ["Above AI as a broader field", "Inside data preparation but not machine learning", "Outside the AI hierarchy because deep learning is broader than artificial intelligence"],
    "M3L1-017": ["It is an AI system", "It must be machine learning because it analyzes data", "It is AI because all data analysis simulates intelligence"],
    "M3L1-021": ["Model-driven", "Rule-based AI", "Data-driven analysis that avoids every use of a statistical model"],
    "M3L1-022": ["Assume any project belongs to exactly one field", "Assume statistics never predicts and data science never explains", "Treat them as fields that never share goals, data, or methods"],
    "M3L1-023": ["SciPy", "Scikit-learn", "Matplotlib"],
    "M3L1-026": ["They are two names for the same Python package", "Matplotlib builds on Seaborn and provides statistical-graphics defaults", "Seaborn is the core array and linear algebra library"],
    "M3L1-027": ["pandas", "NumPy", "Matplotlib, the foundational plotting library"],
    "M3L1-028": ["A plotting language that replaces Python", "A database format used only to store financial records and nothing else", "A machine-learning algorithm for neural networks"],
    "M3L1-029": ["Data", "Predictive Analytics and Numerical Data", "Parallel Arrays and Data Structures"],
    "M3L1-030": ["It began as a database format at Microsoft", "It was created by Guido van Rossum in 1991 as Python's built-in plotting tool", "It was created in 2018 as part of scikit-learn"],
    "M3L1-031": ["pd is a built-in module that contains pandas", "The alias makes DataFrames store data faster", "Python requires the alias pd in every program that uses pandas DataFrames"],
    "M3L1-033": ["A one-dimensional sequence with no labels", "A two-dimensional array with columns but no rows", "An immutable tuple containing column names"],
    "M3L1-036": ["The Math column", "Ali's Science score, 88", "Mona's Math score, 85"],
    "M3L1-037": ["A static picture of a spreadsheet", "A replacement for statistical reasoning and subject knowledge", "A database that stores only unstructured text"],
    "M3L1-038": ["Only writing a fixed IF/THEN rule", "Only automating a decision", "Training a neural network as the only activity in every data science project"],
    "M3L1-039": ["All algorithms produce the same results", "Algorithms are chosen only by dataset size, regardless of the task", "Only one algorithm can learn from data"],
    "M3L1-040": ["It can store only one data type in the entire table", "It removes the need to organize data into rows and columns", "It is immutable once constructed"],
}
for item in items:
    if item["id"] in key_rewrites or item["id"] in balanced_options:
        item["expectedAnswer"] = key_rewrites.get(item["id"], item["expectedAnswer"])
        choices = [item["expectedAnswer"]] + balanced_options[item["id"]]
        target = (int(item["id"].rsplit("-", 1)[1]) - 1) % 4
        shift = (-target) % 4
        item["options"] = choices[shift:] + choices[:shift]
        item["correctIndex"] = item["options"].index(item["expectedAnswer"])

import sys
sys.path.insert(0, str(ROOT.parent))
from explanation_overrides import apply_overrides
apply_overrides(ROOT.name, items)
(ROOT / "final_items.jsonl").write_text("\n".join(json.dumps(x, ensure_ascii=False) for x in items) + "\n")
(ROOT / "essay_items.jsonl").write_text("\n".join(json.dumps(x, ensure_ascii=False) for x in essays) + "\n")
print(f"created {len(items)} MCQs and {len(essays)} structured responses")
