import json
from pathlib import Path
ROOT=Path(__file__).parent

def mcq(i,q,key,distr,why,source,objective,operation,code=None):
    opts=[key]+distr
    target=(i-1)%4
    shift=(-target)%4
    opts=opts[shift:]+opts[:shift]
    row={"id":f"M2L2-{i:03d}","question":q,"options":opts,"correctIndex":opts.index(key),"expectedAnswer":key,"explanation":why,"source":source,"objective":objective,"operation":operation}
    if code: row["stimulusCode"]=code
    return row

R=[]
R.append(mcq(1,"By default, how does a Python script execute its statements?","Sequentially, from top to bottom",["By selecting a branch at random","By repeating each statement until it is false","By executing only indented statements"],"The lesson describes sequential top-to-bottom execution as the default flow.","2_making_decisions.md; PDF p. 31","flow_and_if_syntax","distinguish default sequential flow"))
R.append(mcq(2,"What does conditional execution allow a program to do?","Run a block only when its condition is true",["Translate all code before it runs","Repeat a block while its condition remains true","Store a value in a named variable"],"A conditional chooses whether a block runs according to a condition.","2_making_decisions.md; PDF p. 31","flow_and_if_syntax","interpret conditional execution"))
R.append(mcq(3,'Which pair of constructs changes sequential control flow?',"Selection and repetition",["Input and output","Compilation and interpretation","Assignment and comparison"],"The lesson contrasts selection (conditional execution) with repetition (loops).","2_making_decisions.md; PDF p. 31","flow_and_if_syntax","recall execution-flow categories"))
R.append(mcq(4,"Which line has the correct basic Python conditional form?","`if score >= 50:`",["`if score >= 50`","`if (score >= 50);`","`IF score >= 50:`"],"Python requires a colon at the end of the if header; the keyword is lowercase.","2_making_decisions.md; PDF p. 31","conditional_syntax","identify if syntax"))
R.append(mcq(5,"Which detail tells Python which statements belong to an `if` block?","Indentation beneath the if header",["Quotation marks around the condition","A semicolon at the end of each statement","The variable's capitalization"],"Indentation defines the body of the conditional block.","2_making_decisions.md; PDF p. 31","conditional_syntax","interpret block indentation"))
R.append(mcq(6,"In this code, which values cause the message to print?","Only values greater than zero",["Values greater than or equal to zero","All values, including zero","Only values less than zero"],"The condition is x > 0, so zero does not satisfy it.","2_making_decisions.md; PDF p. 32","simple_if","apply a simple if", "x = int(input())\nif x > 0:\n    print('positive')"))
R.append(mcq(7,"After the code below, which line runs whether x is positive or not?","The unindented Done line",["`print(x, 'is positive')`","Neither line runs","Both lines run only for positive x"],"The Done line is outside the indented block, so it runs after the if regardless of the condition.","2_making_decisions.md; PDF p. 32","simple_if","trace indentation scope","x = int(input())\nif x > 0:\n    print(x, 'is positive')\nprint('Done.')"))
R.append(mcq(8,"What happens if the condition in an `if` statement is False and there is no `else`?","The body is skipped; execution continues",["Python raises an error because every if needs else","Python repeats the condition until it becomes True","The if block runs once anyway"],"An else is optional; if the condition is false, the indented body is skipped.","2_making_decisions.md; PDF p. 32","simple_if","infer behavior without an else"))
R.append(mcq(9,"For the code below, what is printed when x is 12?","`12 is an even number`",["`12 is an odd number`","Both even and odd messages","No message, because 12 % 2 is undefined"],"12 % 2 equals zero, so the if branch runs.","2_making_decisions.md; PDF p. 32","compound_conditions","trace a parity conditional","x = 12\nif x % 2 == 0:\n    print(x, 'is an even number')\nelse:\n    print(x, 'is an odd number')"))
R.append(mcq(10,"For the same even/odd code, what happens when x is 7?","Else prints that x is odd",["The if branch prints that x is even","Neither branch runs","Both branches print"],"Seven has remainder one when divided by two, so the equality condition is false and else runs.","2_making_decisions.md; PDF p. 32","compound_conditions","trace the false branch","x = 7\nif x % 2 == 0:\n    print('even')\nelse:\n    print('odd')"))
R.append(mcq(11,'Which pair of mistakes causes syntax errors in a conditional header?',"One `=` used for comparison or no colon",["Using `==` instead of `=`, or adding a colon","Using `and`, or indenting a block","Using `else`, or comparing integers"],"The examples show one equals sign used as a comparison and a missing colon; both prevent parsing.","2_making_decisions.md; PDF p. 32","conditional_syntax","diagnose conditional syntax errors"))
R.append(mcq(12,"When comparing two numbers with `if x > y`, `elif y > x`, and `else`, what does the final else represent?","The two values are equal",["x is greater than y","y is greater than x","At least one value is negative"],"If neither value is greater than the other, the numbers are equal.","2_making_decisions.md; PDF p. 33","chained_conditionals","infer the residual comparison case","if x > y:\n    print('x is greater')\nelif y > x:\n    print('y is greater')\nelse:\n    print('equal')"))
R.append(mcq(13,"In an `if`/`elif`/`else` chain, how are multiple true conditions handled?","The first match runs; later branches are skipped",["Python executes every true branch","Python executes the last true branch only","Python combines the outputs of all true branches"],"A chained conditional checks branches in order and stops after the first match.","2_making_decisions.md; PDF p. 33","chained_conditionals","apply first-match semantics"))
R.append(mcq(14,"For x=5 and y=5, which branch runs in the two-number comparison example?","The final else branch",["Both the if and elif branches","The first if branch","The elif branch"],"Neither x>y nor y>x is true when the values are equal.","2_making_decisions.md; PDF p. 33","chained_conditionals","trace equal-value case","x = 5\ny = 5\nif x > y:\n    result = 'x greater'\nelif y > x:\n    result = 'y greater'\nelse:\n    result = 'equal'"))
R.append(mcq(15,"Why is branch order important in a chain that classifies positive numbers as even or odd?","A broad first test can block later cases",["A later branch changes the value tested by earlier branches","Branches are randomized","Python always sorts elif conditions by specificity"],"A true earlier condition prevents later conditions from being checked.","2_making_decisions.md; PDF p. 34","branch_order","analyze branch shadowing","if x > 0:\n    print('positive')\nelif x > 0 and x % 2 != 0:\n    print('positive odd')"))
R.append(mcq(16,"Which compound condition means that x is positive and even?","`x > 0 and x % 2 == 0`",["`x > 0 or x % 2 == 0`","`x < 0 and x % 2 == 0`","`x == 0 and x % 2 != 0`"],"Both the positive test and zero-remainder test must be true.","2_making_decisions.md; PDF p. 34","compound_conditions","construct a compound condition"))
R.append(mcq(17,"A condition should pass if a customer has a coupon OR is a member. Which logical operator expresses that either one is sufficient?","`or`",["`and`","`not`","`==`"],"Or is true when at least one condition is true.","2_making_decisions.md; PDF pp. 24, 34","compound_conditions","map an either/or rule"))
R.append(mcq(18,"What output category does the five-way classifier assign to a=-8?","Even negative number",["Zero","Odd negative number","Even positive number"],"-8 is less than zero and divisible by 2, so it matches the negative-even branch.","2_making_decisions.md; PDF p. 34","compound_conditions","trace compound classification","a = -8\nif a > 0 and a % 2 == 0:\n    kind = 'positive even'\nelif a > 0 and a % 2 != 0:\n    kind = 'positive odd'\nelif a == 0:\n    kind = 'zero'\nelif a < 0 and a % 2 == 0:\n    kind = 'negative even'\nelse:\n    kind = 'negative odd'"))
R.append(mcq(19,'Which Boolean condition exactly implements the leap-year rule?',"`year % 400 == 0 or (year % 4 == 0 and year % 100 != 0)`",["`year % 100 == 0 and year % 400 != 0`","`year % 400 == 0 and (year % 4 == 0 or year % 100 != 0)`","`year % 4 == 0 or year % 100 != 0`"],"A year qualifies if divisible by 400, or if divisible by 4 and not by 100.","2_making_decisions.md; PDF pp. 36–37","leap_year","construct the leap-year test"))
R.append(mcq(20,'Under the standard leap-year rule, is 1900 a leap year?',"No; it is divisible by 100 but not by 400",["Yes; every year divisible by 4 is a leap year","Yes; every century year is a leap year","No; it is not divisible by 4"],"1900 is a century year not divisible by 400, so it is excluded.","2_making_decisions.md; PDF pp. 36–37","leap_year","apply century-year exception","year = 1900\nif year % 400 == 0 or (year % 4 == 0 and year % 100 != 0):\n    result = 'leap year'\nelse:\n    result = 'not a leap year'"))
R.append(mcq(21,'Under the standard leap-year rule, is 2000 a leap year?',"Yes; it is divisible by 400",["No; it is a century year","No; century years are never leap years","Yes; it is divisible by 100 only"],"The divisible-by-400 exception makes 2000 a leap year.","2_making_decisions.md; PDF pp. 36–37","leap_year","apply the 400-year exception"))
R.append(mcq(22,"A loan applicant must be at least 21 and earn at least 25,000. Which expression tests eligibility?","`age >= 21 and income >= 25000`",["`age == 21 and income == 25000`","`age > 21 or income > 25000`","`age >= 21 or income >= 25000`"],"At least means inclusive >= thresholds, and both are required.","2_making_decisions.md; PDF pp. 36, 38","loan_eligibility","express inclusive compound thresholds"))
R.append(mcq(23,'An applicant is age 26 and earns 24,999. Under a loan rule requiring age at least 21 and income at least 25,000, what is the result?',"No; income is below the minimum",["Age alone qualifies","Not qualified, because age is above 21","Qualified, because income is rounded to 25,000"],"The income condition is false, and both conditions must be true.","2_making_decisions.md; PDF p. 38","loan_eligibility","apply rule near a threshold"))
R.append(mcq(24,"At what point in the tariff chain does a unit count of 450 reach the selected band?","The branch for values up to 500",["The branch for values up to 100","The branch for values up to 300","The final above-500 branch"],"450 exceeds 100 and 300 but is at most 500.","2_making_decisions.md; PDF p. 39","tariff","trace ordered tariff bands","units = 450\nif units <= 100:\n    rate = 0.10\nelif units <= 300:\n    rate = 0.15\nelif units <= 500:\n    rate = 0.20\nelse:\n    rate = 0.25"))
R.append(mcq(25,'Using the tariff code, what bill is calculated for 400 units if the selected rate is multiplied by all units?',"80",["20","60","100"],"400 is in the 0.20 band, so 400 * 0.20 = 80.","2_making_decisions.md; PDF p. 39","tariff","calculate a tariff outcome","units = 400\nif units <= 100:\n    bill = units * 0.10\nelif units <= 300:\n    bill = units * 0.15\nelif units <= 500:\n    bill = units * 0.20\nelse:\n    bill = units * 0.25\nprint(bill)"))
R.append(mcq(26,"Why does the second electricity branch use `units <= 300` rather than repeating `units >= 101`?","The first branch catches units through 100",["The second branch is tested before the first","An elif cannot use >=","Python assumes units are integers"],"Only inputs that fail the first branch can reach the second branch, so its lower bound is implicit.","2_making_decisions.md; PDF p. 39","tariff","explain an implicit lower bound"))
R.append(mcq(27,"What is the tariff rate for exactly 100 units?","0.10 per unit",["0.20 per unit","0.25 per unit","0.15 per unit"],"The first condition is inclusive: units <= 100.","2_making_decisions.md; PDF p. 39","tariff","apply a tariff boundary"))
R.append(mcq(28,"What is the tariff rate for exactly 501 units?","0.25 per unit",["0.10 per unit","0.15 per unit","0.20 per unit"],"501 exceeds every stated upper bound and reaches the final else.","2_making_decisions.md; PDF p. 39","tariff","apply the final tariff branch"))
R.append(mcq(29,"What does nesting mean for conditional statements?","Placing one conditional inside the block of another",["Writing two conditions on one line without indentation","Repeating the same if until it becomes false","Putting an else before the if"],"A nested conditional is a decision contained inside another decision's block.","2_making_decisions.md; PDF p. 35","nested_conditionals","identify a nested structure"))
R.append(mcq(30,'Why can deeply nested conditions be hard to read?',"Deep nesting makes the flow harder to trace",["Python does not allow nested else blocks","Python evaluates every nested condition before choosing a branch","Nested conditions cannot contain comparisons"],"As nesting depth grows, it is harder to track the structure; elif or functions may be clearer.","2_making_decisions.md; PDF p. 35","nested_conditionals","explain a readability trade-off"))
R.append(mcq(31,"The code first tests `x > 0`, then `x > 10`. For x=12, which branch runs?","The first branch, so the second is skipped",["Both branches run","Neither branch runs","The second branch, because it is more specific"],"The first condition is true, so the elif is not evaluated.","2_making_decisions.md; PDF p. 34","branch_order","trace a broad first condition","if x > 0:\n    label = 'positive'\nelif x > 10:\n    label = 'above ten'"))
R.append(mcq(32,"Which rewrite ensures a value above 10 is recognized before the general positive case?","Test `x > 10` before `x > 0`",["Test `x > 0` before `x > 10`","Replace both conditions with `x == 10`","Put `else` before both tests"],"Specific conditions should be placed before broader conditions in a first-match chain.","2_making_decisions.md; PDF p. 34","branch_order","repair branch ordering"))
R.append(mcq(33,"In the nested comparison example, why does the inner `if x < y` only run when x and y are not equal?","It is under the outer unequal-case else",["The inner condition changes x and y first","Python skips the outer condition","The outer condition changes the values before the inner test runs"],"The inner comparison is nested in the outer else, reached only when equality is false.","2_making_decisions.md; PDF p. 35","nested_conditionals","trace nested reachability","if x == y:\n    result = 'equal'\nelse:\n    if x < y:\n        result = 'x less'\n    else:\n        result = 'y less'"))
R.append(mcq(34,"In the nested comparison below, if x=3 and y=9, what value is assigned to `result`?","x less",["equal","y less","No value is assigned"],"The values are not equal, so the outer else runs; x<y is true in the inner decision, assigning 'x less'.","2_making_decisions.md; PDF p. 35","nested_conditionals","trace nested comparison","if x == y:\n    result = 'equal'\nelse:\n    if x < y:\n        result = 'x less'\n    else:\n        result = 'y less'"))
R.append(mcq(35,"What error occurs if a statement intended to be inside an if block is not indented?","An indentation or block-structure error",["A NameError because all variables disappear","No error; indentation never affects Python","A ZeroDivisionError"],"Indentation defines the conditional body; incorrect indentation prevents the block from being parsed as intended.","2_making_decisions.md; PDF p. 31","conditional_syntax","diagnose an indentation error","if x > 0:\nprint('positive')"))
R.append(mcq(36,'A program reads `x = input(...)` and immediately tests `x > 0`. What step is needed when the input should be numeric?',"Convert input text to int or float before testing",["Convert x to a comment","Python converts every input to a number as soon as it is read","Use print() instead of input()"],"input() yields text; convert it before a numeric comparison.","2_making_decisions.md; PDF pp. 32–33","input_and_conditionals","apply input conversion","x = input('Enter a number: ')\nif x > 0:\n    print('positive')"))
R.append(mcq(37,"In the five-category number classifier, what category is assigned to a=-5?","Odd negative number",["Even negative number","Odd positive number","Zero"],"-5 is negative and has a nonzero remainder on division by 2, so it reaches the final else.","2_making_decisions.md; PDF p. 34","compound_conditions","trace a compound classification"))
R.append(mcq(38,"For a=0 in the compound number classifier, what branch should match before any negative case?","The zero test",["No branch","The positive-even branch","The negative-even branch"],"The explicit zero condition appears before the negative cases and matches exactly.","2_making_decisions.md; PDF p. 34","compound_conditions","trace the zero case"))
R.append(mcq(39,"Which condition identifies a positive odd number?","`a > 0 and a % 2 != 0`",["`a < 0 and a % 2 != 0`","`a == 0 or a % 2 == 0`","`a > 0 and a % 2 == 0`"],"A positive odd number exceeds zero and leaves a nonzero remainder after division by 2.","2_making_decisions.md; PDF p. 34","compound_conditions","construct a compound classification"))
R.append(mcq(40,"A person is admitted if they have a ticket AND arrive before 8, or a supervisor approves them. Which grouping matches that rule?","`(has_ticket and before_8) or supervisor_approval`",["`has_ticket and (before_8 or supervisor_approval)`","`has_ticket or before_8 and supervisor_approval`","`not has_ticket and before_8 and supervisor_approval`"],"Supervisor approval is an independent alternative to meeting both ticket and time requirements.","2_making_decisions.md; PDF pp. 24, 34","compound_conditions","translate a mixed compound rule"))

essays=[
{"id":"M2L2-E01","prompt":"Trace the code for x=-2 and x=5. For each input, state which lines run and explain the role of indentation.","responseType":"code trace","expectedAnswer":"For -2, the positive print is skipped and Done prints. For 5, both positive and Done print. The indented print belongs to the if block; the unindented Done statement runs after the conditional either way.","rubric":[{"criterion":"States that -2 skips the positive message","points":1},{"criterion":"States Done prints for -2","points":1},{"criterion":"States both messages print for 5","points":1},{"criterion":"Explains indentation defines the if block","points":1},{"criterion":"Explains the unindented line runs regardless of condition","points":1}],"source":"2_making_decisions.md, Is the number positive?; PDF p. 32","operation":"trace a simple if and explain indentation","stimulusCode":"if x > 0:\n    print('positive')\nprint('Done.')","marks":5},
{"id":"M2L2-E02","prompt":"Design an if/elif/else chain that compares two numbers and reports whether the first is greater, the second is greater, or they are equal. Explain why the final case can safely be treated as equality.","responseType":"conditional design","expectedAnswer":"if x>y: report x greater; elif y>x: report y greater; else: report equal. For comparable numeric values, if neither is greater, they are equal.","rubric":[{"criterion":"Tests x>y in a valid first branch","points":1},{"criterion":"Tests y>x in an elif branch","points":1},{"criterion":"Uses else for equality","points":1},{"criterion":"Uses valid colon and indentation structure","points":1},{"criterion":"Explains why neither-greater case implies equality","points":1}],"source":"2_making_decisions.md, Which number is bigger?; PDF p. 33","operation":"design and justify a chained comparison","marks":5},
{"id":"M2L2-E03","prompt":'Use the leap-year rule to classify 2000, 1900, 2024, and 2023. State the condition and explain why the two century examples differ.',"responseType":"rule application","expectedAnswer":"2000 is a leap year; 1900 is not; 2024 is a leap year; 2023 is not. Condition: divisible by 400 OR divisible by 4 and not by 100. The 400 exception makes 2000 qualify while 1900 does not.","rubric":[{"criterion":"Correctly classifies 2000","points":1},{"criterion":"Correctly classifies 1900","points":1},{"criterion":"Correctly classifies 2024 and 2023","points":1},{"criterion":"States the full divisible-by-400 or divisible-by-4-not-100 rule","points":1},{"criterion":"Explains the century exception","points":1}],"source":"2_making_decisions.md, Leap years; PDF pp. 36–37","operation":"apply a compound divisibility rule","marks":5},
{"id":"M2L2-E04","prompt":"A chained classification should report above 10, positive, or not positive. The draft tests x>0 before x>10. Explain the bug for x=12 and rewrite the conditions in an order that makes all three outcomes reachable.","responseType":"diagnose and repair","expectedAnswer":"For x=12, x>0 is true first, so the later x>10 branch is unreachable. Put the specific condition first: if x>10 report above 10; elif x>0 report positive; else report not positive.","rubric":[{"criterion":"Traces x=12 into the first broad branch","points":1},{"criterion":"Explains why the later branch is skipped","points":1},{"criterion":"Places x>10 before x>0","points":1},{"criterion":"Uses else for x<=0","points":1},{"criterion":"Provides a valid chained structure","points":1}],"source":"2_making_decisions.md, Order matters, and it's silent; PDF p. 34","operation":"diagnose and repair unreachable branch ordering","marks":5},
{"id":"M2L2-E05","prompt":"An applicant qualifies for a loan only if age is at least 21 and annual income is at least 25,000. Write the Boolean condition and classify these cases: (20, 30000), (21, 25000), (30, 24999), and (21, 26000).","responseType":"condition and case analysis","expectedAnswer":"Condition: age >= 21 and income >= 25000. The cases are not qualified, qualified, not qualified, qualified. Both thresholds are inclusive and both must hold.","rubric":[{"criterion":"Writes age >= 21","points":1},{"criterion":"Writes income >= 25000 joined with and","points":1},{"criterion":"Correctly classifies first two cases","points":1},{"criterion":"Correctly classifies last two cases","points":1},{"criterion":"Explains inclusive thresholds and both-required logic","points":1}],"source":"2_making_decisions.md, Loan eligibility; PDF p. 38","operation":"apply inclusive thresholds and conjunction","marks":5},
{"id":"M2L2-E06","prompt":'Using the electricity tariff code, select the rate and calculate the bill for 50, 250, 400, and 800 units. Explain how the order of the branches creates the lower end of each later band.',"responseType":"branch trace and calculation","expectedAnswer":"50: .10 rate, bill 5; 250: .15, bill 37.5; 400: .20, bill 80; 800: .25, bill 200. Later branches are reached only after earlier conditions fail, so their lower bounds are implicit.","rubric":[{"criterion":"Correctly calculates the 50-unit bill as 5","points":1},{"criterion":"Correctly calculates the 250-unit bill as 37.5","points":1},{"criterion":"Correctly calculates the 400-unit bill as 80","points":1},{"criterion":"Correctly calculates the 800-unit bill as 200","points":1},{"criterion":"Explains implicit lower bounds from prior branch failures","points":1}],"source":"2_making_decisions.md, The electricity bill; PDF p. 39","operation":"trace tariff bands and calculate outcomes","marks":5},
{"id":"M2L2-E07","prompt":'Classify a number as positive even, positive odd, zero, negative even, or negative odd. Write an ordered condition outline and show the resulting category for 8, 3, 0, -6, and -7.',"responseType":"conditional design and trace","expectedAnswer":"One valid sequence: if a>0 and a%2==0; elif a>0 and a%2!=0; elif a==0; elif a<0 and a%2==0; else negative odd. Results: 8 positive even, 3 positive odd, 0 zero, -6 negative even, -7 negative odd.","rubric":[{"criterion":"Includes positive-even and positive-odd conditions","points":1},{"criterion":"Includes an explicit zero condition","points":1},{"criterion":"Includes negative-even condition and final negative-odd case","points":1},{"criterion":"Correctly classifies 8, 3, and 0","points":1},{"criterion":"Correctly classifies -6 and -7 and uses ordered first-match logic","points":1}],"source":"2_making_decisions.md, Compound conditions; PDF p. 34","operation":"design and trace a multiway compound classification","marks":5},
{"id":"M2L2-E08","prompt":"Rewrite the nested comparison below as a single if/elif/else chain with the same outcomes. Explain one readability advantage and confirm the output for x=4, y=9.","responseType":"refactor and trace","expectedAnswer":"if x==y: result='equal'; elif x<y: result='x less'; else: result='y less'. For x=4,y=9, result is x less. A single chain avoids an extra nesting level and can be easier to read.","rubric":[{"criterion":"Preserves equality case in the first if","points":1},{"criterion":"Uses x<y in an elif branch","points":1},{"criterion":"Uses else for x>y","points":1},{"criterion":"Gives x less for x=4,y=9","points":1},{"criterion":"States a valid readability benefit of flattening the nesting","points":1}],"source":"2_making_decisions.md, Nested conditions; PDF p. 35","operation":"refactor a nested decision and trace it","stimulusCode":"if x == y:\n    result = 'equal'\nelse:\n    if x < y:\n        result = 'x less'\n    else:\n        result = 'y less'","marks":5}
]

essay_justifications = {
    "M2L2-E01": "For x=-2 the condition x>0 is false, so its indented body is skipped; for x=5 it is true. The unindented Done statement is outside the conditional body and therefore runs in both cases.",
    "M2L2-E02": "The two greater-than tests cover the unequal cases. For comparable numeric inputs, if neither x>y nor y>x is true, the values must be equal, so the final else is valid.",
    "M2L2-E03": "A year is a leap year when it is divisible by 400, or divisible by 4 but not by 100. Thus 2000 meets the 400 exception, 1900 is excluded by the century rule, 2024 qualifies, and 2023 does not divide by 4.",
    "M2L2-E04": "An if/elif chain stops after its first true branch. Since 12>0 is already true, testing it first prevents the later 12>10 branch from being reached; checking the narrower threshold first preserves both outcomes.",
    "M2L2-E05": "Eligibility requires both inclusive comparisons to be true. The conjunction rejects age 20 and income 24,999, while equality at either threshold qualifies when the other condition also passes.",
    "M2L2-E06": "The rates are selected by the first matching tariff branch and each bill is units multiplied by that rate. Failure of earlier upper-bound tests establishes the implicit lower bound of each later band.",
    "M2L2-E07": "The ordered conditions separate sign and parity, with zero handled explicitly. Each input matches its sign/parity combination; the final else covers the remaining negative odd case after the earlier branches fail.",
    "M2L2-E08": "The chain preserves the original three mutually exclusive outcomes while removing one nesting level. With x=4 and y=9, equality is false and x<y is true, so result is 'x less'.",
}
for essay in essays:
    essay["justification"] = essay_justifications[essay["id"]]

import sys
sys.path.insert(0, str(ROOT.parent))
from explanation_overrides import apply_overrides
apply_overrides(ROOT.name, R)
(ROOT/"final_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in R)+"\n")
(ROOT/"essay_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in essays)+"\n")
print(f"restored {len(R)} Making Decisions MCQs and {len(essays)} responses")
