import json
from pathlib import Path
from html import escape

ROOT = Path(__file__).parent
ASSETS = ROOT / "diagrams"
ASSETS.mkdir(parents=True, exist_ok=True)

def svg(name, title, nodes, edges, width=700, height=900):
    """Write a simple accessible flowchart SVG; nodes are (id, kind, text, x, y)."""
    shapes = []
    centers = {}
    for ident, kind, label, x, y in nodes:
        lines = label.split("\n")
        cx, cy = x + 145, y + 36
        centers[ident] = (cx, cy, kind)
        if kind == "terminal":
            shape = f'<rect x="{x}" y="{y}" width="290" height="72" rx="36" class="terminal"/>'
        elif kind == "io":
            shape = f'<polygon points="{x+28},{y} {x+290},{y} {x+262},{y+72} {x},{y+72}" class="io"/>'
        elif kind == "decision":
            shape = f'<polygon points="{x+145},{y} {x+290},{y+58} {x+145},{y+116} {x},{y+58}" class="decision"/>'
            cy += 4
        else:
            shape = f'<rect x="{x}" y="{y}" width="290" height="72" class="process"/>'
        text = "".join(f'<tspan x="{cx}" dy="{0 if i == 0 else 22}">{escape(line)}</tspan>' for i, line in enumerate(lines))
        shapes.append(shape + f'<text x="{cx}" y="{cy - (len(lines)-1)*11}" text-anchor="middle">{text}</text>')
    links = []
    for a, b, label, route in edges:
        ax, ay, ak = centers[a]; bx, by, bk = centers[b]
        if route == "back":
            path = f'M {ax+145} {ay} L 610 {ay} L 610 {by} L {bx+145} {by}'
            labelx, labely = 615, (ay+by)/2
        elif route == "left":
            path = f'M {ax-145} {ay} L 70 {ay} L 70 {by} L {bx-145} {by}'
            labelx, labely = 10, (ay+by)/2
        elif route == "branch_right":
            path = f'M {ax+145} {ay} L 550 {ay} L 550 {by-36} L {bx} {by-36}'
            labelx, labely = 555, (ay+by)/2
        elif route == "branch_left":
            path = f'M {ax-145} {ay} L 150 {ay} L 150 {by-36} L {bx} {by-36}'
            labelx, labely = 80, (ay+by)/2
        else:
            path = f'M {ax} {ay+36} L {bx} {by-36}'
            labelx, labely = ax+14, (ay+by)/2
        links.append(f'<path d="{path}" class="arrow" marker-end="url(#arrow)"/><text class="edge-label" x="{labelx}" y="{labely-6}">{label}</text>' if label else f'<path d="{path}" class="arrow" marker-end="url(#arrow)"/>')
    content = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">
<title id="title">{escape(title)}</title><desc id="desc">Flowchart with labeled standard flowchart symbols and directed arrows.</desc>
<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="5" orient="auto"><path d="M0,0 L10,5 L0,10 z" fill="#263746"/></marker></defs>
<style>text{{font-family:Arial,sans-serif;font-size:18px;fill:#172b3a}}.edge-label{{font-size:16px;font-weight:bold}}.terminal{{fill:#e5f2ff;stroke:#1769aa;stroke-width:2.5}}.io{{fill:#e8f6ed;stroke:#287a45;stroke-width:2.5}}.process{{fill:#fff5d8;stroke:#9a6a00;stroke-width:2.5}}.decision{{fill:#f7e9ff;stroke:#75449a;stroke-width:2.5}}.arrow{{fill:none;stroke:#263746;stroke-width:2.5}}</style>
{''.join(links)}{''.join(shapes)}</svg>'''
    (ASSETS / name).write_text(content)

svg("average_sequence.svg", "Sequence flowchart: average three values", [
    ("s","terminal","START",205,25),("i","io","Input a, b, c",205,140),("p","process","avg = (a + b + c) / 3",205,255),("o","io","Print avg",205,370),("e","terminal","STOP",205,485)], [("s","i","",""),("i","p","",""),("p","o","",""),("o","e","","")], height=590)
svg("bonus_decision.svg", "Bonus decision flowchart", [
    ("s","terminal","START",205,20),("i","io","Input salary",205,120),("d","decision","salary >= 6000?",205,230),("yes","process","Bonus = 0.06 x salary",45,430),("no","process","Bonus = 250",365,430),("o","io","Print Bonus",205,590),("e","terminal","STOP",205,700)], [("s","i","",""),("i","d","",""),("d","yes","Yes","branch_left"),("d","no","No","branch_right"),("yes","o","",""),("no","o","",""),("o","e","","")], height=800)
svg("sum_1_to_100.svg", "Pre-test loop flowchart: sum integers from 1 to 100", [
    ("s","terminal","START",205,20),("init","process","Sum = 0; N = 1",205,120),("d","decision","N <= 100?",205,230),("add","process","Sum = Sum + N",205,410),("inc","process","N = N + 1",205,520),("out","io","Print Sum",365,650),("e","terminal","STOP",365,755)], [("s","init","",""),("init","d","",""),("d","add","Yes",""),("add","inc","",""),("inc","d","","back"),("d","out","No","branch_right"),("out","e","","")], height=860)
svg("factorial_loop.svg", "Pre-test loop flowchart: factorial of positive N", [
    ("s","terminal","START",205,20),("i","io","Input N",205,115),("init","process","I = 0; PROD = 1",205,210),("d","decision","I < N?",205,320),("inc","process","I = I + 1",205,500),("mul","process","PROD = PROD x I",205,610),("out","io","Print PROD",365,755),("e","terminal","STOP",365,860)], [("s","i","",""),("i","init","",""),("init","d","",""),("d","inc","Yes",""),("inc","mul","",""),("mul","d","","back"),("d","out","No","branch_right"),("out","e","","")], height=960)
svg("six_scores.svg", "Sequence flowchart: add six test scores", [
    ("s","terminal","START",205,20),("init","process","Sum = 0",205,105),("i1","io","Get first test score",205,200),("a1","process","Add first score to Sum",205,295),("i2","io","Get second test score",205,390),("a2","process","Add second score to Sum",205,485),("i3","io","Get third test score",205,580),("a3","process","Add third score to Sum",205,675),("i4","io","Get fourth test score",205,770),("a4","process","Add fourth score to Sum",205,865),("i5","io","Get fifth test score",205,960),("a5","process","Add fifth score to Sum",205,1055),("i6","io","Get sixth test score",205,1150),("a6","process","Add sixth score to Sum",205,1245),("o","io","Output Sum",205,1340),("e","terminal","STOP",205,1435)], [("s","init","",""),("init","i1","",""),("i1","a1","",""),("a1","i2","",""),("i2","a2","",""),("a2","i3","",""),("i3","a3","",""),("a3","i4","",""),("i4","a4","",""),("a4","i5","",""),("i5","a5","",""),("a5","i6","",""),("i6","a6","",""),("a6","o","",""),("o","e","","")], height=1540)
svg("grade_decision.svg", "Decision flowchart: pass at average 60 or higher", [
    ("s","terminal","START",205,20),("i","io","Input four marks",205,120),("p","process","Avg = (Mark1 + Mark2 + Mark3 + Mark4) / 4",205,230),("d","decision","Avg >= 60?",205,370),("yes","io","Print Pass",45,570),("no","io","Print Fail",365,570),("e","terminal","STOP",205,730)], [("s","i","",""),("i","p","",""),("p","d","",""),("d","yes","Yes","branch_left"),("d","no","No","branch_right"),("yes","e","",""),("no","e","","")], height=830)
svg("bonus_strict_boundary.svg", "Incorrect bonus boundary: salary greater than 6000", [
    ("s","terminal","START",205,20),("i","io","Input salary",205,120),("d","decision","salary > 6000?",205,230),("yes","process","Bonus = 0.06 x salary",45,430),("no","process","Bonus = 250",365,430),("o","io","Print Bonus",205,590),("e","terminal","STOP",205,700)], [("s","i","",""),("i","d","",""),("d","yes","Yes","branch_left"),("d","no","No","branch_right"),("yes","o","",""),("no","o","",""),("o","e","","")], height=800)
svg("sum_missing_update.svg", "Faulty sum loop: counter update is missing", [
    ("s","terminal","START",205,20),("init","process","Sum = 0; N = 1",205,120),("d","decision","N <= 100?",205,230),("add","process","Sum = Sum + N",205,410),("out","io","Print Sum",365,650),("e","terminal","STOP",365,755)], [("s","init","",""),("init","d","",""),("d","add","Yes",""),("add","d","","back"),("d","out","No","branch_right"),("out","e","","")], height=860)
svg("incomplete_flow.svg", "Incomplete flowchart without an ending terminal", [
    ("s","terminal","START",205,25),("i","io","Input value",205,145),("p","process","Calculate result",205,265),("o","io","Print result",205,385)], [("s","i","",""),("i","p","",""),("p","o","","")], height=520)
svg("max_of_three.svg", "Largest of three positive unequal values", [
    ("s","terminal","START",235,20),("i","io","Input a, b, c",235,110),("init","process","Big = a",235,200),("d1","decision","b > Big?",235,300),("ub","process","Big = b",35,480),("d2","decision","c > Big?",235,620),("uc","process","Big = c",35,800),("o","io","Print Big",235,960),("e","terminal","STOP",235,1060)], [("s","i","",""),("i","init","",""),("init","d1","",""),("d1","ub","Yes","branch_left"),("ub","d2","",""),("d1","d2","No","branch_right"),("d2","uc","Yes","branch_left"),("uc","o","",""),("d2","o","No","branch_right"),("o","e","","")], width=700,height=1150)

(ASSETS/"loop_test_placement.svg").write_text('''<svg xmlns="http://www.w3.org/2000/svg" width="960" height="760" viewBox="0 0 960 760" role="img" aria-labelledby="title desc"><title id="title">Pre-test and post-test loop flowcharts</title><desc id="desc">Two flowcharts compare a condition before the process with a condition after the process.</desc><defs><marker id="a" markerWidth="10" markerHeight="10" refX="8" refY="5" orient="auto"><path d="M0 0L10 5L0 10z" fill="#263746"/></marker></defs><style>text{font:18px Arial;fill:#172b3a}.head{font-weight:bold;font-size:23px}.t{fill:#e5f2ff;stroke:#1769aa;stroke-width:3}.p{fill:#fff5d8;stroke:#9a6a00;stroke-width:3}.d{fill:#f7e9ff;stroke:#75449a;stroke-width:3}.a{fill:none;stroke:#263746;stroke-width:3;marker-end:url(#a)}.lab{font-size:16px;font-weight:bold}</style><text class="head" x="240" y="42" text-anchor="middle">Pre-test</text><text class="head" x="720" y="42" text-anchor="middle">Post-test</text><rect class="t" x="155" y="70" width="170" height="58" rx="29"/><text x="240" y="106" text-anchor="middle">START</text><polygon class="d" points="240,165 345,215 240,265 135,215"/><text x="240" y="221" text-anchor="middle">Condition?</text><rect class="p" x="155" y="335" width="170" height="70"/><text x="240" y="377" text-anchor="middle">Process step</text><rect class="t" x="155" y="520" width="170" height="58" rx="29"/><text x="240" y="556" text-anchor="middle">STOP</text><path class="a" d="M240 128L240 165"/><path class="a" d="M240 265L240 335"/><text class="lab" x="250" y="302">Yes</text><path class="a" d="M135 215L90 215L90 550L155 550"/><text class="lab" x="98" y="202">No</text><path class="a" d="M325 370L385 370L385 215L345 215"/><text class="lab" x="350" y="350">repeat</text><rect class="t" x="635" y="70" width="170" height="58" rx="29"/><text x="720" y="106" text-anchor="middle">START</text><rect class="p" x="635" y="185" width="170" height="70"/><text x="720" y="227" text-anchor="middle">Process step</text><polygon class="d" points="720,315 825,365 720,415 615,365"/><text x="720" y="371" text-anchor="middle">Condition?</text><rect class="t" x="635" y="535" width="170" height="58" rx="29"/><text x="720" y="571" text-anchor="middle">STOP</text><path class="a" d="M720 128L720 185"/><path class="a" d="M720 255L720 315"/><path class="a" d="M615 365L565 365L565 220L635 220"/><text class="lab" x="570" y="350">Yes</text><path class="a" d="M720 415L720 535"/><text class="lab" x="732" y="480">No</text></svg>''')

(ASSETS/"page_connectors.svg").write_text('''<svg xmlns="http://www.w3.org/2000/svg" width="900" height="560" viewBox="0 0 900 560" role="img" aria-labelledby="title desc"><title id="title">On-page and off-page flowchart connectors</title><desc id="desc">A sample flow continues through a labeled off-page connector to the second page; a circle marks an on-page connection.</desc><defs><marker id="a" markerWidth="10" markerHeight="10" refX="8" refY="5" orient="auto"><path d="M0 0L10 5L0 10z" fill="#263746"/></marker></defs><style>text{font:18px Arial;fill:#172b3a}.head{font-weight:bold;font-size:22px}.t{fill:#e5f2ff;stroke:#1769aa;stroke-width:3}.p{fill:#fff5d8;stroke:#9a6a00;stroke-width:3}.io{fill:#e8f6ed;stroke:#287a45;stroke-width:3}.off{fill:#fce9e9;stroke:#aa3333;stroke-width:3}.on{fill:#f7e9ff;stroke:#75449a;stroke-width:3}.a{fill:none;stroke:#263746;stroke-width:3;marker-end:url(#a)}</style><rect x="15" y="15" width="420" height="525" fill="none" stroke="#8899a6" stroke-dasharray="8 7"/><rect x="465" y="15" width="420" height="525" fill="none" stroke="#8899a6" stroke-dasharray="8 7"/><text class="head" x="225" y="48" text-anchor="middle">Page 1</text><text class="head" x="675" y="48" text-anchor="middle">Page 2</text><rect class="t" x="130" y="75" width="190" height="58" rx="29"/><text x="225" y="111" text-anchor="middle">START</text><polygon class="io" points="150,175 320,175 300,235 130,235"/><text x="225" y="211" text-anchor="middle">Input value</text><path class="a" d="M225 133L225 175"/><path class="a" d="M225 235L225 285"/><path class="off" d="M165 285H285V330L225 370L165 330Z"/><text x="225" y="324" text-anchor="middle">A</text><text x="225" y="393" text-anchor="middle">Off-page</text><path class="a" d="M285 307L510 307L510 285"/><path class="off" d="M615 285H735V330L675 370L615 330Z"/><text x="675" y="324" text-anchor="middle">A</text><text x="675" y="393" text-anchor="middle">Continue</text><path class="a" d="M675 285L675 190"/><rect class="p" x="590" y="115" width="170" height="75"/><text x="675" y="160" text-anchor="middle">Process step</text><path class="a" d="M675 115L675 75"/><rect class="t" x="590" y="20" width="170" height="55" rx="27"/><text x="675" y="54" text-anchor="middle">STOP</text><circle class="on" cx="375" cy="455" r="28"/><text x="375" y="462" text-anchor="middle">B</text><text x="225" y="462" text-anchor="middle">On-page connector</text><path class="a" d="M285 455L347 455"/><path class="a" d="M403 455L470 455"/><text x="675" y="465" text-anchor="middle">Matching connector rejoins the same-page path</text></svg>''')

# Correct connector illustration: paired B circles stay on page 1; matching A
# off-page symbols mark the cross-page continuation, followed top-to-bottom.
(ASSETS/"page_connectors.svg").write_text('''<svg xmlns="http://www.w3.org/2000/svg" width="900" height="560" viewBox="0 0 900 560" role="img" aria-labelledby="title desc"><title id="title">On-page and off-page flowchart connectors</title><desc id="desc">Matching A off-page symbols continue a chart from page one to page two. Two matching B circles connect separated parts on page one.</desc><defs><marker id="a" markerWidth="10" markerHeight="10" refX="8" refY="5" orient="auto"><path d="M0 0L10 5L0 10z" fill="#263746"/></marker></defs><style>text{font:18px Arial;fill:#172b3a}.head{font-weight:bold;font-size:22px}.t{fill:#e5f2ff;stroke:#1769aa;stroke-width:3}.p{fill:#fff5d8;stroke:#9a6a00;stroke-width:3}.io{fill:#e8f6ed;stroke:#287a45;stroke-width:3}.off{fill:#fce9e9;stroke:#aa3333;stroke-width:3}.on{fill:#f7e9ff;stroke:#75449a;stroke-width:3}.a{fill:none;stroke:#263746;stroke-width:3;marker-end:url(#a)}</style><rect x="15" y="15" width="420" height="525" fill="none" stroke="#8899a6" stroke-dasharray="8 7"/><rect x="465" y="15" width="420" height="525" fill="none" stroke="#8899a6" stroke-dasharray="8 7"/><text class="head" x="225" y="48" text-anchor="middle">Page 1</text><text class="head" x="675" y="48" text-anchor="middle">Page 2</text><rect class="t" x="130" y="75" width="190" height="58" rx="29"/><text x="225" y="111" text-anchor="middle">START</text><polygon class="io" points="150,175 320,175 300,235 130,235"/><text x="225" y="211" text-anchor="middle">Input value</text><path class="a" d="M225 133L225 175"/><path class="a" d="M225 235L225 285"/><path class="off" d="M165 285H285V330L225 370L165 330Z"/><text x="225" y="324" text-anchor="middle">A</text><text x="225" y="393" text-anchor="middle">Off-page</text><path class="off" d="M615 75H735V120L675 160L615 120Z"/><text x="675" y="114" text-anchor="middle">A</text><path class="a" d="M675 160L675 190"/><rect class="p" x="590" y="190" width="170" height="75"/><text x="675" y="235" text-anchor="middle">Process step</text><path class="a" d="M675 265L675 320"/><rect class="t" x="590" y="320" width="170" height="58" rx="29"/><text x="675" y="356" text-anchor="middle">STOP</text><circle class="on" cx="120" cy="465" r="28"/><text x="120" y="472" text-anchor="middle">B</text><circle class="on" cx="330" cy="465" r="28"/><text x="330" y="472" text-anchor="middle">B</text><text x="225" y="425" text-anchor="middle">Two matching on-page connectors</text><path class="a" d="M50 465L92 465"/><path class="a" d="M358 465L405 465"/><text x="225" y="520" text-anchor="middle">Same-page chart parts join at matching B circles</text><text x="675" y="435" text-anchor="middle">A continues from Page 1</text></svg>''')

def mcq(i, q, opts, ans, expl, source, objective, operation, diagram=None):
    rec={"id":f"FLOW-{i:03d}","question":q,"options":opts,"correctIndex":ans,"expectedAnswer":opts[ans],"explanation":expl,"source":source,"objective":objective,"operation":operation}
    if diagram: rec["stimulusAsset"] = f"diagrams/{diagram}"
    return rec

items = [
mcq(1,"Which flowchart symbol marks the beginning or end of a chart?",["Oval terminal","Parallelogram","Rectangle","Diamond"],0,"The oval terminal represents START or STOP.","PDF p. 5; flow.md ‘The symbols’","symbol_meanings","recall a symbol meaning"),
mcq(2,"A flowchart step reads a value from the user. Which symbol should contain that step?",["Diamond","Parallelogram","Oval","Rectangle"],1,"Input and output operations, including READ, use a parallelogram.","PDF p. 5; flow.md ‘The symbols’","symbol_meanings","select a symbol for an operation"),
mcq(3,"A step assigns Sum = Sum + N. Which symbol matches the operation?",["Rectangle","Oval","Diamond","Parallelogram"],0,"An assignment or calculation is a process, shown in a rectangle.","PDF p. 5; flow.md ‘The symbols’","symbol_meanings","select a symbol for an operation"),
mcq(4,"What does every line connecting flowchart steps need to show?",["A circle","An arrow indicating direction","A Yes/No label","A number"],1,"The source states each flow line needs an arrow to show direction.","PDF p. 6; flow.md ‘The symbols’","flowchart_rules","recall a flow-line rule"),
mcq(5,"What is the usual direction in which a flowchart proceeds?",["Bottom to top","Right to left only","Top to bottom","In a circle"],2,"The chart generally flows from top to bottom.","PDF p. 8; flow.md ‘The rules, in one breath’","flowchart_rules","recall a layout convention"),
mcq(6,"[Diagram] In this average-of-three flowchart, which value is printed?",["The input value a only","The computed average of a, b, and c","The sum before division","The number 3"],1,"The process computes (a+b+c)/3 and the next I/O symbol prints avg.","PDF p. 13; flow.md ‘Structure 1 — Sequence’","sequence_and_dataflow","trace a sequence chart","average_sequence.svg"),
mcq(7,"[Diagram] If a=6, b=9, and c=12, what does the flowchart print?",["9","27","3","12"],0,"The sum is 27 and dividing by 3 gives 9.","PDF p. 13; flow.md ‘Structure 1 — Sequence’","sequence_and_dataflow","execute a sequence chart","average_sequence.svg"),
mcq(8,"[Diagram] In the average chart, what happens immediately after the three inputs are read?",["The chart stops","It prints avg","It calculates avg = (a+b+c)/3","It asks a decision question"],2,"The rectangle calculates the average before the output step.","PDF p. 13; flow.md ‘Structure 1 — Sequence’","sequence_and_dataflow","trace order in a sequence chart","average_sequence.svg"),
mcq(9,"A diamond asks whether salary is at least EGP 6,000. How many exits should leave the decision?",["One","Two","Three","Four"],1,"A decision has two exits, such as Yes/No or True/False.","PDF p. 6, 11; flow.md ‘The symbols’","decision_structure","apply the two-exit rule"),
mcq(10,"[Diagram] An employee earns EGP 5,500. Which path and bonus does the chart select?",["Yes; EGP 330","No; EGP 250","Yes; EGP 250","No; EGP 330"],1,"5500 >= 6000 is false, so the No branch assigns a fixed EGP 250.","PDF p. 17; flow.md ‘Structure 2 — Decision’","decision_structure","trace a decision chart","bonus_decision.svg"),
mcq(11,"[Diagram] What bonus does this chart assign to a salary of exactly EGP 6,000?",["EGP 250","EGP 360","EGP 6,000","EGP 0"],1,"The condition includes equality, and 6% of 6000 is 360.","PDF p. 17; flow.md boundary discussion","decision_structure","apply a boundary condition","bonus_decision.svg"),
mcq(12,"[Diagram] Which condition would change the chart so that a salary of exactly EGP 6,000 takes the No branch?",["salary >= 6000","salary > 6000","salary < 6000","salary = 6000"],1,"With >, equality is false, so exactly 6000 would take No.","PDF p. 17; flow.md boundary discussion","decision_structure","diagnose a changed boundary","bonus_decision.svg"),
mcq(13,"Why do both branches of the bonus decision rejoin before Print Bonus?",["So the salary is read twice","So one shared output step runs after either branch","So the chart has three decision exits","So the No branch skips the bonus assignment"],1,"The branches assign Bonus differently, then share one print operation.","flow.md ‘Structure 2 — Decision’","decision_structure","interpret branch convergence"),
mcq(14,"Which statement correctly describes an on-page connector?",["A circle joining separated parts of a chart on the same page","A diamond that repeats a calculation","A terminal placed at every decision exit","A parallelogram used only for input"],0,"The circle connector joins separated portions of the flowchart.","PDF p. 7, 9; flow.md ‘The symbols’","connectors_and_layout","distinguish connector function"),
mcq(15,"When is an off-page connector useful?",["When a chart continues onto another page","Whenever a calculation uses two inputs","To mark the end of every algorithm","To replace all arrows"],0,"The off-page connector marks where a chart continues on another page.","PDF p. 7; flow.md ‘The symbols’","connectors_and_layout","select connector use"),
mcq(16,"[Diagram] What is the first value of N tested in the sum-from-1-to-100 chart?",["0","1","100","101"],1,"N is initialized to 1 before the condition N <= 100 is tested.","PDF p. 15; flow.md ‘Adding the integers from 1 to 100’","loops_and_iteration","trace loop initialization","sum_1_to_100.svg"),
mcq(17,"[Diagram] After the first pass through the sum loop, what are Sum and N?",["Sum=0, N=2","Sum=1, N=2","Sum=1, N=1","Sum=2, N=2"],1,"The chart adds the current N (1), then increments N to 2.","PDF p. 15; flow.md ‘Adding the integers from 1 to 100’","loops_and_iteration","trace state updates","sum_1_to_100.svg"),
mcq(18,"[Diagram] What value is printed by the completed sum chart?",["5000","5050","100","101"],1,"It adds every integer from 1 through 100, whose total is 5050.","PDF p. 15; flow.md ‘Adding the integers from 1 to 100’","loops_and_iteration","interpret a loop result","sum_1_to_100.svg"),
mcq(19,"[Diagram] When does the sum chart leave the loop and print Sum?",["When N <= 100 is true","When N becomes 100","When N <= 100 is false","Before the first addition"],2,"The No exit from N <= 100 leads to Print Sum.","PDF p. 15; flow.md ‘Adding the integers from 1 to 100’","loops_and_iteration","interpret loop exit condition","sum_1_to_100.svg"),
mcq(20,"A loop checks its condition before any loop-body action. What kind of loop is this?",["Post-test","Pre-test","Off-page","Sequence"],1,"A pre-test loop checks first, so it may run zero times.","PDF p. 12; flow.md ‘Pre-test and post-test loops’","loop_types","classify a loop by test position"),
mcq(21,"What is guaranteed by a post-test loop as described in the lesson?",["Its body runs at least once before the condition is checked","Its body can never repeat","Its condition is checked before the body","It always runs exactly twice"],0,"A post-test loop checks after its work, so the body runs at least once.","PDF p. 12; flow.md ‘Pre-test and post-test loops’","loop_types","infer a post-test property"),
mcq(22,"[Diagram] Which part of the sum chart makes it a loop rather than a one-pass sequence?",["The START terminal","The backward arrow from the update to the condition","The output parallelogram","The initialization rectangle"],1,"The backward arrow returns control to the condition for another test.","PDF p. 10, 15; flow.md ‘Structure 3 — Loop’","loops_and_iteration","identify loop structure","sum_1_to_100.svg"),
mcq(23,"[Diagram] For N=4 in the factorial chart, what is PROD after the first complete loop pass?",["0","1","4","24"],1,"I starts at 0 and PROD at 1. On the first pass, I is incremented to 1 and PROD is multiplied by 1, so PROD remains 1.","PDF p. 16; flow.md ‘Structure 3 — Loop’","factorial_algorithm","trace factorial state","factorial_loop.svg"),
mcq(24,"[Diagram] For N=4, which sequence of I values is multiplied into PROD?",["0, 1, 2, 3","1, 2, 3, 4","2, 3, 4, 5","4 only"],1,"Each pass increments I before multiplication, producing factors 1 through 4.","PDF p. 16; flow.md ‘Structure 3 — Loop’","factorial_algorithm","trace loop update order","factorial_loop.svg"),
mcq(25,"[Diagram] What does the factorial chart print when N=5?",["15","25","120","720"],2,"The chart multiplies 1×2×3×4×5, giving 120.","PDF p. 16; flow.md ‘Structure 3 — Loop’","factorial_algorithm","execute an accumulator loop","factorial_loop.svg"),
mcq(26,"[Diagram] At which tested value of I does the factorial chart stop when N=5?",["I=4","I=5","I=6","I=0"],2,"After the pass at I=5, I becomes 6 and the condition I<N is false.","PDF p. 16; flow.md ‘Structure 3 — Loop’","factorial_algorithm","trace loop termination","factorial_loop.svg"),
mcq(27,"[Diagram] The six-score chart reads six values and adds each to Sum. If the scores are 26, 49, 98, 87, 62, and 75, what is Output Sum?",["387","397","407","417"],1,"The running totals are 26, 75, 173, 260, 322, and 397; the chart outputs 397.","PDF pp. 18–20; flow.md ‘The symbols’","sequence_and_dataflow","trace a multi-step accumulation","six_scores.svg"),
mcq(28,"[Diagram] In the six-score chart, what is the purpose of the repeated Add-score boxes?",["They compare every score with 60","They accumulate each entered score into Sum","They divide each score by six","They reset Sum after every input"],1,"Each process box adds the newly read score to the running total.","PDF pp. 18–20","sequence_and_dataflow","interpret accumulator steps","six_scores.svg"),
mcq(29,"A flowchart reaches an output step and then has no ending symbol. Which source rule is violated?",["Every chart ends with a terminal","Every process uses a rectangle","A decision has exactly two exits","All flowcharts must contain a loop"],0,"A flowchart should end with a terminal symbol such as STOP.","PDF p. 8; flow.md ‘The rules, in one breath’","flowchart_rules","diagnose a chart completion issue"),
mcq(30,"Which option best distinguishes a flowchart from pseudocode?",["A flowchart uses shapes and arrows; pseudocode uses English-like statements","A flowchart is exact Python; pseudocode is a computer device","A flowchart is always a program; pseudocode is always an algorithm","A flowchart has no order; pseudocode must use arrows"],0,"Flowcharts are graphical; pseudocode expresses operations in words and phrases without strict program syntax.","PDF pp. 21, 25; flow.md ‘Pseudocode: the middle step’","representations","distinguish representations"),
mcq(31,'Which statement about pseudocode is correct?',["It must obey Python syntax exactly","It is English-like and does not strictly follow a programming language's syntax","It is a diagram with no words","It is the same as executable machine code"],1,"The source describes pseudocode as English-like statements whose syntax is not strictly followed.","PDF p. 21; flow.md ‘Pseudocode: the middle step’","pseudocode_concepts","recall a pseudocode property"),
mcq(32,"Which item is an exact language-specific program rather than pseudocode?",["Read n1, n2","Sum = n1 + n2","if Avg >= 60: print('Pass')","End"],2,"The lesson distinguishes a program as exact code following a language's rules.","PDF pp. 21, 25; flow.md ‘Pseudocode: the middle step’","representations","classify a representation"),
mcq(33,"[Diagram] Which condition in the grade decision chart makes an average of exactly 60 pass?",["Avg > 60","Avg >= 60","Avg < 60","Avg != 60"],1,"The chart uses >= 60, including equality.","PDF pp. 23–24; flow.md ‘Determining a student's final grade’","pseudocode_and_decisions","interpret a threshold chart","grade_decision.svg"),
mcq(34,"[Diagram] A student's four marks average 59.75. Which output path is followed?",["Print Pass","Print Fail","Print both","No output"],1,"59.75 is below 60, so the No branch prints Fail.","PDF pp. 23–24; flow.md ‘Determining a student's final grade’","pseudocode_and_decisions","apply a decision chart","grade_decision.svg"),
mcq(35,"[Diagram] A student's marks are 55, 70, 62, and 48. What does the grade chart print?",["Pass","Fail","60","No output"],1,"The sum is 235; the average is 58.75, below 60, so it prints Fail.","PDF pp. 23–24; flow.md ‘Determining a student's final grade’","pseudocode_and_decisions","trace calculation and branch","grade_decision.svg"),
mcq(36,'Why can a flowchart make a missing branch or disconnected step easier to notice before coding?',["The chart presents the ordered paths visibly","A flowchart automatically runs the program","The chart replaces the need to define a rule","A flowchart hides decisions in paragraphs"],0,"A visible diagram makes path structure and breaks easier to inspect.","PDF pp. 2–3; flow.md ‘Why bother drawing it?’","purpose_and_benefits","infer a stated benefit"),
mcq(37,"A complex flowchart is split across two pages. Which symbol marks where its path continues on the next page?",["Oval terminal","Off-page connector","Decision diamond","Input parallelogram"],1,"The off-page connector marks a continuation between pages.","PDF p. 7; flow.md ‘The symbols’","connectors_and_layout","select a continuation symbol"),
mcq(38,"In a decision chart, the condition is written as a question. What are suitable labels for its two outgoing paths?",["Start and Stop","Input and Output","Yes and No","Read and Print"],2,"The two paths may be labeled Yes/No or True/False.","PDF p. 11; flow.md ‘The symbols’","decision_structure","select branch labels"),
mcq(39,"[Diagram] Which part of the bonus chart should change if the policy becomes ‘EGP 6,000 or more receives 7%’?",["Change the decision to salary > 6000 only","Change the Yes-branch calculation to 0.07 × salary","Change the No branch to print 7,000","Remove the shared output step"],1,"The threshold stays inclusive; the bonus calculation changes from 6% to 7%.","PDF p. 17; flow.md ‘Structure 2 — Decision’","decision_structure","adapt a chart to a changed rule","bonus_decision.svg"),
mcq(40,'A reader wants to explain a business rule to a manager who does not write Python. Which benefit of a flowchart is most relevant?',["It communicates the logic visually before coding","It guarantees that the final program has no bugs","It makes every algorithm shorter than code","It lets a computer infer missing requirements"],0,"The lesson says flowcharts communicate rules to people who do not write Python.","PDF p. 3; flow.md ‘Why bother drawing it?’","purpose_and_benefits","apply a stated benefit"),
]

essays = [
{"id":"FLOW-E01","prompt":"Use the attached average-of-three flowchart. Trace it for a=6, b=9, c=12. Then describe one change to the chart that would make it calculate the sum instead of the average.","responseType":"trace plus chart modification","marks":5,"expectedAnswer":"The process computes (6+9+12)/3=9 and prints 9. To calculate the sum, change the process box to avg = a+b+c (or Sum = a+b+c); the input, output, and terminal sequence can otherwise remain.","rubric":[{"criterion":"Follows the chart in order from input through output","points":1},{"criterion":"Calculates the sum 27","points":1},{"criterion":"Divides by 3 for the chart's current result","points":1},{"criterion":"Gives the current output 9","points":1},{"criterion":"Specifies a correct process-box change to output the sum 27","points":1}],"source":"PDF p. 13; flow.md ‘Structure 1 — Sequence’","operation":"trace and modify a sequence chart","stimulusAsset":"diagrams/average_sequence.svg"},
{"id":"FLOW-E02","prompt":"Use the attached bonus flowchart. For salaries of EGP 5,500 and EGP 6,000, show the branch and bonus for each. Explain why replacing >= with > changes the EGP 6,000 case.","responseType":"two traces plus explanation","marks":5,"expectedAnswer":"At 5500 the condition is false, so No assigns 250. At 6000 the inclusive condition is true, so Yes assigns 0.06×6000=360. With >, equality is false and the 6000 salary would instead receive 250.","rubric":[{"criterion":"Correctly traces 5500 to No","points":1},{"criterion":"Gives EGP 250 for 5500","points":1},{"criterion":"Correctly traces 6000 to Yes and computes EGP 360","points":1},{"criterion":"Explains that > excludes equality","points":1},{"criterion":"Gives EGP 250 as the changed-condition outcome at 6000","points":1}],"source":"PDF p. 17; flow.md ‘Structure 2 — Decision’ and boundary discussion","operation":"trace and evaluate a decision boundary","stimulusAsset":"diagrams/bonus_decision.svg"},
{"id":"FLOW-E03","prompt":"Use the attached sum-from-1-to-100 flowchart. Complete a short trace for its first three loop passes, recording (N before test, Sum after addition, N after increment). State the final output.","responseType":"trace table","marks":5,"expectedAnswer":"Passes: (1,1,2), (2,3,3), (3,6,4). The chart continues through N=100 and prints 5050.","rubric":[{"criterion":"First pass state (1,1,2)","points":1},{"criterion":"Second pass state (2,3,3)","points":1},{"criterion":"Third pass state (3,6,4)","points":1},{"criterion":"Explains that condition is tested before each pass","points":1},{"criterion":"Gives final sum 5050","points":1}],"source":"PDF p. 15; flow.md ‘Adding the integers from 1 to 100’","operation":"trace a pre-test accumulator chart","stimulusAsset":"diagrams/sum_1_to_100.svg"},
{"id":"FLOW-E04","prompt":"Use the attached factorial flowchart for N=4. Trace I and PROD through every pass, show the first failing condition, and give the printed result.","responseType":"trace table","marks":5,"expectedAnswer":"Start I=0, PROD=1. Test 0<4; increment I to 1 and multiply, PROD=1. Then I=2, PROD=2; I=3, PROD=6; I=4, PROD=24. Increment after the final pass reaches I=5; 5<4 is false, so print 24.","rubric":[{"criterion":"Correctly states initialization and first pass (I=1, PROD=1)","points":1},{"criterion":"Correctly traces the next two products (2 then 6)","points":1},{"criterion":"Correct final-pass product is 24 at I=4","points":1},{"criterion":"Shows I becomes 5 and the condition fails","points":1},{"criterion":"Gives printed result 24","points":1}],"source":"PDF p. 16; flow.md ‘Structure 3 — Loop’","operation":"trace a factorial accumulator chart","stimulusAsset":"diagrams/factorial_loop.svg"},
{"id":"FLOW-E05","prompt":"Design a flowchart for a decision with two outcomes that rejoin before the single STOP terminal. Use this rule: input a mark average; print Pass when it is at least 60, otherwise print Fail. Submit either a drawn chart or a node-and-arrow list naming the symbol for every step and both branch labels.","responseType":"flowchart construction","marks":5,"expectedAnswer":"START terminal → input average parallelogram → decision diamond Avg >= 60?; Yes → output Pass parallelogram; No → output Fail parallelogram; both paths join → STOP terminal.","rubric":[{"criterion":"Includes START and STOP terminals","points":1},{"criterion":"Uses input/output parallelogram for average input","points":1},{"criterion":"Uses decision diamond with inclusive condition Avg >= 60","points":1},{"criterion":"Has correctly labeled Yes/No paths to Pass and Fail outputs","points":1},{"criterion":"Rejoins branches before a single end terminal","points":1}],"source":"PDF pp. 5–6, 11, 23–24; flow.md ‘The symbols’ and grade example","operation":"construct a decision flowchart"},
{"id":"FLOW-E06","prompt":"A student draws a loop that checks N <= 100 before adding N, starts with N=1 and Sum=0, adds N, increments N, and returns to the test. Explain whether this is pre-test or post-test, whether the body could run zero times if the initial N were changed to 101, and why.","responseType":"concept explanation with trace condition","marks":5,"expectedAnswer":"It is pre-test because the condition is checked before the body. If N starts at 101, 101<=100 is false immediately, so the body runs zero times and the chart proceeds to output. The condition controls entry into the loop.","rubric":[{"criterion":"Identifies the loop as pre-test","points":1},{"criterion":"Explains the condition is checked before loop work","points":1},{"criterion":"Evaluates 101<=100 as false","points":1},{"criterion":"States the body runs zero times","points":1},{"criterion":"Connects the result to pre-test behavior and chart exit","points":1}],"source":"PDF p. 12, 15; flow.md ‘Pre-test and post-test loops’","operation":"infer behavior from loop test position"},
{"id":"FLOW-E07","prompt":'Assume the second input is nonzero. Write pseudocode to read two numbers and display their sum, difference, product, and quotient. Then explain one way pseudocode differs from a language-specific program.',"responseType":"pseudocode plus comparison","marks":5,"expectedAnswer":"Read n1,n2; Sum=n1+n2; Diff=n1−n2; Mult=n1*n2; Quot=n1/n2; Print Sum,Diff,Mult,Quot; End. Pseudocode uses English-like steps without strict language syntax; a program follows exact syntax rules.","rubric":[{"criterion":"Reads both inputs","points":1},{"criterion":"Correctly specifies sum and difference","points":1},{"criterion":"Correctly specifies product and quotient","points":1},{"criterion":"Includes output and an end step","points":1},{"criterion":"Explains syntax distinction between pseudocode and program","points":1}],"source":"PDF pp. 21–22, 25; flow.md ‘Pseudocode: the middle step’","operation":"write pseudocode and distinguish representation"},
{"id":"FLOW-E08","prompt":"Use the attached six-score flowchart and the scores 26, 49, 98, 87, 62, 75. Show the running Sum after each score, give the final output, and identify whether the chart contains a decision or a loop.","responseType":"trace and structure identification","marks":5,"expectedAnswer":"Running sums: 26, 75, 173, 260, 322, 397. Output is 397. It is a sequence with repeated fixed steps; the displayed chart has no decision diamond or loop/backward arrow.","rubric":[{"criterion":"Correct running total after score 1: 26","points":1},{"criterion":"Correct running totals through score 3: 75 and 173","points":1},{"criterion":"Correct running totals through scores 4–6: 260, 322, 397","points":1},{"criterion":"Gives output 397","points":1},{"criterion":"Identifies the chart as a sequence with no decision or loop","points":1}],"source":"PDF pp. 18–20","operation":"trace and classify a multi-step sequence chart","stimulusAsset":"diagrams/six_scores.svg"}
]

# Keep keyed choices from standing out only because they are uniquely shortest
# or longest. Wording remains source-faithful; the correct answer follows text.
choice_edits = {
    2: ["Use a diamond to ask a yes-or-no question first", "Use a parallelogram for reading input", "Use an oval for starting or stopping", "Use a rectangle for a calculation"],
    4: ["A Yes/No label beside every flowchart connection", "A number showing each step's order", "A circle connector on each flow line", "An arrow indicating the line's direction"],
    6: ["Only the input value stored in a", "The average calculated from a, b, and c", "The sum of all three inputs before division", "The value 3 used as the divisor"],
    8: ["It adds a, b, and c, then divides their total by three to calculate avg", "It stops the chart and skips the average calculation entirely", "It sends the three inputs directly to an output without calculation", "It asks whether an input should be ignored before calculating the average"],
    13: ["So both paths can use one shared output step", "So the decision has three possible outcomes", "So the No path can skip assigning any bonus", "So the employee's salary is read again before printing"],
    14: ["A parallelogram that accepts input on the same page", "A circle linking separated parts on the same page", "A diamond that repeats one calculation on the chart", "A terminal that marks every exit from a decision"],
    15: ["When the chart's next part is located on another page", "When the connector should replace all arrows in a chart", "When an algorithm has reached its final step", "When a calculation uses two different input values"],
    21: ["The body runs once before the condition is checked", "The body is skipped whenever the condition is true", "The condition is checked before the body begins", "The body always repeats exactly two times"],
    22: ["The START terminal at the top of the chart", "The return arrow that sends control back to the test", "The output parallelogram at the bottom of the chart", "The initialization box that sets Sum and N"],
    28: ["They divide every entered score by six", "They reset Sum to zero before each new score", "They compare each score with a cutoff value of 60", "They add each newly entered score to the running total"],
    30: ["A flowchart has no order; pseudocode must use arrows to show steps", "A flowchart uses shapes and arrows; pseudocode uses English-like steps", "A flowchart is exact Python, while pseudocode is a device that runs code", "A flowchart is a program, while pseudocode is always a step-by-step algorithm"],
    31: ["It is executable machine code that the computer runs directly", "It must follow Python syntax exactly, including punctuation and indentation", "It uses English-like steps without requiring exact language syntax", "It is a graphical diagram made only from standard shapes and arrows"],
    32: ["The word End used alone as a pseudocode stopping step", "The input instruction Read n1,n2 written as a short phrase", "The assignment Sum=n1+n2 written as an arithmetic step", "The Python if statement that prints Pass when Avg >= 60"],
    38: ["The pair Input and Output as labels on the two paths", "The pair Yes and No, or True and False, on the paths", "The pair Read and Print as labels on the two paths", "The pair Start and Stop on each decision path"],
    39: ["Remove the shared output step after the two branches", "Change the condition to salary greater than 6000 only", "Change the Yes branch to calculate seven percent of salary", "Make the No branch assign a fixed bonus of 7,000 EGP instead"]
}
for item in items:
    n = int(item["id"].split("-")[-1])
    if n in choice_edits:
        correct = item["expectedAnswer"]
        item["options"] = choice_edits[n]
        # Preserve the correct response by its meaning after the choice rewrite.
        correct_by_id = {
            2: 1, 4: 3, 6: 1, 8: 0, 13: 0, 14: 1, 15: 0,
            21: 0, 22: 1, 28: 3, 30: 1, 31: 2, 32: 3, 38: 1, 39: 2
        }
        item["expectedAnswer"] = item["options"][correct_by_id[n]]
        item["correctIndex"] = correct_by_id[n]

by_id = {x["id"]: x for x in items}
by_id["FLOW-012"].update({
    "question":"[Diagram] For a salary of EGP 6,000, what path and bonus does this chart produce?",
    "options":["Yes; EGP 360","No; EGP 250","Yes; EGP 250","No; EGP 360"],
    "correctIndex":1,"expectedAnswer":"No; EGP 250",
    "explanation":"The chart uses > 6000, so equality takes No and assigns EGP 250. The stated policy uses >= 6000.",
    "source":"PDF p. 17; flow.md bonus boundary discussion","stimulusAsset":"diagrams/bonus_strict_boundary.svg"})
by_id["FLOW-014"]["stimulusAsset"]="diagrams/page_connectors.svg"
by_id["FLOW-014"]["question"]="[Diagram] Which statement correctly describes the B connectors shown?"
by_id["FLOW-015"]["stimulusAsset"]="diagrams/page_connectors.svg"
by_id["FLOW-015"]["question"]="[Diagram] When is the off-page connector shown used?"
by_id["FLOW-020"]["stimulusAsset"]="diagrams/loop_test_placement.svg"
by_id["FLOW-020"]["question"]="[Diagram] In which chart is the condition checked before any loop-body action?"
by_id["FLOW-021"]["stimulusAsset"]="diagrams/loop_test_placement.svg"
by_id["FLOW-021"]["question"]="[Diagram] Which loop chart guarantees that its process step happens at least once?"
by_id["FLOW-022"].update({
    "question":"[Diagram] The sum chart returns from adding Sum to the condition, but it has no N = N + 1 step. What happens?",
    "options":["It adds each value once because the chart loops","N stays 1, so the chart keeps adding 1 again","It stops immediately before adding N","It counts down to zero and then prints Sum"],
    "correctIndex":1,"expectedAnswer":"N stays 1, so the chart keeps adding 1 again",
    "explanation":"N starts at 1 and is never changed, so N <= 100 remains true and each pass adds 1 again.",
    "source":"PDF p. 15; flow.md sum 1–100 example","operation":"diagnose a missing loop update","stimulusAsset":"diagrams/sum_missing_update.svg"})
by_id["FLOW-028"].update({
    "question":"[Diagram] The chart receives a=8, b=12, and c=10. What value does it print as Big?",
    "options":["8","12","10","30"],"correctIndex":1,"expectedAnswer":"12",
    "explanation":"Big starts as 8, is updated to 12 because 12 is larger, and stays 12 when compared with 10.",
    "objective":"maximum_selection","operation":"trace sequential maximum comparisons",
    "source":"PDF p. 14; maximum-of-three example","stimulusAsset":"diagrams/max_of_three.svg"})
by_id["FLOW-029"]["stimulusAsset"]="diagrams/incomplete_flow.svg"
by_id["FLOW-029"]["question"]='[Diagram] The chart reaches Print result and then has no ending symbol. Which flowchart convention is violated?'

for i, item in enumerate(items):
    target = i % 4
    current = item["options"].index(item["expectedAnswer"])
    shift = current - target
    item["options"] = item["options"][shift:] + item["options"][:shift]
    item["correctIndex"] = target

import sys
sys.path.insert(0, str(ROOT.parent))
from explanation_overrides import apply_overrides
apply_overrides(ROOT.name, items)
(ROOT/"final_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in items)+"\n")
(ROOT/"essay_items.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in essays)+"\n")

print(f"created {len(items)} MCQs and {len(essays)} essays; SVGs={len(list(ASSETS.glob('*.svg')))}")
